// src/app/admin/lunch/menus/[id]/edit/page.tsx
'use client'

import React, { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'
import { useLunchStore, type LunchMenu } from '@/stores/lunch'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'

type NutritionalForm = {
  calories: string
  protein: string
  carbs: string
  fat: string
}

export default function AdminLunchMenuEditPage() {
  const router = useRouter()
  const params = useParams<{ id: string }>()
  const menuId = params?.id

  const supabase = useMemo(() => createClient(), [])
  const lunchStore = useLunchStore()

  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const [menu, setMenu] = useState<LunchMenu | null>(null)
  const [allergensInput, setAllergensInput] = useState('')

  const [form, setForm] = useState<{
    date: string
    meal_name: string
    description: string
    photo_url: string
  }>({
    date: new Date().toISOString().split('T')[0],
    meal_name: '',
    description: '',
    photo_url: '',
  })

  const [nutritionalInfo, setNutritionalInfo] = useState<NutritionalForm>({
    calories: '',
    protein: '',
    carbs: '',
    fat: '',
  })

  const handleDelete = async () => {
    if (!menuId) return
    if (!confirm('Are you sure you want to delete this menu? This action cannot be undone.')) return
    setSubmitting(true)
    setError('')
    try {
      await lunchStore.deleteMenu(menuId)
      router.push('/admin/lunch/menus')
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to delete menu')
    } finally {
      setSubmitting(false)
    }
  }

  useEffect(() => {
    const run = async () => {
      if (!menuId) {
        setError('Menu not found')
        setLoading(false)
        return
      }

      setLoading(true)
      setError('')

      try {
        const { data: menuData, error: menuError } = await supabase
          .from('lunch_menus')
          .select('*')
          .eq('id', menuId)
          .single()

        if (menuError) throw menuError
        if (!menuData) {
          setError('Menu not found')
          setMenu(null)
          return
        }

        const typed = menuData as LunchMenu
        setMenu(typed)
        setForm({
          date: typed.date,
          meal_name: typed.meal_name,
          description: typed.description || '',
          photo_url: typed.photo_url || '',
        })

        setAllergensInput((typed.allergens || []).join(', '))

        setNutritionalInfo({
          calories: typed.nutritional_info?.calories ?? '',
          protein: typed.nutritional_info?.protein ?? '',
          carbs: typed.nutritional_info?.carbs ?? '',
          fat: typed.nutritional_info?.fat ?? '',
        })
      } catch (err: unknown) {
        setError(err instanceof Error ? err.message : 'Failed to load menu')
      } finally {
        setLoading(false)
      }
    }

    void run()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [menuId])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!menuId) return

    setSubmitting(true)
    setError('')

    try {
      const allergens = allergensInput
        .split(',')
        .map((a) => a.trim())
        .filter((a) => a.length > 0)

      const nutritional: Record<string, string> = {}
      if (nutritionalInfo.calories.trim()) nutritional.calories = nutritionalInfo.calories.trim()
      if (nutritionalInfo.protein.trim()) nutritional.protein = nutritionalInfo.protein.trim()
      if (nutritionalInfo.carbs.trim()) nutritional.carbs = nutritionalInfo.carbs.trim()
      if (nutritionalInfo.fat.trim()) nutritional.fat = nutritionalInfo.fat.trim()

      await lunchStore.updateMenu(menuId, {
        date: form.date,
        meal_name: form.meal_name,
        description: form.description || undefined,
        allergens,
        nutritional_info: Object.keys(nutritional).length > 0 ? nutritional : {},
        photo_url: form.photo_url || undefined,
      })

      router.push(`/admin/lunch/menus/${menuId}`)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to update menu')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div>
      <div className="mb-6">
        <button
          type="button"
          onClick={() => router.push(`/admin/lunch/menus/${menuId}`)}
          className="text-gray-600 hover:text-gray-900 mb-4 inline-block"
        >
          ← Back to Menu
        </button>
        <Heading size="xl" className="mb-1">
          Edit Lunch Menu
        </Heading>
        <p className="text-sm text-gray-500">Update menu details, allergens, and nutritional information</p>
      </div>

      {loading && !menu ? (
        <div className="flex justify-center py-12">
          <LoadingSpinner />
        </div>
      ) : error && !menu ? (
        <div className="mb-6">
          <ErrorAlert message={error} />
        </div>
      ) : (
        <IOSCard className="max-w-2xl p-6 mx-auto">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label htmlFor="date" className="block text-sm font-semibold text-gray-700 mb-2">
                Date <span className="text-red-500">*</span>
              </label>
              <input
                id="date"
                value={form.date}
                onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))}
                type="date"
                required
                className="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
              />
            </div>

            <div>
              <label htmlFor="meal_name" className="block text-sm font-semibold text-gray-700 mb-2">
                Meal Name <span className="text-red-500">*</span>
              </label>
              <input
                id="meal_name"
                value={form.meal_name}
                onChange={(e) => setForm((p) => ({ ...p, meal_name: e.target.value }))}
                type="text"
                required
                placeholder="e.g. Vegetable Pasta"
                className="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
              />
            </div>

            <div>
              <label htmlFor="description" className="block text-sm font-semibold text-gray-700 mb-2">
                Description
              </label>
              <textarea
                id="description"
                value={form.description}
                onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))}
                rows={4}
                className="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all resize-none"
                placeholder="Meal description..."
              />
            </div>

            <div>
              <label htmlFor="allergens" className="block text-sm font-semibold text-gray-700 mb-2">
                Allergens (comma-separated)
              </label>
              <input
                id="allergens"
                value={allergensInput}
                onChange={(e) => setAllergensInput(e.target.value)}
                type="text"
                className="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
                placeholder="e.g. Nuts, Dairy, Gluten"
              />
              <p className="text-xs text-gray-500 mt-2">
                Enter allergens separated by commas. Common allergens: Gluten, Dairy, Nuts, Eggs, Fish, Soy
              </p>
              {allergensInput.trim().length > 0 && (
                <div className="mt-3 flex flex-wrap gap-2">
                  {allergensInput
                    .split(',')
                    .map((a) => a.trim())
                    .filter((a) => a.length > 0)
                    .slice(0, 20)
                    .map((a) => (
                      <span key={a} className="px-3 py-1 text-xs font-semibold rounded-full bg-yellow-100 text-yellow-800">
                        {a}
                      </span>
                    ))}
                </div>
              )}
            </div>

            <div className="p-5 bg-linear-to-br from-green-50 to-blue-50 rounded-xl border-2 border-green-100">
              <Heading size="md" className="mb-4">
                Nutritional Information (Optional)
              </Heading>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="calories" className="block text-xs font-semibold text-gray-700 mb-1">
                    Calories
                  </label>
                  <input
                    id="calories"
                    value={nutritionalInfo.calories}
                    onChange={(e) => setNutritionalInfo((p) => ({ ...p, calories: e.target.value }))}
                    type="number"
                    min={0}
                    className="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                    placeholder="e.g. 450"
                  />
                </div>
                <div>
                  <label htmlFor="protein" className="block text-xs font-semibold text-gray-700 mb-1">
                    Protein
                  </label>
                  <input
                    id="protein"
                    value={nutritionalInfo.protein}
                    onChange={(e) => setNutritionalInfo((p) => ({ ...p, protein: e.target.value }))}
                    type="text"
                    className="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                    placeholder="e.g. 20g"
                  />
                </div>
                <div>
                  <label htmlFor="carbs" className="block text-xs font-semibold text-gray-700 mb-1">
                    Carbohydrates
                  </label>
                  <input
                    id="carbs"
                    value={nutritionalInfo.carbs}
                    onChange={(e) => setNutritionalInfo((p) => ({ ...p, carbs: e.target.value }))}
                    type="text"
                    className="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                    placeholder="e.g. 50g"
                  />
                </div>
                <div>
                  <label htmlFor="fat" className="block text-xs font-semibold text-gray-700 mb-1">
                    Fat
                  </label>
                  <input
                    id="fat"
                    value={nutritionalInfo.fat}
                    onChange={(e) => setNutritionalInfo((p) => ({ ...p, fat: e.target.value }))}
                    type="text"
                    className="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                    placeholder="e.g. 15g"
                  />
                </div>
              </div>
            </div>

            <div>
              <label htmlFor="photo_url" className="block text-sm font-semibold text-gray-700 mb-2">
                Photo URL (Optional)
              </label>
              <input
                id="photo_url"
                value={form.photo_url}
                onChange={(e) => setForm((p) => ({ ...p, photo_url: e.target.value }))}
                type="url"
                className="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
                placeholder="https://example.com/photo.jpg"
              />
              <p className="text-xs text-gray-500 mt-2">Enter a URL to an image of the meal</p>
              {form.photo_url && (
                <div className="mt-3">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={form.photo_url}
                    alt={form.meal_name}
                    className="w-full max-w-md h-48 object-cover rounded-lg border-2 border-gray-200"
                  />
                </div>
              )}
            </div>

            {error && (
              <div className="p-4 bg-red-50 border-2 border-red-200 text-red-800 rounded-xl text-sm">
                ⚠️ {error}
              </div>
            )}

            <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
              <button
                type="button"
                onClick={() => router.push(`/admin/lunch/menus/${menuId}`)}
                className="px-6 py-2.5 text-sm font-semibold text-gray-700 bg-white border-2 border-gray-300 rounded-xl hover:bg-gray-50 transition-all"
                disabled={submitting}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() => void handleDelete()}
                disabled={submitting}
                className="px-6 py-2.5 text-sm font-semibold text-white bg-red-600 rounded-xl hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                🗑️ Delete
              </button>
              <IOSButton type="submit" disabled={submitting} className="px-6 py-2.5">
                {submitting ? '⏳ Saving...' : '✅ Save Changes'}
              </IOSButton>
            </div>
          </form>
        </IOSCard>
      )}
    </div>
  )
}

// pages/admin/lunch/menus/[id]/edit.vue
<template>
  <div>
    <div class="mb-6">
      <NuxtLink
        :to="`/admin/lunch/menus/${menuId}`"
        class="text-blue-600 hover:text-blue-700 mb-4 inline-block"
      >
        ← Back to Menu
      </NuxtLink>
      <Heading size="xl" class="mb-1">Edit Lunch Menu</Heading>
      <p class="text-sm text-gray-500">Update menu details, allergens, and nutritional information</p>
    </div>

    <div v-if="loading && !menu" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error && !menu" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <IOSCard v-else customClass="max-w-2xl p-6">
      <form @submit.prevent="handleSubmit" class="space-y-6">
        <!-- Date -->
        <div>
          <label for="date" class="block text-sm font-semibold text-gray-700 mb-2">
            Date <span class="text-red-500">*</span>
          </label>
          <input
            id="date"
            v-model="form.date"
            type="date"
            required
            class="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
          />
        </div>

        <!-- Meal Name -->
        <div>
          <label for="meal_name" class="block text-sm font-semibold text-gray-700 mb-2">
            Meal Name <span class="text-red-500">*</span>
          </label>
          <input
            id="meal_name"
            v-model="form.meal_name"
            type="text"
            required
            class="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
            placeholder="e.g. Vegetable Pasta"
          />
        </div>

        <!-- Description -->
        <div>
          <label for="description" class="block text-sm font-semibold text-gray-700 mb-2">
            Description
          </label>
          <textarea
            id="description"
            v-model="form.description"
            rows="4"
            class="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all resize-none"
            placeholder="Meal description..."
          />
        </div>

        <!-- Allergens -->
        <div>
          <label for="allergens" class="block text-sm font-semibold text-gray-700 mb-2">
            Allergens (comma-separated)
          </label>
          <input
            id="allergens"
            v-model="allergensInput"
            type="text"
            class="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
            placeholder="e.g. Nuts, Dairy, Gluten"
          />
          <p class="text-xs text-gray-500 mt-2">
            Enter allergens separated by commas. Common allergens: Gluten, Dairy, Nuts, Eggs, Fish, Soy
          </p>
          <div v-if="form.allergens.length > 0" class="mt-3 flex flex-wrap gap-2">
            <span
              v-for="allergen in form.allergens"
              :key="allergen"
              class="px-3 py-1 text-xs font-semibold rounded-full bg-yellow-100 text-yellow-800"
            >
              {{ allergen }}
              <button
                type="button"
                @click="removeAllergen(allergen)"
                class="ml-1 text-yellow-600 hover:text-yellow-800"
              >
                ×
              </button>
            </span>
          </div>
        </div>

        <!-- Nutritional Information -->
        <div class="p-5 bg-gradient-to-br from-green-50 to-blue-50 rounded-xl border-2 border-green-100">
          <Heading size="md" class="mb-4">Nutritional Information (Optional)</Heading>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label for="calories" class="block text-xs font-semibold text-gray-700 mb-1">
                Calories
              </label>
              <input
                id="calories"
                v-model.number="nutritionalInfo.calories"
                type="number"
                min="0"
                class="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                placeholder="e.g. 450"
              />
            </div>
            <div>
              <label for="protein" class="block text-xs font-semibold text-gray-700 mb-1">
                Protein
              </label>
              <input
                id="protein"
                v-model="nutritionalInfo.protein"
                type="text"
                class="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                placeholder="e.g. 20g"
              />
            </div>
            <div>
              <label for="carbs" class="block text-xs font-semibold text-gray-700 mb-1">
                Carbohydrates
              </label>
              <input
                id="carbs"
                v-model="nutritionalInfo.carbs"
                type="text"
                class="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                placeholder="e.g. 50g"
              />
            </div>
            <div>
              <label for="fat" class="block text-xs font-semibold text-gray-700 mb-1">
                Fat
              </label>
              <input
                id="fat"
                v-model="nutritionalInfo.fat"
                type="text"
                class="w-full px-3 py-2 bg-white border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500"
                placeholder="e.g. 15g"
              />
            </div>
          </div>
        </div>

        <!-- Photo URL -->
        <div>
          <label for="photo_url" class="block text-sm font-semibold text-gray-700 mb-2">
            Photo URL (Optional)
          </label>
          <input
            id="photo_url"
            v-model="form.photo_url"
            type="url"
            class="w-full px-4 py-3 bg-white border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
            placeholder="https://example.com/photo.jpg"
          />
          <p class="text-xs text-gray-500 mt-2">
            Enter a URL to an image of the meal
          </p>
          <div v-if="form.photo_url" class="mt-3">
            <img
              :src="form.photo_url"
              :alt="form.meal_name"
              class="w-full max-w-md h-48 object-cover rounded-lg border-2 border-gray-200"
              @error="photoError = true"
            />
          </div>
        </div>

        <!-- Error Message -->
        <div v-if="error" class="p-4 bg-red-50 border-2 border-red-200 text-red-800 rounded-xl text-sm">
          ⚠️ {{ error }}
        </div>

        <!-- Actions -->
        <div class="flex justify-end gap-3 pt-4 border-t border-gray-200">
          <NuxtLink
            :to="`/admin/lunch/menus/${menuId}`"
            class="px-6 py-2.5 text-sm font-semibold text-gray-700 bg-white border-2 border-gray-300 rounded-xl hover:bg-gray-50 transition-all"
          >
            Cancel
          </NuxtLink>
          <button
            type="button"
            @click="handleDelete"
            :disabled="submitting"
            class="px-6 py-2.5 text-sm font-semibold text-white bg-red-600 rounded-xl hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          >
            🗑️ Delete
          </button>
          <button
            type="submit"
            :disabled="submitting"
            class="px-6 py-2.5 text-sm font-semibold text-white bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-xl transition-all"
          >
            {{ submitting ? '⏳ Saving...' : '✅ Save Changes' }}
          </button>
        </div>
      </form>
    </IOSCard>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useSupabaseClient } from '#imports'
import { useLunchStore } from '~/stores/lunch'
import Heading from '~/components/ui/Heading.vue'
import IOSCard from '~/components/ui/IOSCard.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'
import type { LunchMenu } from '~/stores/lunch'

definePageMeta({
  middleware: ['auth', 'role'],
  role: ['admin', 'kitchen']
})

const route = useRoute()
const router = useRouter()
const supabase = useSupabaseClient()
const lunchStore = useLunchStore()

const menuId = route.params.id as string
const loading = ref(true)
const submitting = ref(false)
const error = ref('')
const photoError = ref(false)
const menu = ref<LunchMenu | null>(null)
const allergensInput = ref('')

const form = ref({
  date: '',
  meal_name: '',
  description: '',
  allergens: [] as string[],
  nutritional_info: {} as Record<string, any>,
  photo_url: ''
})

const nutritionalInfo = ref({
  calories: '',
  protein: '',
  carbs: '',
  fat: ''
})

// Watch allergensInput and update form.allergens
watch(allergensInput, (newValue) => {
  form.value.allergens = newValue
    .split(',')
    .map(a => a.trim())
    .filter(a => a.length > 0)
})

// Watch nutritionalInfo and update form.nutritional_info
watch(nutritionalInfo, (newValue) => {
  const info: Record<string, any> = {}
  if (newValue.calories) info.calories = newValue.calories
  if (newValue.protein) info.protein = newValue.protein
  if (newValue.carbs) info.carbs = newValue.carbs
  if (newValue.fat) info.fat = newValue.fat
  form.value.nutritional_info = info
}, { deep: true })

onMounted(async () => {
  try {
    const { data: menuData, error: menuError } = await supabase
      .from('lunch_menus')
      .select('*')
      .eq('id', menuId)
      .single()

    if (menuError) throw menuError
    if (!menuData) {
      error.value = 'Menu not found'
      return
    }

    menu.value = menuData

    // Populate form
    form.value = {
      date: menuData.date,
      meal_name: menuData.meal_name,
      description: menuData.description || '',
      allergens: menuData.allergens || [],
      nutritional_info: menuData.nutritional_info || {},
      photo_url: menuData.photo_url || ''
    }

    // Populate allergens input
    allergensInput.value = (menuData.allergens || []).join(', ')

    // Populate nutritional info
    if (menuData.nutritional_info) {
      nutritionalInfo.value = {
        calories: menuData.nutritional_info.calories || '',
        protein: menuData.nutritional_info.protein || '',
        carbs: menuData.nutritional_info.carbs || '',
        fat: menuData.nutritional_info.fat || ''
      }
    }
  } catch (e: any) {
    console.error('Error loading menu:', e)
    error.value = e.message || 'Failed to load menu'
  } finally {
    loading.value = false
  }
})

const removeAllergen = (allergen: string) => {
  form.value.allergens = form.value.allergens.filter(a => a !== allergen)
  allergensInput.value = form.value.allergens.join(', ')
}

const handleSubmit = async () => {
  submitting.value = true
  error.value = ''

  try {
    // Update allergens from input
    form.value.allergens = allergensInput.value
      .split(',')
      .map(a => a.trim())
      .filter(a => a.length > 0)

    // Update nutritional info
    const info: Record<string, any> = {}
    if (nutritionalInfo.value.calories) info.calories = nutritionalInfo.value.calories
    if (nutritionalInfo.value.protein) info.protein = nutritionalInfo.value.protein
    if (nutritionalInfo.value.carbs) info.carbs = nutritionalInfo.value.carbs
    if (nutritionalInfo.value.fat) info.fat = nutritionalInfo.value.fat
    form.value.nutritional_info = Object.keys(info).length > 0 ? info : {}

    await lunchStore.updateMenu(menuId, form.value)
    await router.push(`/admin/lunch/menus/${menuId}`)
  } catch (e: any) {
    console.error('Error updating menu:', e)
    error.value = e.message || 'Failed to update menu'
  } finally {
    submitting.value = false
  }
}

const handleDelete = async () => {
  if (!confirm('Are you sure you want to delete this menu? This action cannot be undone.')) {
    return
  }

  submitting.value = true
  error.value = ''

  try {
    await lunchStore.deleteMenu(menuId)
    await router.push('/admin/lunch/menus')
  } catch (e: any) {
    console.error('Error deleting menu:', e)
    error.value = e.message || 'Failed to delete menu'
    submitting.value = false
  }
}
</script>
