// src/app/parent/portfolios/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'parent.portfolios'

import React, { useEffect, useState } from 'react'
import { usePortfoliosStore, Portfolio } from '@/stores/portfolios'
import { useChildrenStore } from '@/stores/children'
import { useAuth } from '@/hooks/useAuth'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

export default function ParentPortfoliosPage() {
  const { t } = useI18n()

  const { profile } = useAuth()
  const { portfolios, loading, error, fetchPortfolios } = usePortfoliosStore()
  const { children, fetchChildren } = useChildrenStore()
  
  const [selectedChildId, setSelectedChildId] = useState('')

  useEffect(() => {
    async function loadData() {
        await fetchChildren()
    }
    loadData()
  }, [fetchChildren])

  useEffect(() => {
    if (selectedChildId) {
        fetchPortfolios(selectedChildId)
    } else if (children.length > 0) {
        setSelectedChildId(children[0].id)
    }
  }, [selectedChildId, children, fetchPortfolios])

  if (loading && portfolios.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-4xl mx-auto pb-12">
      <div className="mb-10 text-center">
        <Heading size="xl" className="text-gray-900 tracking-tight">{t(pT(ROUTE))}</Heading>
        <p className="text-sm text-gray-500 mt-1">Die schönsten Momente und Lernfortschritte Ihres Kindes.</p>
      </div>

      {children.length > 1 && (
        <div className="mb-10 flex justify-center gap-2 overflow-x-auto pb-2">
            {children.map(c => (
                <button
                    key={c.id}
                    onClick={() => setSelectedChildId(c.id)}
                    className={`px-6 py-2 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all duration-300 ${
                        selectedChildId === c.id 
                        ? 'bg-black text-white border-black shadow-lg' 
                        : 'bg-white text-gray-400 border-black/5'
                    }`}
                >
                    {c.first_name}
                </button>
            ))}
        </div>
      )}

      {portfolios.length === 0 ? (
        <IOSCard className="p-20 text-center bg-gray-50/30 border-black/5">
          <div className="text-6xl opacity-10 mb-6">📸</div>
          <p className="text-gray-400 font-bold max-w-xs mx-auto">Noch keine Portfolio-Einträge vorhanden.</p>
        </IOSCard>
      ) : (
        <div className="space-y-12">
            {portfolios.map((entry: Portfolio) => (
                <div key={entry.id} className="relative group">
                    <div className="absolute left-1/2 -ml-px top-full h-12 border-l border-black/5 group-last:hidden"></div>
                    
                    <IOSCard className="p-0 overflow-hidden border-black/5 shadow-xl shadow-black/5">
                        <div className="p-8 border-b border-black/5 flex items-center justify-between">
                            <div>
                                <h3 className="text-lg font-black text-gray-900 mb-0.5">{entry.title}</h3>
                                <p className="text-[10px] font-black text-black/20 uppercase tracking-widest">{new Date(entry.date).toLocaleDateString()}</p>
                            </div>
                            <span className="text-2xl">✨</span>
                        </div>
                        
                        {entry.attachments?.[0] && (
                            <div className="aspect-video bg-gray-100 overflow-hidden">
                                <img src={entry.attachments[0]} alt={entry.title} className="w-full h-full object-cover" />
                            </div>
                        )}
                        
                        <div className="p-8">
                            <p className="text-base text-gray-600 font-medium leading-relaxed whitespace-pre-wrap">{entry.content}</p>
                        </div>
                    </IOSCard>
                </div>
            ))}
        </div>
      )}
    </div>
  )
}

// pages/parent/portfolios/index.vue
<template>
  <div>
    <div class="mb-6">
      <Heading size="xl">Portfolios</Heading>
      <p class="text-sm text-gray-600 mt-1">Sammlung von Arbeiten und Erinnerungen Ihrer Kinder</p>
    </div>

    <div class="mb-4">
      <select
        v-model="selectedChildId"
        class="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        @change="fetchPortfolios"
      >
        <option value="">Alle meine Kinder</option>
        <option v-for="child in myChildren" :key="child.id" :value="child.id">
          {{ child.first_name }} {{ child.last_name }}
        </option>
      </select>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error.message || 'Fehler beim Laden der Portfolios'" />
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div v-if="portfolios.length === 0" class="col-span-full bg-white rounded-lg shadow p-8 text-center text-gray-500">
        Keine Portfolio-Elemente gefunden.
      </div>

      <div
        v-for="portfolio in portfolios"
        :key="portfolio.id"
        class="bg-white rounded-lg shadow overflow-hidden hover:shadow-lg transition-shadow"
      >
        <div v-if="portfolio.attachments && portfolio.attachments.length > 0" class="aspect-video bg-gray-100">
          <img
            :src="portfolio.attachments[0]"
            :alt="portfolio.title"
            class="w-full h-full object-cover"
          />
        </div>
        <div class="p-5">
          <div class="mb-2">
            <span class="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded">
              {{ getPortfolioTypeLabel(portfolio.portfolio_type) }}
            </span>
          </div>
          <h3 class="text-lg font-semibold text-gray-900 mb-2">{{ portfolio.title }}</h3>
          <p class="text-sm text-gray-600 mb-2">{{ getChildName(portfolio.child_id) }}</p>
          <p class="text-sm text-gray-500 mb-3">{{ formatDate(portfolio.date) }}</p>
          <p v-if="portfolio.description" class="text-sm text-gray-700 mb-4 line-clamp-2">
            {{ portfolio.description }}
          </p>
          <div v-if="portfolio.attachments && portfolio.attachments.length > 0" class="mb-4">
            <span class="text-xs text-gray-500">📎 {{ portfolio.attachments.length }} Anhänge</span>
          </div>
          <NuxtLink
            :to="`/parent/portfolios/${portfolio.id}`"
            class="inline-flex items-center gap-1 px-3 py-1.5 bg-blue-50 text-blue-700 rounded-md hover:bg-blue-100 transition-colors text-sm"
          >
            <span>👁️</span>
            <span>Vollständig ansehen</span>
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { usePortfoliosStore } from '~/stores/portfolios'
import { useChildrenStore } from '~/stores/children'
import { useAuthStore } from '~/stores/auth'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'parent'
})

const portfoliosStore = usePortfoliosStore()
const childrenStore = useChildrenStore()
const authStore = useAuthStore()

const selectedChildId = ref('')
const { portfolios, loading, error } = storeToRefs(portfoliosStore)
const { children } = storeToRefs(childrenStore)

const myChildren = computed(() => {
  const userId = authStore.user?.id
  if (!userId) return []
  
  return children.value.filter(child => child.parent_ids?.includes(userId))
})

const filteredPortfolios = computed(() => {
  const myChildIds = myChildren.value.map(c => c.id)
  let filtered = portfolios.value.filter(portfolio => myChildIds.includes(portfolio.child_id))
  
  if (selectedChildId.value) {
    filtered = filtered.filter(portfolio => portfolio.child_id === selectedChildId.value)
  }
  
  return filtered.sort((a, b) => 
    new Date(b.date).getTime() - new Date(a.date).getTime()
  )
})

onMounted(async () => {
  await Promise.all([
    portfoliosStore.fetchPortfolios(),
    childrenStore.fetchChildren()
  ])
})

const fetchPortfolios = async () => {
  await portfoliosStore.fetchPortfolios(selectedChildId.value || undefined)
}

const getChildName = (childId: string) => {
  const child = children.value.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}

const getPortfolioTypeLabel = (type: string) => {
  const labels: Record<string, string> = {
    artwork: 'Kunstwerk',
    photo: 'Foto',
    achievement: 'Leistung',
    activity: 'Aktivität',
    milestone: 'Meilenstein',
    other: 'Sonstiges'
  }
  return labels[type] || type
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString('de-DE')
}
</script>
