// pages/admin/observations/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <div>
        <Heading size="xl">Beobachtungen</Heading>
        <p class="text-sm text-gray-600 mt-1">Dokumentieren Sie die Entwicklung der Kinder</p>
      </div>
      <NuxtLink
        to="/admin/observations/new"
        class="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors shadow-sm"
      >
        <span>➕</span>
        <span>Neue Beobachtung</span>
      </NuxtLink>
    </div>

    <div class="mb-4 flex gap-4">
      <select
        v-model="selectedChildId"
        class="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        @change="fetchObservations"
      >
        <option value="">Alle Kinder</option>
        <option v-for="child in children" :key="child.id" :value="child.id">
          {{ child.first_name }} {{ child.last_name }}
        </option>
      </select>
      <input
        v-model="selectedDate"
        type="date"
        class="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        @change="fetchObservations"
      />
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error.message || 'Error loading observations'" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="observations.length === 0" class="p-8 text-center text-gray-500">
        No observations found.
      </div>

      <div v-else class="divide-y divide-gray-200">
        <div
          v-for="observation in observations"
          :key="observation.id"
          class="p-6 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-3 mb-2">
                <h3 class="text-lg font-medium text-gray-900">{{ getChildName(observation.child_id) }}</h3>
                <span v-if="observation.development_area" class="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded">
                  {{ observation.development_area }}
                </span>
              </div>
              <p class="text-sm text-gray-600 mb-2">{{ formatDate(observation.observation_date) }}</p>
              <p v-if="observation.context" class="text-sm text-gray-500 mb-2 italic">{{ observation.context }}</p>
              <p class="text-gray-700 mb-3">{{ observation.description }}</p>
              <div v-if="observation.photos && observation.photos.length > 0" class="mt-2">
                <span class="text-xs text-gray-500">📷 {{ observation.photos.length }} photos</span>
              </div>
            </div>
            <div class="flex items-center gap-2">
              <NuxtLink
                :to="`/admin/observations/${observation.id}`"
                class="inline-flex items-center gap-1 px-3 py-1.5 bg-blue-50 text-blue-700 rounded-md hover:bg-blue-100 transition-colors"
              >
                <span>👁️</span>
                <span>Ansehen</span>
              </NuxtLink>
              <NuxtLink
                :to="`/admin/observations/${observation.id}?edit=true`"
                class="inline-flex items-center gap-1 px-3 py-1.5 bg-yellow-50 text-yellow-700 rounded-md hover:bg-yellow-100 transition-colors"
              >
                <span>✏️</span>
                <span>Bearbeiten</span>
              </NuxtLink>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useObservationsStore } from '~/stores/observations'
import { useChildrenStore } from '~/stores/children'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const observationsStore = useObservationsStore()
const childrenStore = useChildrenStore()

const selectedChildId = ref('')
const selectedDate = ref('')
const { observations, loading, error } = storeToRefs(observationsStore)
const { children } = storeToRefs(childrenStore)

onMounted(async () => {
  await Promise.all([
    observationsStore.fetchObservations(),
    childrenStore.fetchChildren()
  ])
})

const fetchObservations = async () => {
  await observationsStore.fetchObservations(
    selectedChildId.value || undefined,
    selectedDate.value || undefined
  )
}

const getChildName = (childId: string) => {
  const child = children.value.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}
</script>

// next-app/src/app/parent/observations/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'parent.observations'

import React, { useEffect, useState } from 'react'
import { useObservationsStore, Observation } from '@/stores/observations'
import { useChildrenStore } from '@/stores/children'
import { useAuth } from '@/hooks/useAuth'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

export default function ParentObservationsPage() {
  const { t } = useI18n()

  const { profile } = useAuth()
  const { observations, loading, fetchObservations } = useObservationsStore()
  const { children, fetchChildren } = useChildrenStore()
  
  const [selectedChildId, setSelectedChildId] = useState('')

  useEffect(() => {
    fetchChildren()
  }, [fetchChildren])

  useEffect(() => {
    if (selectedChildId) {
        fetchObservations(selectedChildId)
    } else if (children.length > 0) {
        setSelectedChildId(children[0].id)
    }
  }, [selectedChildId, children, fetchObservations])

  if (loading && observations.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-4xl mx-auto pb-12">
      <div className="mb-10 text-center">
        <Heading size="xl" className="text-gray-900 tracking-tight">{t(pT(ROUTE))}</Heading>
        <p className="text-sm text-gray-500 mt-1">Dokumentation der pädagogischen Entwicklung Ihres Kindes.</p>
      </div>

      {children.length > 1 && (
        <div className="mb-10 flex justify-center gap-2">
             {children.map(c => (
                <button
                    key={c.id}
                    onClick={() => setSelectedChildId(c.id)}
                    className={`px-6 py-2 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all duration-300 ${
                        selectedChildId === c.id ? 'bg-black text-white' : 'bg-white text-gray-400 border-black/5'
                    }`}
                >
                    {c.first_name}
                </button>
            ))}
        </div>
      )}

      {observations.length === 0 ? (
        <IOSCard className="p-20 text-center bg-gray-50/30 border-black/5">
          <div className="text-6xl opacity-10 mb-6">🔍</div>
          <p className="text-gray-400 font-bold max-w-xs mx-auto">Noch keine Beobachtungen eingetragen.</p>
        </IOSCard>
      ) : (
        <div className="space-y-6">
            {observations.map(obs => (
                <IOSCard key={obs.id} className="p-8 border-black/5 hover:border-indigo-500/30 transition-all">
                    <div className="flex justify-between items-start mb-6">
                        <div>
                             <h3 className="text-lg font-black text-gray-900">{obs.title || 'Entwicklungsbeobachtung'}</h3>
                             <p className="text-[10px] font-black text-black/20 uppercase tracking-widest">{new Date(obs.observation_date).toLocaleDateString()}</p>
                        </div>
                        <span className="text-xs font-black text-gray-400 uppercase tracking-widest bg-gray-100 px-3 py-1 rounded-full">{obs.observation_type}</span>
                    </div>
                    <p className="text-base text-gray-600 font-medium leading-relaxed mb-6">{obs.content}</p>
                    {obs.areas_of_development && obs.areas_of_development.length > 0 && (
                        <div className="flex flex-wrap gap-2">
                             {obs.areas_of_development.map(area => (
                                 <span key={area} className="px-2 py-0.5 bg-indigo-50 text-indigo-600 text-[9px] font-black uppercase tracking-widest rounded-md border border-indigo-100/50">{area}</span>
                             ))}
                        </div>
                    )}
                </IOSCard>
            ))}
        </div>
      )}
    </div>
  )
}
