// pages/admin/lunch/billing/reconciliation.vue
<template>
  <div>
    <div class="mb-6">
      <NuxtLink
        to="/admin/lunch/billing"
        class="text-gray-600 hover:text-gray-900 mb-4 inline-block"
      >
        ← Back to Billing
      </NuxtLink>
      <Heading size="xl">Billing Reconciliation</Heading>
    </div>

    <div class="bg-white rounded-lg shadow p-6 mb-6">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Month</label>
          <select
            v-model.number="filters.month"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          >
            <option v-for="m in 12" :key="m" :value="m">
              {{ getMonthName(m) }}
            </option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Year</label>
          <input
            v-model.number="filters.year"
            type="number"
            :min="new Date().getFullYear() - 1"
            :max="new Date().getFullYear() + 1"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <div class="flex items-end">
          <button
            @click="loadReconciliation"
            :disabled="loading"
            class="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50"
          >
            {{ loading ? 'Loading...' : 'Load Reconciliation' }}
          </button>
        </div>
      </div>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else-if="reconciliation" class="space-y-6">
      <!-- Summary -->
      <div class="bg-white rounded-lg shadow p-6">
        <Heading size="md" class="mb-4">Summary</Heading>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <p class="text-sm text-gray-600">Total Bills</p>
            <p class="text-2xl font-semibold">{{ reconciliation.summary.totalBills }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-600">Expected Total</p>
            <p class="text-2xl font-semibold text-green-600">€{{ reconciliation.summary.expectedTotal.toFixed(2) }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-600">Actual Total</p>
            <p class="text-2xl font-semibold text-blue-600">€{{ reconciliation.summary.actualTotal.toFixed(2) }}</p>
          </div>
          <div>
            <p class="text-sm text-gray-600">Difference</p>
            <p
              :class="[
                'text-2xl font-semibold',
                Math.abs(reconciliation.summary.difference) < 0.01
                  ? 'text-gray-600'
                  : reconciliation.summary.difference > 0
                    ? 'text-red-600'
                    : 'text-green-600'
              ]"
            >
              €{{ reconciliation.summary.difference.toFixed(2) }}
            </p>
          </div>
        </div>
      </div>

      <!-- Discrepancies -->
      <div v-if="reconciliation.discrepancies.length > 0" class="bg-white rounded-lg shadow p-6">
        <Heading size="md" class="mb-4 text-red-600">⚠️ Discrepancies ({{ reconciliation.discrepancies.length }})</Heading>
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Child</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Expected</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actual</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Difference</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Issue</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr
                v-for="disc in reconciliation.discrepancies"
                :key="disc.billId"
                class="hover:bg-gray-50"
              >
                <td class="px-4 py-3 text-sm text-gray-900">{{ disc.childName }}</td>
                <td class="px-4 py-3 text-sm text-gray-600">€{{ disc.expected.toFixed(2) }}</td>
                <td class="px-4 py-3 text-sm text-gray-600">€{{ disc.actual.toFixed(2) }}</td>
                <td class="px-4 py-3 text-sm font-medium" :class="disc.difference > 0 ? 'text-red-600' : 'text-green-600'">
                  €{{ disc.difference.toFixed(2) }}
                </td>
                <td class="px-4 py-3 text-sm text-gray-600">{{ disc.issue }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Missing Attendance -->
      <div v-if="reconciliation.missingAttendance.length > 0" class="bg-white rounded-lg shadow p-6">
        <Heading size="md" class="mb-4 text-yellow-600">⚠️ Missing Attendance Records ({{ reconciliation.missingAttendance.length }})</Heading>
        <div class="space-y-2">
          <div
            v-for="missing in reconciliation.missingAttendance"
            :key="`${missing.childId}-${missing.date}`"
            class="p-3 bg-yellow-50 border border-yellow-200 rounded-md"
          >
            <p class="text-sm">
              <strong>{{ missing.childName }}</strong> - No attendance record for {{ formatDate(missing.date) }}
            </p>
          </div>
        </div>
      </div>

      <!-- Missing Pricing -->
      <div v-if="reconciliation.missingPricing.length > 0" class="bg-white rounded-lg shadow p-6">
        <Heading size="md" class="mb-4 text-orange-600">⚠️ Missing Pricing ({{ reconciliation.missingPricing.length }})</Heading>
        <div class="space-y-2">
          <div
            v-for="missing in reconciliation.missingPricing"
            :key="missing.groupId"
            class="p-3 bg-orange-50 border border-orange-200 rounded-md"
          >
            <p class="text-sm">
              <strong>{{ missing.groupName }}</strong> - No lunch pricing configured
            </p>
            <NuxtLink
              to="/admin/lunch/pricing"
              class="text-sm text-orange-800 underline hover:text-orange-900 mt-1 inline-block"
            >
              Set up pricing →
            </NuxtLink>
          </div>
        </div>
      </div>

      <!-- All Bills -->
      <div class="bg-white rounded-lg shadow p-6">
        <Heading size="md" class="mb-4">All Bills</Heading>
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Child</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Expected</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actual</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr
                v-for="bill in reconciliation.bills"
                :key="bill.billId"
                class="hover:bg-gray-50"
              >
                <td class="px-4 py-3 text-sm text-gray-900">{{ bill.childName }}</td>
                <td class="px-4 py-3 text-sm text-gray-600">€{{ bill.expected.toFixed(2) }}</td>
                <td class="px-4 py-3 text-sm text-gray-600">€{{ bill.actual.toFixed(2) }}</td>
                <td class="px-4 py-3">
                  <span
                    :class="[
                      'px-2 py-1 text-xs font-medium rounded-full',
                      Math.abs(bill.difference) < 0.01
                        ? 'bg-green-100 text-green-800'
                        : 'bg-yellow-100 text-yellow-800'
                    ]"
                  >
                    {{ Math.abs(bill.difference) < 0.01 ? 'Match' : 'Mismatch' }}
                  </span>
                </td>
                <td class="px-4 py-3">
                  <NuxtLink
                    :to="`/admin/lunch/billing/${bill.billId}`"
                    class="text-blue-600 hover:text-blue-700 text-sm"
                  >
                    View →
                  </NuxtLink>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useChildrenStore } from '~/stores/children'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const childrenStore = useChildrenStore()
const { children } = storeToRefs(childrenStore)

const loading = ref(false)
const error = ref('')
const reconciliation = ref<any>(null)

const filters = ref({
  month: new Date().getMonth() + 1,
  year: new Date().getFullYear()
})

onMounted(async () => {
  await childrenStore.fetchChildren()
})

const getMonthName = (month: number) => {
  const date = new Date(2000, month - 1, 1)
  return date.toLocaleString('default', { month: 'long' })
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}

const loadReconciliation = async () => {
  loading.value = true
  error.value = ''

  try {
    const response = await $fetch('/api/admin/lunch/billing/reconciliation', {
      method: 'GET',
      params: {
        month: filters.value.month,
        year: filters.value.year
      }
    })

    if (response.success && response.reconciliation) {
      reconciliation.value = response.reconciliation
    } else {
      throw new Error(response.message || 'Failed to load reconciliation')
    }
  } catch (e: any) {
    console.error('Error loading reconciliation:', e)
    error.value = e.data?.message || e.message || 'Failed to load reconciliation'
  } finally {
    loading.value = false
  }
}
</script>

// src/app/admin/lunch/billing/reconciliation/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.lunch.billing.reconciliation'

import React, { useState } from 'react'
import Link from 'next/link'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'

type Reconciliation = {
  month: number
  year: number
  summary: {
    totalBills: number
    expectedTotal: number
    actualTotal: number
    difference: number
  }
  discrepancies: Array<any>
  missingAttendance: Array<any>
  missingPricing: Array<any>
  bills: Array<any>
}

export default function AdminLunchBillingReconciliationPage() {
  const { t } = useI18n()

  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [reconciliation, setReconciliation] = useState<Reconciliation | null>(null)

  const [filters, setFilters] = useState({
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
  })

  const getMonthName = (month: number) => {
    const date = new Date(2000, month - 1, 1)
    return date.toLocaleString('default', { month: 'long' })
  }

  const formatDate = (date: string) => new Date(date).toLocaleDateString()

  const loadReconciliation = async () => {
    setLoading(true)
    setError('')

    try {
      const res = await fetch(
        `/api/admin/lunch/billing/reconciliation?month=${encodeURIComponent(String(filters.month))}&year=${encodeURIComponent(
          String(filters.year),
        )}`,
      )
      const data = await res.json()
      if (data?.success && data?.reconciliation) {
        setReconciliation(data.reconciliation as Reconciliation)
      } else {
        throw new Error(data?.message || 'Failed to load reconciliation')
      }
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load reconciliation')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-7xl mx-auto pb-12">
      <div className="mb-6">
        <Link href="/admin/lunch/billing" className="text-gray-600 hover:text-gray-900 mb-4 inline-block">
          ← Back to Billing
        </Link>
        <Heading size="xl">{t(pT(ROUTE))}</Heading>
      </div>

      <IOSCard className="bg-white rounded-lg shadow p-6 mb-6 max-w-3xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Month</label>
            <select
              value={filters.month}
              onChange={(e) => setFilters((p) => ({ ...p, month: Number(e.target.value) }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
            >
              {Array.from({ length: 12 }).map((_, idx) => {
                const m = idx + 1
                return (
                  <option key={m} value={m}>
                    {getMonthName(m)}
                  </option>
                )
              })}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Year</label>
            <input
              value={filters.year}
              onChange={(e) => setFilters((p) => ({ ...p, year: Number(e.target.value) }))}
              type="number"
              min={new Date().getFullYear() - 1}
              max={new Date().getFullYear() + 1}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <div className="flex items-end">
            <IOSButton
              type="button"
              onClick={() => void loadReconciliation()}
              disabled={loading}
              className="w-full bg-blue-600 text-white hover:bg-blue-700 transition-colors disabled:opacity-50"
            >
              {loading ? 'Loading...' : 'Load Reconciliation'}
            </IOSButton>
          </div>
        </div>
      </IOSCard>

      {loading ? (
        <div className="flex justify-center py-12">
          <LoadingSpinner />
        </div>
      ) : error ? (
        <div className="mb-6 max-w-3xl mx-auto">
          <ErrorAlert message={error} />
        </div>
      ) : reconciliation ? (
        <div className="space-y-6 max-w-7xl mx-auto px-2">
          <div className="bg-white rounded-lg shadow p-6 max-w-5xl mx-auto">
            <Heading size="md" className="mb-4">
              Summary
            </Heading>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div>
                <p className="text-sm text-gray-600">Total Bills</p>
                <p className="text-2xl font-semibold">{reconciliation.summary.totalBills}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Expected Total</p>
                <p className="text-2xl font-semibold text-green-600">€{reconciliation.summary.expectedTotal.toFixed(2)}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Actual Total</p>
                <p className="text-2xl font-semibold text-blue-600">€{reconciliation.summary.actualTotal.toFixed(2)}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Difference</p>
                <p
                  className={[
                    'text-2xl font-semibold',
                    Math.abs(reconciliation.summary.difference) < 0.01
                      ? 'text-gray-600'
                      : reconciliation.summary.difference > 0
                        ? 'text-red-600'
                        : 'text-green-600',
                  ].join(' ')}
                >
                  €{reconciliation.summary.difference.toFixed(2)}
                </p>
              </div>
            </div>
          </div>

          {reconciliation.discrepancies.length > 0 && (
            <div className="bg-white rounded-lg shadow p-6 max-w-5xl mx-auto">
              <Heading size="md" className="mb-4 text-red-600">
                ⚠️ Discrepancies ({reconciliation.discrepancies.length})
              </Heading>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Child</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Expected</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actual</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Difference</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Issue</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {reconciliation.discrepancies.map((disc) => (
                      <tr key={disc.billId} className="hover:bg-gray-50">
                        <td className="px-4 py-3 text-sm text-gray-900">{disc.childName}</td>
                        <td className="px-4 py-3 text-sm text-gray-600">€{disc.expected.toFixed(2)}</td>
                        <td className="px-4 py-3 text-sm text-gray-600">€{disc.actual.toFixed(2)}</td>
                        <td
                          className={[
                            'px-4 py-3 text-sm font-medium',
                            disc.difference > 0 ? 'text-red-600' : 'text-green-600',
                          ].join(' ')}
                        >
                          €{disc.difference.toFixed(2)}
                        </td>
                        <td className="px-4 py-3 text-sm text-gray-600">{disc.issue}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {reconciliation.missingAttendance.length > 0 && (
            <div className="bg-white rounded-lg shadow p-6 max-w-5xl mx-auto">
              <Heading size="md" className="mb-4 text-yellow-600">
                ⚠️ Missing Attendance Records ({reconciliation.missingAttendance.length})
              </Heading>
              <div className="space-y-2">
                {reconciliation.missingAttendance.map((missing: any) => (
                  <div key={`${missing.childId}-${missing.date}`} className="p-3 bg-yellow-50 border border-yellow-200 rounded-md">
                    <p className="text-sm">
                      <strong>{missing.childName}</strong> - No attendance record for {formatDate(missing.date)}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {reconciliation.missingPricing.length > 0 && (
            <div className="bg-white rounded-lg shadow p-6 max-w-5xl mx-auto">
              <Heading size="md" className="mb-4 text-orange-600">
                ⚠️ Missing Pricing ({reconciliation.missingPricing.length})
              </Heading>
              <div className="space-y-2">
                {reconciliation.missingPricing.map((missing: any) => (
                  <div key={missing.groupId} className="p-3 bg-orange-50 border border-orange-200 rounded-md">
                    <p className="text-sm">
                      <strong>{missing.groupName}</strong> - No lunch pricing configured
                    </p>
                    <Link href="/admin/lunch/pricing" className="text-sm text-orange-800 underline hover:text-orange-900 mt-1 inline-block">
                      Set up pricing →
                    </Link>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-white rounded-lg shadow p-6 max-w-5xl mx-auto">
            <Heading size="md" className="mb-4">
              All Bills
            </Heading>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Child</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Expected</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actual</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {reconciliation.bills.map((bill: any) => (
                    <tr key={bill.billId} className="hover:bg-gray-50">
                      <td className="px-4 py-3 text-sm text-gray-900">{bill.childName}</td>
                      <td className="px-4 py-3 text-sm text-gray-600">€{bill.expected.toFixed(2)}</td>
                      <td className="px-4 py-3 text-sm text-gray-600">€{bill.actual.toFixed(2)}</td>
                      <td className="px-4 py-3">
                        <span
                          className={[
                            'px-2 py-1 text-xs font-medium rounded-full',
                            Math.abs(bill.difference) < 0.01
                              ? 'bg-green-100 text-green-800'
                              : 'bg-yellow-100 text-yellow-800',
                          ].join(' ')}
                        >
                          {Math.abs(bill.difference) < 0.01 ? 'Match' : 'Mismatch'}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <Link href={`/admin/lunch/billing/${bill.billId}`} className="text-blue-600 hover:text-blue-700 text-sm">
                          View →
                        </Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}
