// pages/teacher/leave/new.vue
<template>
  <div>
    <div class="mb-6">
      <NuxtLink
        to="/teacher/leave"
        class="text-gray-600 hover:text-gray-900 mb-4 inline-block"
      >
        ← Back to Leave Requests
      </NuxtLink>
      <Heading size="xl">Request Leave</Heading>
    </div>

    <div class="bg-white rounded-lg shadow p-6 max-w-2xl">
      <TeacherLeaveRequestForm
        @submit="handleSubmit"
        @cancel="handleCancel"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useTeacherLeaveRequestsStore } from '~/stores/teacherLeaveRequests'
import Heading from '~/components/ui/Heading.vue'
import TeacherLeaveRequestForm from '~/components/forms/TeacherLeaveRequestForm.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'teacher'
})

const router = useRouter()
const teacherLeaveRequestsStore = useTeacherLeaveRequestsStore()

const handleSubmit = async (data: any) => {
  try {
    await teacherLeaveRequestsStore.createLeaveRequest(data)
    alert('Leave request submitted successfully!')
    router.push('/teacher/leave')
  } catch (error: any) {
    alert(error.message || 'Failed to submit leave request')
  }
}

const handleCancel = () => {
  router.push('/teacher/leave')
}
</script>

// next-app/src/app/teacher/leave/new/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'teacher.leave.new'

import React, { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useAuth } from '@/hooks/useAuth'
import { useTeacherLeaveRequestsStore } from '@/stores/teacherLeaveRequests'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { TeacherLeaveRequestForm } from '@/components/forms/TeacherLeaveRequestForm'

export default function NewTeacherLeavePage() {
  const { t } = useI18n()

  const router = useRouter()
  const { user } = useAuth()
  const { createLeaveRequest } = useTeacherLeaveRequestsStore()
  const [submitting, setSubmitting] = useState(false)

  const handleSubmit = async (data: any) => {
    if (!user?.id) return
    setSubmitting(true)
    try {
      await createLeaveRequest({
        ...data,
        teacher_id: user.id
      })
      alert('Urlaubsantrag erfolgreich eingereicht!')
      router.push('/teacher/leave')
    } catch (e: any) {
      alert(e.message || 'Fehler beim Einreichen des Antrags')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="max-w-3xl mx-auto pb-12">
      <div className="mb-8">
        <Link
          href="/teacher/leave"
          className="text-sm font-semibold text-[#667eea] mb-2 inline-flex items-center gap-1 hover:translate-x-[-4px] transition-transform"
        >
          ← Zurück zu meinen Anträgen
        </Link>
        <Heading size="xl" className="text-gray-900 mt-2">{t(pT(ROUTE))}</Heading>
        <p className="text-sm text-gray-500 mt-1">Stellen Sie einen neuen Antrag auf Abwesenheit oder Urlaub.</p>
      </div>

      <IOSCard className="p-8">
        <TeacherLeaveRequestForm
          onSubmit={handleSubmit}
          onCancel={() => router.push('/teacher/leave')}
          loading={submitting}
        />
      </IOSCard>
    </div>
  )
}
