// src/app/admin/observations/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.observations'

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { useObservationsStore } from '@/stores/observations'
import { useChildrenStore } from '@/stores/children'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'

export default function AdminObservationsPage() {
  const { t } = useI18n()

  const { observations, loading, error, fetchObservations } = useObservationsStore()
  const { children, fetchChildren } = useChildrenStore()

  const [selectedChildId, setSelectedChildId] = useState('')
  const [selectedDate, setSelectedDate] = useState('')

  useEffect(() => {
    fetchChildren()
    fetchObservations()
  }, [fetchChildren, fetchObservations])

  const handleFilter = () => fetchObservations(selectedChildId || undefined, selectedDate || undefined)

  const getChildName = (childId: string) => {
    const child = (children || []).find((c: any) => c.id === childId)
    return child ? `${child.first_name} ${child.last_name}` : childId
  }

  const formatDate = (d: string) => new Date(d).toLocaleDateString('de-DE')

  const devAreaColors: Record<string, string> = {
    language: 'bg-blue-100 text-blue-700',
    social: 'bg-green-100 text-green-700',
    cognitive: 'bg-purple-100 text-purple-700',
    physical: 'bg-orange-100 text-orange-700',
    emotional: 'bg-pink-100 text-pink-700'
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <div>
          <Heading size="xl" className="text-gray-900">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-gray-500 mt-1">Dokumentieren Sie die Entwicklung der Kinder</p>
        </div>
        <Link href="/admin/observations/new">
          <IOSButton variant="primary" className="inline-flex items-center gap-2 text-sm px-4 py-2">
            ➕ Neue Beobachtung
          </IOSButton>
        </Link>
      </div>

      {/* Filters */}
      <div className="mb-5 flex flex-wrap gap-3">
        <select
          value={selectedChildId}
          onChange={e => { setSelectedChildId(e.target.value); fetchObservations(e.target.value || undefined, selectedDate || undefined) }}
          className="px-4 py-2.5 bg-white/80 border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
        >
          <option value="">Alle Kinder</option>
          {(children || []).map((c: any) => (
            <option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>
          ))}
        </select>
        <input
          type="date"
          value={selectedDate}
          onChange={e => { setSelectedDate(e.target.value); fetchObservations(selectedChildId || undefined, e.target.value || undefined) }}
          className="px-4 py-2.5 bg-white/80 border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
        />
      </div>

      {loading ? (
        <div className="flex justify-center py-12"><LoadingSpinner /></div>
      ) : error ? (
        <div className="mb-6"><ErrorAlert message={error.message || 'Fehler'} /></div>
      ) : (
        <IOSCard className="overflow-hidden p-0">
          {observations.length === 0 ? (
            <div className="p-8 text-center">
              <div className="text-5xl opacity-40 mb-4">🔍</div>
              <p className="font-semibold text-gray-700">Keine Beobachtungen gefunden</p>
            </div>
          ) : (
            <div className="divide-y divide-black/5">
              {observations.map(obs => (
                <div key={obs.id} className="p-5 hover:bg-white/60 transition-colors">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-3 mb-1.5 flex-wrap">
                        <h3 className="text-base font-bold text-gray-900">{getChildName(obs.child_id)}</h3>
                        {obs.development_area && (
                          <span className={`px-2 py-0.5 text-xs font-semibold rounded-full ${devAreaColors[obs.development_area] || 'bg-blue-100 text-blue-700'}`}>
                            {obs.development_area}
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-gray-500 mb-2 font-medium">📅 {formatDate(obs.observation_date)}</p>
                      {obs.context && <p className="text-sm text-gray-500 mb-1 italic">{obs.context}</p>}
                      <p className="text-sm text-gray-700 line-clamp-2">{obs.description}</p>
                      {obs.photos?.length > 0 && (
                        <p className="text-xs text-gray-400 mt-2">📷 {obs.photos.length} Foto{obs.photos.length > 1 ? 's' : ''}</p>
                      )}
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <Link href={`/admin/observations/${obs.id}`}>
                        <IOSButton variant="secondary" className="text-xs px-3 py-1.5 inline-flex items-center gap-1">
                          👁️ Ansehen
                        </IOSButton>
                      </Link>
                      <Link href={`/admin/observations/${obs.id}?edit=true`}>
                        <IOSButton variant="secondary" className="text-xs px-3 py-1.5 inline-flex items-center gap-1">
                          ✏️ Bearbeiten
                        </IOSButton>
                      </Link>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </IOSCard>
      )}
    </div>
  )
}

// pages/admin/observations/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <div>
        <Heading size="xl">Beobachtungen</Heading>
        <p class="text-sm text-gray-600 mt-1">Dokumentieren Sie die Entwicklung der Kinder</p>
      </div>
      <NuxtLink
        to="/admin/observations/new"
        class="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors shadow-sm"
      >
        <span>➕</span>
        <span>Neue Beobachtung</span>
      </NuxtLink>
    </div>

    <div class="mb-4 flex gap-4">
      <select
        v-model="selectedChildId"
        class="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        @change="fetchObservations"
      >
        <option value="">Alle Kinder</option>
        <option v-for="child in children" :key="child.id" :value="child.id">
          {{ child.first_name }} {{ child.last_name }}
        </option>
      </select>
      <input
        v-model="selectedDate"
        type="date"
        class="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        @change="fetchObservations"
      />
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error.message || 'Error loading observations'" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="observations.length === 0" class="p-8 text-center text-gray-500">
        No observations found.
      </div>

      <div v-else class="divide-y divide-gray-200">
        <div
          v-for="observation in observations"
          :key="observation.id"
          class="p-6 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-3 mb-2">
                <h3 class="text-lg font-medium text-gray-900">{{ getChildName(observation.child_id) }}</h3>
                <span v-if="observation.development_area" class="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded">
                  {{ observation.development_area }}
                </span>
              </div>
              <p class="text-sm text-gray-600 mb-2">{{ formatDate(observation.observation_date) }}</p>
              <p v-if="observation.context" class="text-sm text-gray-500 mb-2 italic">{{ observation.context }}</p>
              <p class="text-gray-700 mb-3">{{ observation.description }}</p>
              <div v-if="observation.photos && observation.photos.length > 0" class="mt-2">
                <span class="text-xs text-gray-500">📷 {{ observation.photos.length }} photos</span>
              </div>
            </div>
            <div class="flex items-center gap-2">
              <NuxtLink
                :to="`/admin/observations/${observation.id}`"
                class="inline-flex items-center gap-1 px-3 py-1.5 bg-blue-50 text-blue-700 rounded-md hover:bg-blue-100 transition-colors"
              >
                <span>👁️</span>
                <span>Ansehen</span>
              </NuxtLink>
              <NuxtLink
                :to="`/admin/observations/${observation.id}?edit=true`"
                class="inline-flex items-center gap-1 px-3 py-1.5 bg-yellow-50 text-yellow-700 rounded-md hover:bg-yellow-100 transition-colors"
              >
                <span>✏️</span>
                <span>Bearbeiten</span>
              </NuxtLink>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useObservationsStore } from '~/stores/observations'
import { useChildrenStore } from '~/stores/children'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const observationsStore = useObservationsStore()
const childrenStore = useChildrenStore()

const selectedChildId = ref('')
const selectedDate = ref('')
const { observations, loading, error } = storeToRefs(observationsStore)
const { children } = storeToRefs(childrenStore)

onMounted(async () => {
  await Promise.all([
    observationsStore.fetchObservations(),
    childrenStore.fetchChildren()
  ])
})

const fetchObservations = async () => {
  await observationsStore.fetchObservations(
    selectedChildId.value || undefined,
    selectedDate.value || undefined
  )
}

const getChildName = (childId: string) => {
  const child = children.value.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}
</script>
