// src/app/teacher/leave/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'teacher.leave'

import React, { useEffect, useState, useMemo } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'
import { useTeacherLeaveRequestsStore } from '@/stores/teacherLeaveRequests'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'

export default function TeacherLeaveIndexPage() {
  const { t } = useI18n()

  const router = useRouter()
  const { user } = useAuth()
  const { leaveRequests, loading, error, fetchLeaveRequests, deleteLeaveRequest } = useTeacherLeaveRequestsStore()
  const [filterStatus, setFilterStatus] = useState<'all' | 'pending' | 'approved' | 'rejected'>('all')

  useEffect(() => {
    if (user?.id) {
      fetchLeaveRequests(user.id)
    }
  }, [user?.id, fetchLeaveRequests])

  const filteredRequests = useMemo(() => {
    if (filterStatus === 'all') return leaveRequests
    return leaveRequests.filter(r => r.status === filterStatus)
  }, [leaveRequests, filterStatus])

  const formatLeaveType = (type: string) => {
    const types: Record<string, string> = {
      vacation: 'Erholungsurlaub',
      sick: 'Krankmeldung',
      personal: 'Persönlich',
      other: 'Sonstiges'
    }
    return types[type] || type
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Möchten Sie diesen Urlaubsantrag wirklich stornieren?')) return
    try {
      await deleteLeaveRequest(id)
      if (user?.id) await fetchLeaveRequests(user.id)
    } catch (e: any) {
      alert(e.message || 'Fehler beim Stornieren')
    }
  }

  if (loading && leaveRequests.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-4xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <Heading size="xl" className="text-gray-900">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-gray-500 mt-1">Verwalten Sie Ihre Abwesenheiten und Urlaubsanträge.</p>
        </div>
        <Link href="/teacher/leave/new">
          <IOSButton variant="primary" className="px-6 py-2.5 text-sm font-bold flex items-center gap-2">
            <span>➕</span>
            <span>Neuer Antrag</span>
          </IOSButton>
        </Link>
      </div>

      <div className="flex gap-2 mb-6 p-1.5 bg-[#f2f2f7] rounded-2xl w-fit">
        {['all', 'pending', 'approved', 'rejected'].map(status => (
          <button
            key={status}
            onClick={() => setFilterStatus(status as any)}
            className={`px-5 py-2 rounded-xl text-sm font-bold transition-all duration-300 capitalize ${
              filterStatus === status ? 'bg-white text-[#667eea] shadow-sm' : 'text-gray-500 hover:text-gray-700'
            }`}
          >
            {status === 'all' ? 'Alle' : status === 'pending' ? 'Ausstehend' : status === 'approved' ? 'Genehmigt' : 'Abgelehnt'}
          </button>
        ))}
      </div>

      {error ? (
        <ErrorAlert message={error.message || 'Fehler beim Laden der Anträge'} />
      ) : filteredRequests.length === 0 ? (
        <IOSCard className="p-16 text-center bg-gray-50/50">
          <div className="text-5xl opacity-40 mb-4">🏖️</div>
          <p className="text-gray-500 font-medium">Keine Urlaubsanträge gefunden.</p>
        </IOSCard>
      ) : (
        <div className="grid gap-4">
          {filteredRequests.map(request => (
            <IOSCard key={request.id} className="p-0 overflow-hidden shadow-sm border-black/5 hover:shadow-md transition-all duration-300">
              <div className="p-6">
                <div className="flex flex-col md:flex-row md:items-start justify-between gap-6">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-3">
                        <span className={`px-2.5 py-1 text-[10px] font-black uppercase tracking-widest rounded-md border ${
                          request.status === 'approved' ? 'bg-green-50 text-green-700 border-green-100' :
                          request.status === 'rejected' ? 'bg-red-50 text-red-700 border-red-100' :
                          'bg-amber-50 text-amber-700 border-amber-100'
                        }`}>
                          {request.status === 'approved' ? 'Genehmigt' : request.status === 'rejected' ? 'Abgelehnt' : 'Wartend'}
                        </span>
                        <span className="px-2.5 py-1 text-[10px] font-black uppercase tracking-widest bg-blue-50 text-blue-700 border border-blue-100 rounded-md">
                          {formatLeaveType(request.leave_type)}
                        </span>
                    </div>
                    
                    <div className="flex items-center gap-2 mb-3">
                        <span className="text-gray-400">📅</span>
                        <span className="text-sm font-black text-gray-900">
                          {new Date(request.start_date).toLocaleDateString('de-DE')} - {new Date(request.end_date).toLocaleDateString('de-DE')}
                        </span>
                    </div>
                    
                    <p className="text-sm font-medium text-gray-600 leading-relaxed">{request.reason}</p>
                    
                    {request.admin_notes && (
                        <div className="mt-4 p-3 bg-gray-50 rounded-xl border border-gray-100">
                            <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Anmerkung der Leitung</p>
                            <p className="text-sm text-gray-700 font-medium">{request.admin_notes}</p>
                        </div>
                    )}
                  </div>
                  
                  {request.status === 'pending' && (
                    <IOSButton
                      variant="secondary"
                      onClick={() => handleDelete(request.id)}
                      className="text-xs py-2 h-auto text-red-500 hover:text-red-600 font-black border-red-50"
                    >
                      Antrag stornieren
                    </IOSButton>
                  )}
                </div>
              </div>
            </IOSCard>
          ))}
        </div>
      )}
    </div>
  )
}

// pages/teacher/leave/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <Heading size="xl">My Leave Requests</Heading>
      <NuxtLink
        to="/teacher/leave/new"
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
      >
        ➕ New Request
      </NuxtLink>
    </div>

    <div class="mb-4 flex gap-4">
      <button
        @click="filterStatus = 'all'"
        :class="[
          'px-4 py-2 rounded-md transition-colors',
          filterStatus === 'all'
            ? 'bg-blue-600 text-white'
            : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
        ]"
      >
        All
      </button>
      <button
        @click="filterStatus = 'pending'"
        :class="[
          'px-4 py-2 rounded-md transition-colors',
          filterStatus === 'pending'
            ? 'bg-blue-600 text-white'
            : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
        ]"
      >
        Pending
      </button>
      <button
        @click="filterStatus = 'approved'"
        :class="[
          'px-4 py-2 rounded-md transition-colors',
          filterStatus === 'approved'
            ? 'bg-blue-600 text-white'
            : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
        ]"
      >
        Approved
      </button>
      <button
        @click="filterStatus = 'rejected'"
        :class="[
          'px-4 py-2 rounded-md transition-colors',
          filterStatus === 'rejected'
            ? 'bg-blue-600 text-white'
            : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
        ]"
      >
        Rejected
      </button>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="filteredRequests.length === 0" class="p-8 text-center text-gray-500">
        No leave requests found.
      </div>

      <div v-else class="divide-y divide-gray-200">
        <div
          v-for="request in filteredRequests"
          :key="request.id"
          class="p-6 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-3 mb-2">
                <span
                  :class="[
                    'px-2 py-1 text-xs font-medium rounded-full',
                    request.status === 'approved' ? 'bg-green-100 text-green-800' :
                    request.status === 'rejected' ? 'bg-red-100 text-red-800' :
                    'bg-yellow-100 text-yellow-800'
                  ]"
                >
                  {{ request.status }}
                </span>
                <span class="px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded-full">
                  {{ formatLeaveType(request.leave_type) }}
                </span>
              </div>
              <p class="text-sm text-gray-600 mb-1">
                {{ formatDate(request.start_date) }} - {{ formatDate(request.end_date) }}
              </p>
              <p class="text-gray-900 mb-2">{{ request.reason }}</p>
              <p v-if="request.admin_notes" class="text-sm text-gray-600 mt-2">
                <strong>Admin Notes:</strong> {{ request.admin_notes }}
              </p>
              <p v-if="request.reviewed_at" class="text-xs text-gray-500 mt-2">
                Reviewed on {{ formatDateTime(request.reviewed_at) }}
              </p>
            </div>
            <button
              v-if="request.status === 'pending'"
              @click="deleteRequest(request.id)"
              class="ml-4 px-3 py-1 text-sm text-red-600 hover:text-red-800 hover:bg-red-50 rounded transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useTeacherLeaveRequestsStore } from '~/stores/teacherLeaveRequests'
import { useAuthStore } from '~/stores/auth'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'teacher'
})

const teacherLeaveRequestsStore = useTeacherLeaveRequestsStore()
const authStore = useAuthStore()
const { leaveRequests, loading, error } = storeToRefs(teacherLeaveRequestsStore)

const filterStatus = ref<'all' | 'pending' | 'approved' | 'rejected'>('all')

const filteredRequests = computed(() => {
  if (filterStatus.value === 'all') {
    return leaveRequests.value
  }
  return leaveRequests.value.filter(r => r.status === filterStatus.value)
})

onMounted(async () => {
  if (authStore.user?.id) {
    await teacherLeaveRequestsStore.fetchLeaveRequests(authStore.user.id)
  }
})

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}

const formatDateTime = (date: string) => {
  return new Date(date).toLocaleString()
}

const formatLeaveType = (type: string) => {
  const types: Record<string, string> = {
    vacation: 'Vacation',
    sick: 'Sick Leave',
    personal: 'Personal',
    other: 'Other'
  }
  return types[type] || type
}

const deleteRequest = async (id: string) => {
  if (!confirm('Are you sure you want to cancel this leave request?')) return

  try {
    await teacherLeaveRequestsStore.deleteLeaveRequest(id)
    if (authStore.user?.id) {
      await teacherLeaveRequestsStore.fetchLeaveRequests(authStore.user.id)
    }
  } catch (error: any) {
    alert(error.message || 'Failed to cancel request')
  }
}
</script>
