// pages/admin/lunch/menus/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <div class="ios-page-header">
        <div class="flex justify-between items-center">
          <div>
            <h1>Mittagessen-Menüs</h1>
          </div>
          <NuxtLink
            to="/admin/lunch/menus/new"
            class="ios-button ios-button-primary inline-flex items-center gap-2"
          >
            ➕ Menü hinzufügen
          </NuxtLink>
        </div>
      </div>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else>
      <IOSCard customClass="overflow-hidden">
        <div v-if="menus.length === 0" class="p-8 text-center text-gray-600">
          <div class="text-6xl mb-4 opacity-50">🍽️</div>
          <p class="text-lg font-semibold text-gray-900 mb-2">Noch keine Menüs erstellt</p>
          <p class="text-sm text-gray-600">Erstellen Sie Ihr erstes Menü, um zu beginnen.</p>
        </div>

        <div v-else class="divide-y divide-gray-200">
          <div
            v-for="menu in menus"
            :key="menu.id"
            class="p-6 hover:bg-gray-50 transition-colors"
          >
            <div class="flex items-center justify-between">
              <div>
                <p class="text-lg font-semibold text-gray-900">{{ menu.meal_name }}</p>
                <p class="text-sm text-gray-700 mt-1">{{ menu.description }}</p>
                <p class="text-xs text-gray-600 mt-2">Datum: {{ formatDate(menu.date) }}</p>
                <div v-if="menu.allergens && menu.allergens.length > 0" class="mt-2">
                  <span class="px-3 py-1 text-xs font-semibold rounded-full bg-yellow-100 text-yellow-800">
                    Allergene: {{ menu.allergens.join(', ') }}
                  </span>
                </div>
              </div>
              <div class="flex gap-3">
                <NuxtLink
                  :to="`/admin/lunch/menus/${menu.id}`"
                  class="text-blue-600 hover:text-blue-700 text-sm font-medium"
                >
                  Ansehen →
                </NuxtLink>
                <NuxtLink
                  :to="`/admin/lunch/menus/${menu.id}/edit`"
                  class="text-indigo-600 hover:text-indigo-700 text-sm font-medium"
                >
                  ✏️ Bearbeiten
                </NuxtLink>
              </div>
            </div>
          </div>
        </div>
      </IOSCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useLunchStore } from '~/stores/lunch'
import { useKita } from '~/composables/useKita'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'
import IOSCard from '~/components/ui/IOSCard.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: ['admin', 'kitchen']
})

const lunchStore = useLunchStore()
const { getUserKitaId } = useKita()
const { menus, loading, error } = storeToRefs(lunchStore)

onMounted(async () => {
  const kitaId = await getUserKitaId()
  await lunchStore.fetchMenus(undefined, undefined, kitaId || undefined)
})

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}
</script>

// src/app/admin/lunch/menus/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.lunch.menus'

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { useLunchStore, LunchMenu } from '@/stores/lunch'
import { useAuth } from '@/hooks/useAuth'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'

export default function AdminLunchMenusPage() {
  const { t } = useI18n()

  const { profile } = useAuth()
  const { menus, loading, error, fetchMenus } = useLunchStore()
  
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0])

  useEffect(() => {
    if (profile?.kita_id) {
        fetchMenus(startDate, undefined, profile.kita_id)
    }
  }, [profile, startDate, fetchMenus])

  if (loading && menus.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-7xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-10">
        <div>
          <Heading size="xl" className="text-slate-900 dark:text-slate-50 tracking-tight">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-ui-soft mt-1">Verwalten Sie die täglichen Menüs für Ihre Kita.</p>
        </div>
        <Link href="/admin/lunch/menus/new">
          <IOSButton className="px-6 py-2.5 text-sm font-black uppercase tracking-widest">
            ➕ Menü hinzufügen
          </IOSButton>
        </Link>
      </div>

      <div className="mb-10 flex gap-4">
            <div className="flex flex-col gap-1">
                <span className="text-[10px] font-black text-black/30 uppercase tracking-widest ml-1">Anzeigen ab</span>
                <input 
                    type="date"
                    value={startDate} 
                    onChange={(e) => setStartDate(e.target.value)}
                    className="px-5 py-2.5 bg-white dark:bg-white/5 border border-black/5 dark:border-white/10 rounded-2xl text-[11px] font-black uppercase tracking-widest shadow-sm focus:ring-2 focus:ring-(--aura-primary)/25 outline-none transition-all text-slate-900 dark:text-slate-50"
                />
            </div>
      </div>

      {error ? (
        <ErrorAlert message={error.message || 'Fehler beim Laden des Speiseplans'} />
      ) : menus.length === 0 ? (
        <IOSCard className="p-20 text-center bg-gray-50/30 border-black/5">
          <div className="text-6xl opacity-10 mb-6">🍽️</div>
          <p className="text-ui-soft font-bold max-w-xs mx-auto">Keine Menüs für diesen Zeitraum vorhanden.</p>
        </IOSCard>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {menus.map(menu => (
                <IOSCard key={menu.id} className="p-0 overflow-hidden border-black/5 group hover:shadow-2xl transition-all duration-500">
                    <div className="relative h-48 bg-gray-100 overflow-hidden">
                        {menu.photo_url ? (
                            <img src={menu.photo_url} alt={menu.meal_name} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700" />
                        ) : (
                            <div className="w-full h-full flex items-center justify-center text-4xl opacity-20 bg-linear-to-br from-gray-50 to-gray-200">🥘</div>
                        )}
                        <div className="absolute top-4 left-4">
                            <span className="px-3 py-1.5 bg-black/60 backdrop-blur-md text-white text-[10px] font-black uppercase tracking-widest rounded-full">
                                {new Date(menu.date).toLocaleDateString('de-DE', { weekday: 'short', day: '2-digit', month: 'short' })}
                            </span>
                        </div>
                    </div>
                    <div className="p-8">
                        <h3 className="text-xl font-black text-slate-900 dark:text-slate-50 mb-3 group-hover:text-aura-primary transition-colors">{menu.meal_name}</h3>
                        <p className="text-sm text-ui-soft line-clamp-2 mb-6 font-medium leading-relaxed">{menu.description || 'Keine Beschreibung vorhanden.'}</p>
                        
                        <div className="flex flex-wrap gap-2 mb-8">
                            {menu.allergens?.map(a => (
                                <span key={a} className="px-2 py-0.5 bg-red-50 text-red-500 border border-red-100/50 text-[9px] font-black uppercase rounded-md">{a}</span>
                            ))}
                        </div>

                        <div className="flex gap-2">
                             <Link href={`/admin/lunch/menus/${menu.id}`} className="flex-1">
                                <IOSButton variant="secondary" className="w-full py-2.5 text-[10px] font-black uppercase tracking-widest border-black/5 bg-gray-50 hover:bg-white">Details</IOSButton>
                             </Link>
                             <Link href={`/admin/lunch/menus/${menu.id}/edit`}>
                                <IOSButton variant="secondary" className="p-2.5 bg-white dark:bg-white/5 border border-black/5 dark:border-white/10 text-aura-primary hover:border-(--aura-primary)/40">✏️</IOSButton>
                             </Link>
                        </div>
                    </div>
                </IOSCard>
            ))}
        </div>
      )}
    </div>
  )
}
