// src/app/teacher/daily-reports/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'teacher.daily-reports'

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { useDailyReportsStore } from '@/stores/dailyReports'
import { useGroupsStore } from '@/stores/groups'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'

export default function TeacherDailyReportsIndexPage() {
  const { t } = useI18n()

  const { dailyReports: reports, loading, error, fetchDailyReports } = useDailyReportsStore()
  const { groups, fetchGroups } = useGroupsStore()

  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0])

  useEffect(() => {
    fetchGroups()
    fetchDailyReports(undefined, selectedDate)
  }, [fetchGroups, fetchDailyReports, selectedDate])

  const getGroupName = (groupId: string) => {
    const group = (groups || []).find((g: any) => g.id === groupId)
    return group ? group.name : groupId
  }

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('de-DE', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  return (
    <div className="max-w-4xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <Heading size="xl" className="text-gray-900">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-gray-500 mt-1">Verwalten Sie die täglichen Berichte für Eltern</p>
        </div>
        <Link href="/teacher/daily-reports/new">
          <IOSButton variant="primary" className="px-5 py-2.5 text-sm font-bold flex items-center gap-2">
            <span>➕</span>
            <span>Neuer Bericht</span>
          </IOSButton>
        </Link>
      </div>

      <div className="mb-6 flex items-center gap-3">
        <input
          type="date"
          value={selectedDate}
          onChange={(e) => setSelectedDate(e.target.value)}
          className="px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all shadow-sm"
        />
      </div>

      {loading ? (
        <div className="flex justify-center py-24"><LoadingSpinner /></div>
      ) : error ? (
        <ErrorAlert message={error.message || 'Fehler beim Laden der Berichte'} />
      ) : reports.length === 0 ? (
        <IOSCard className="p-12 text-center">
          <div className="text-5xl opacity-40 mb-4">📝</div>
          <p className="text-gray-500 font-medium">Keine Tagesberichte für dieses Datum gefunden.</p>
        </IOSCard>
      ) : (
        <div className="grid gap-5">
          {reports.map((report: any) => (
            <IOSCard key={report.id} className="p-0 overflow-hidden hover:shadow-lg transition-shadow duration-300">
              <div className="p-6">
                <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-2 flex-wrap">
                      <h3 className="text-xl font-bold text-gray-900 truncate">{report.title}</h3>
                      <span className="px-2.5 py-0.5 bg-[#667eea]/10 text-[#667eea] text-xs font-bold rounded-full border border-[#667eea]/10">
                        {getGroupName(report.group_id)}
                      </span>
                    </div>
                    <p className="text-xs font-bold text-black/40 uppercase tracking-widest mb-4">
                      {formatDate(report.report_date)}
                    </p>
                    <p className="text-gray-700 line-clamp-2 mb-4 leading-relaxed font-medium">
                      {report.content}
                    </p>
                    {report.activities && report.activities.length > 0 && (
                      <div className="flex flex-wrap gap-2 mb-4">
                        {report.activities.slice(0, 3).map((activity: string, idx: number) => (
                          <span key={idx} className="px-2 py-1 bg-gray-50 text-gray-600 text-[10px] font-bold rounded-lg border border-gray-100">
                            #{activity}
                          </span>
                        ))}
                        {report.activities.length > 3 && (
                          <span className="text-[10px] font-bold text-gray-400">+{report.activities.length - 3}</span>
                        )}
                      </div>
                    )}
                  </div>
                  <div className="flex md:flex-col items-center gap-2 flex-shrink-0">
                    <Link href={`/teacher/daily-reports/${report.id}`} className="w-full">
                      <IOSButton variant="secondary" className="w-full px-4 py-2 text-xs font-bold whitespace-nowrap">
                        👁️ Details
                      </IOSButton>
                    </Link>
                    <Link href={`/teacher/daily-reports/${report.id}?edit=true`} className="w-full">
                      <IOSButton variant="secondary" className="w-full px-4 py-2 text-xs font-bold whitespace-nowrap">
                        ✏️ Bearbeiten
                      </IOSButton>
                    </Link>
                  </div>
                </div>
              </div>
            </IOSCard>
          ))}
        </div>
      )}
    </div>
  )
}

// pages/teacher/daily-reports/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <div>
        <Heading size="xl">Tagesberichte</Heading>
        <p class="text-sm text-gray-600 mt-1">Erstellen Sie tägliche Berichte für Eltern</p>
      </div>
      <NuxtLink
        to="/teacher/daily-reports/new"
        class="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors shadow-sm"
      >
        <span>➕</span>
        <span>Neuer Tagesbericht</span>
      </NuxtLink>
    </div>

    <div class="mb-4">
      <input
        v-model="selectedDate"
        type="date"
        class="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        @change="fetchReports"
      />
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="reports.length === 0" class="p-8 text-center text-gray-500">
        Keine Tagesberichte für dieses Datum gefunden.
      </div>

      <div v-else class="divide-y divide-gray-200">
        <div
          v-for="report in reports"
          :key="report.id"
          class="p-6 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-3 mb-2">
                <h3 class="text-lg font-medium text-gray-900">{{ report.title }}</h3>
                <span class="text-sm text-gray-500">{{ getGroupName(report.group_id) }}</span>
              </div>
              <p class="text-sm text-gray-600 mb-2">{{ formatDate(report.report_date) }}</p>
              <p class="text-gray-700 mb-3">{{ report.content }}</p>
              <div v-if="report.activities && report.activities.length > 0" class="mb-2">
                <p class="text-sm font-medium text-gray-700">Aktivitäten:</p>
                <ul class="text-sm text-gray-600 list-disc list-inside">
                  <li v-for="activity in report.activities" :key="activity">{{ activity }}</li>
                </ul>
              </div>
              <div v-if="report.photos && report.photos.length > 0" class="mt-2">
                <span class="text-xs text-gray-500">📷 {{ report.photos.length }} Fotos</span>
              </div>
            </div>
            <div class="flex items-center gap-2">
              <NuxtLink
                :to="`/teacher/daily-reports/${report.id}`"
                class="inline-flex items-center gap-1 px-3 py-1.5 bg-blue-50 text-blue-700 rounded-md hover:bg-blue-100 transition-colors"
              >
                <span>👁️</span>
                <span>Ansehen</span>
              </NuxtLink>
              <NuxtLink
                :to="`/teacher/daily-reports/${report.id}?edit=true`"
                class="inline-flex items-center gap-1 px-3 py-1.5 bg-yellow-50 text-yellow-700 rounded-md hover:bg-yellow-100 transition-colors"
              >
                <span>✏️</span>
                <span>Bearbeiten</span>
              </NuxtLink>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useDailyReportsStore } from '~/stores/dailyReports'
import { useGroupsStore } from '~/stores/groups'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'teacher'
})

const dailyReportsStore = useDailyReportsStore()
const groupsStore = useGroupsStore()

const selectedDate = ref(new Date().toISOString().split('T')[0])
const { dailyReports: reports, loading, error } = storeToRefs(dailyReportsStore)

onMounted(async () => {
  await Promise.all([
    dailyReportsStore.fetchDailyReports(undefined, selectedDate.value),
    groupsStore.fetchGroups()
  ])
})

const fetchReports = async () => {
  await dailyReportsStore.fetchDailyReports(undefined, selectedDate.value)
}

const getGroupName = (groupId: string) => {
  const group = groupsStore.groups.find(g => g.id === groupId)
  return group ? group.name : groupId
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString('de-DE')
}
</script>
