// src/app/admin/portfolios/new/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.portfolios.new'

import React, { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'
import { usePortfoliosStore, type Portfolio } from '@/stores/portfolios'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { PortfolioForm } from '@/components/forms/PortfolioForm'
import { sT } from '@/i18n/sT'

export default function AdminPortfoliosNewPage() {
  const { t } = useI18n()

  const router = useRouter()
  const { user } = useAuth()
  const portfoliosStore = usePortfoliosStore()

  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)

  const handleSubmit = async (data: Partial<Portfolio>) => {
    if (!user?.id) {
      setError(t(sT('errNotAuthenticated')))
      return
    }

    setError('')
    setSubmitting(true)
    try {
      await portfoliosStore.createPortfolio(data, user.id)
      alert(t(sT('successPortfolioCreated')))
      router.push('/admin/portfolios')
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : t(sT('errCreatePortfolioItem')))
    } finally {
      setSubmitting(false)
    }
  }

  const handleCancel = () => {
    router.push('/admin/portfolios')
  }

  return (
    <div>
      <div className="mb-6 flex items-center justify-between gap-4">
        <button
          type="button"
          onClick={handleCancel}
          className="text-gray-600 hover:text-gray-900 mb-4 inline-block"
        >
          ← Back to Portfolios
        </button>
        <Heading size="xl">{t(pT(ROUTE))}</Heading>
      </div>

      <IOSCard className="max-w-3xl p-6">
        {error && <ErrorAlert message={error} />}

        <PortfolioForm
          onSubmit={(data: any) => void handleSubmit(data)}
          onCancel={handleCancel}
          loading={submitting}
        />

        {submitting && (
          <div className="flex justify-center pt-4">
            <LoadingSpinner size="sm" />
          </div>
        )}
      </IOSCard>
    </div>
  )
}

// pages/parent/leave/new.vue
<template>
  <div>
    <div class="mb-6">
      <NuxtLink
        to="/parent/leave"
        class="text-gray-600 hover:text-gray-900 mb-4 inline-block"
      >
        ← Back to Leave Requests
      </NuxtLink>
      <Heading size="xl">Request Leave</Heading>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else class="bg-white rounded-lg shadow p-6 max-w-2xl">
      <LeaveRequestForm
        :children="myChildren"
        @submit="handleSubmit"
        @cancel="handleCancel"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useSupabaseClient } from '#imports'
import { useAuthStore } from '~/stores/auth'
import { useLeaveRequestsStore } from '~/stores/leaveRequests'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import LeaveRequestForm from '~/components/forms/LeaveRequestForm.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'parent'
})

const router = useRouter()
const supabase = useSupabaseClient()
const authStore = useAuthStore()
const leaveRequestsStore = useLeaveRequestsStore()

const loading = ref(true)
const myChildren = ref<any[]>([])

onMounted(async () => {
  try {
    const userId = authStore.user?.id
    if (!userId) return

    const { data: children } = await supabase
      .from('children')
      .select('*')
      .contains('parent_ids', [userId])

    myChildren.value = children || []
  } catch (error) {
    console.error('Error fetching children:', error)
  } finally {
    loading.value = false
  }
})

const handleSubmit = async (data: any) => {
  try {
    await leaveRequestsStore.createLeaveRequest(data)
    alert('Leave request submitted successfully!')
    router.push('/parent/leave')
  } catch (error: any) {
    alert(error.message || 'Failed to submit leave request')
  }
}

const handleCancel = () => {
  router.push('/parent/leave')
}
</script>
