// next-app/src/app/teacher/payroll/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'teacher.payroll'

import React, { useEffect, useState } from 'react'
import { usePayrollStore, StaffPayroll } from '@/stores/payroll'
import { useAuth } from '@/hooks/useAuth'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

export default function TeacherPayrollPage() {
  const { t } = useI18n()

  const { profile } = useAuth()
  const { payroll, loading, error, fetchPayroll } = usePayrollStore()
  
  useEffect(() => {
    if (profile?.id) {
        fetchPayroll(profile.id)
    }
  }, [profile, fetchPayroll])

  if (loading && payroll.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-4xl mx-auto pb-12">
      <div className="mb-10 text-center">
        <Heading size="xl" className="text-gray-900 tracking-tight">{t(pT(ROUTE))}</Heading>
        <p className="text-sm text-gray-500 mt-1">Überblick über Ihre monatlichen Gehaltsabrechnungen.</p>
      </div>

      {payroll.length === 0 ? (
        <IOSCard className="p-20 text-center bg-gray-50/30 border-black/5">
          <div className="text-6xl opacity-10 mb-6">💼</div>
          <p className="text-gray-400 font-bold max-w-xs mx-auto">Noch keine Abrechnungen in diesem System vorhanden.</p>
        </IOSCard>
      ) : (
        <div className="space-y-4">
            {payroll.map(entry => (
                <IOSCard key={entry.id} className="p-0 overflow-hidden border-black/5 group hover:shadow-xl transition-all duration-300">
                    <div className="p-6 md:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6">
                        <div className="flex-1">
                            <div className="flex items-center gap-3 mb-2">
                                <h3 className="text-lg font-black text-gray-900">{new Date(entry.year, entry.month - 1).toLocaleString('de-DE', { month: 'long', year: 'numeric' })}</h3>
                                <span className={`px-2 py-0.5 text-[9px] font-black uppercase tracking-widest rounded-md border ${
                                    entry.status === 'paid' ? 'bg-green-50 text-green-600 border-green-100' : 'bg-blue-50 text-blue-600 border-blue-100'
                                }`}>
                                    {entry.status}
                                </span>
                            </div>
                            <div className="flex flex-wrap gap-x-6 gap-y-2 text-[10px] font-black text-black/30 uppercase tracking-widest">
                                <span className="text-[#667eea]">💵 Netto: {entry.net_salary.toFixed(2)}€</span>
                                <span>🕒 Überstunden: {entry.overtime_hours}h</span>
                            </div>
                        </div>

                        <button className="px-6 py-2.5 bg-gray-50 border border-black/5 text-[10px] font-black uppercase tracking-widest rounded-xl hover:bg-white transition-all">
                             📄 Abrechnung Laden
                        </button>
                    </div>
                </IOSCard>
            ))}
        </div>
      )}
    </div>
  )
}

// pages/teacher/payroll/index.vue
<template>
  <div>
    <Heading size="xl" class="mb-6">My Payroll</Heading>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="myPayroll.length === 0" class="p-8 text-center text-gray-500">
        No payroll records found.
      </div>

      <table v-else class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Period</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Base Salary</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Overtime</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Bonuses</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Deductions</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Net Salary</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr v-for="record in myPayroll" :key="record.id" class="hover:bg-gray-50">
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
              {{ getMonthName(record.month) }} {{ record.year }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              €{{ record.base_salary.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              €{{ record.overtime_amount.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-green-600">
              €{{ record.bonuses.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-red-600">
              €{{ record.deductions.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
              €{{ record.net_salary.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span
                :class="[
                  'px-2 py-1 text-xs font-medium rounded-full',
                  record.status === 'paid' ? 'bg-green-100 text-green-800' :
                  record.status === 'approved' ? 'bg-blue-100 text-blue-800' :
                  'bg-yellow-100 text-yellow-800'
                ]"
              >
                {{ record.status }}
              </span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { usePayrollStore } from '~/stores/payroll'
import { useAuthStore } from '~/stores/auth'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'teacher'
})

const payrollStore = usePayrollStore()
const authStore = useAuthStore()

const { payroll, loading, error } = storeToRefs(payrollStore)

const myPayroll = computed(() => {
  if (!authStore.user?.id) return []
  return payroll.value.filter(p => p.staff_id === authStore.user?.id)
})

onMounted(async () => {
  if (authStore.user?.id) {
    await payrollStore.fetchPayroll(authStore.user.id)
  }
})

const getMonthName = (month: number) => {
  const date = new Date(2000, month - 1, 1)
  return date.toLocaleString('default', { month: 'long' })
}
</script>
