// src/components/layout/AppSidebar.tsx
'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'
import { useI18n } from '@/i18n/I18nProvider'
import { LanguageSwitcher } from '@/components/common/LanguageSwitcher'
import {
  LayoutDashboard, Settings, Globe, Users, Briefcase, User, CheckSquare, 
  CalendarDays, ClipboardList, FileText, CheckCircle, FileSignature, 
  Eye, Book, Palette, Clock, Utensils, Receipt, CreditCard, Wrench, 
  Umbrella, MessageSquare, ListTodo, Bed, ShoppingCart, BarChart3, LogOut, Baby
} from 'lucide-react'
import { ThemeToggle } from '@/components/common/ThemeToggle'

interface AppSidebarProps {
  collapsed?: boolean
  onCollapsedChange?: (collapsed: boolean) => void
}

type NavItem = {
  path: string
  labelKey: string
  icon: React.ReactNode
}

export function AppSidebar({ collapsed: controlledCollapsed, onCollapsedChange }: AppSidebarProps) {
  const [internalCollapsed, setInternalCollapsed] = useState(false)
  const pathname = usePathname()
  const { profile, loading } = useAuth()
  const { t } = useI18n()

  const isCollapsed = controlledCollapsed ?? internalCollapsed

  const toggleCollapse = () => {
    if (onCollapsedChange) {
      onCollapsedChange(!isCollapsed)
    } else {
      setInternalCollapsed(!isCollapsed)
    }
  }

  const role = profile?.role
  const navItems: NavItem[] = []

  // Admin grouped sections — rendered separately for section labels
  type NavSection = { label: string; items: NavItem[] }
  const adminSections: NavSection[] = []

  const iconProps = { size: 20, className: "shrink-0 transition-transform duration-200 group-hover:scale-110" }

  if (!role) {
    navItems.push({ path: '/dashboard', labelKey: 'nav.gen.dashboard', icon: <LayoutDashboard {...iconProps} /> })
  } else if (role === 'admin') {
    // Core navigation (no section header — shown at top)
    navItems.push(
      { path: '/admin/dashboard', labelKey: 'nav.admin.dashboard', icon: <LayoutDashboard {...iconProps} /> },
      { path: '/admin/setup', labelKey: 'nav.admin.setup', icon: <Settings {...iconProps} /> },
      { path: '/admin/site', labelKey: 'nav.admin.site', icon: <Globe {...iconProps} /> },
    )
    adminSections.push(
      {
        label: 'Management',
        items: [
          { path: '/admin/children', labelKey: 'nav.admin.children', icon: <Baby {...iconProps} /> },
          { path: '/admin/groups', labelKey: 'nav.admin.groups', icon: <Users {...iconProps} /> },
          { path: '/admin/staff', labelKey: 'nav.admin.staff', icon: <Briefcase {...iconProps} /> },
          { path: '/admin/users', labelKey: 'nav.admin.users', icon: <User {...iconProps} /> },
          { path: '/admin/attendance', labelKey: 'nav.admin.attendance', icon: <CheckSquare {...iconProps} /> },
          { path: '/admin/calendar', labelKey: 'nav.admin.calendar', icon: <CalendarDays {...iconProps} /> },
        ],
      },
      {
        label: 'Classroom',
        items: [
          { path: '/admin/applications', labelKey: 'nav.admin.applications', icon: <ClipboardList {...iconProps} /> },
          { path: '/admin/contracts', labelKey: 'nav.admin.contracts', icon: <FileText {...iconProps} /> },
          { path: '/admin/consents', labelKey: 'nav.admin.consents', icon: <CheckCircle {...iconProps} /> },
          { path: '/admin/daily-reports', labelKey: 'nav.admin.dailyReports', icon: <FileSignature {...iconProps} /> },
          { path: '/admin/observations', labelKey: 'nav.admin.observations', icon: <Eye {...iconProps} /> },
          { path: '/admin/portfolios', labelKey: 'nav.admin.portfolios', icon: <Book {...iconProps} /> },
          { path: '/admin/learning-themes', labelKey: 'nav.admin.learningThemes', icon: <Palette {...iconProps} /> },
          { path: '/admin/daily-routines', labelKey: 'nav.admin.dailyRoutines', icon: <Clock {...iconProps} /> },
        ],
      },
      {
        label: 'Finance & HR',
        items: [
          { path: '/admin/lunch/menus', labelKey: 'nav.admin.lunchMenus', icon: <Utensils {...iconProps} /> },
          { path: '/admin/lunch/billing', labelKey: 'nav.admin.lunchBilling', icon: <Receipt {...iconProps} /> },
          { path: '/admin/fees', labelKey: 'nav.admin.fees', icon: <CreditCard {...iconProps} /> },
          { path: '/admin/parent-work', labelKey: 'nav.admin.parentWork', icon: <Wrench {...iconProps} /> },
          { path: '/admin/leave', labelKey: 'nav.admin.leave', icon: <Umbrella {...iconProps} /> },
          { path: '/admin/hr/payroll', labelKey: 'nav.admin.hrPayroll', icon: <Briefcase {...iconProps} /> },
          { path: '/admin/messages', labelKey: 'nav.admin.messages', icon: <MessageSquare {...iconProps} /> },
          { path: '/admin/settings', labelKey: 'nav.admin.settings', icon: <Settings {...iconProps} /> },
        ],
      },
    )
  } else if (role === 'teacher') {
    navItems.push(
      { path: '/teacher/dashboard', labelKey: 'nav.teacher.dashboard', icon: <LayoutDashboard {...iconProps} /> },
      { path: '/teacher/todo', labelKey: 'nav.teacher.todo', icon: <ListTodo {...iconProps} /> },
      { path: '/teacher/children', labelKey: 'nav.teacher.children', icon: <Baby {...iconProps} /> },
      { path: '/teacher/attendance', labelKey: 'nav.teacher.attendance', icon: <CheckSquare {...iconProps} /> },
      { path: '/teacher/daily-reports', labelKey: 'nav.teacher.dailyReports', icon: <FileSignature {...iconProps} /> },
      { path: '/teacher/observations', labelKey: 'nav.teacher.observations', icon: <Eye {...iconProps} /> },
      { path: '/teacher/portfolios', labelKey: 'nav.teacher.portfolios', icon: <Book {...iconProps} /> },
      { path: '/teacher/nap-records', labelKey: 'nav.teacher.napRecords', icon: <Bed {...iconProps} /> },
      { path: '/teacher/calendar', labelKey: 'nav.teacher.calendar', icon: <CalendarDays {...iconProps} /> },
      { path: '/teacher/leave', labelKey: 'nav.teacher.leave', icon: <Umbrella {...iconProps} /> },
      { path: '/teacher/payroll', labelKey: 'nav.teacher.payroll', icon: <Briefcase {...iconProps} /> },
      { path: '/teacher/messages', labelKey: 'nav.teacher.messages', icon: <MessageSquare {...iconProps} /> }
    )
  } else if (role === 'parent') {
    navItems.push(
      { path: '/parent/dashboard', labelKey: 'nav.parent.dashboard', icon: <LayoutDashboard {...iconProps} /> },
      { path: '/parent/children', labelKey: 'nav.parent.children', icon: <Baby {...iconProps} /> },
      { path: '/parent/attendance', labelKey: 'nav.parent.attendance', icon: <CheckSquare {...iconProps} /> },
      { path: '/parent/daily-reports', labelKey: 'nav.parent.dailyReports', icon: <FileSignature {...iconProps} /> },
      { path: '/parent/observations', labelKey: 'nav.parent.observations', icon: <Eye {...iconProps} /> },
      { path: '/parent/portfolios', labelKey: 'nav.parent.portfolios', icon: <Book {...iconProps} /> },
      { path: '/parent/learning-themes', labelKey: 'nav.parent.learningThemes', icon: <Palette {...iconProps} /> },
      { path: '/parent/absences', labelKey: 'nav.parent.absences', icon: <Umbrella {...iconProps} /> },
      { path: '/parent/calendar', labelKey: 'nav.parent.calendar', icon: <CalendarDays {...iconProps} /> },
      { path: '/parent/lunch', labelKey: 'nav.parent.lunch', icon: <Utensils {...iconProps} /> },
      { path: '/parent/fees', labelKey: 'nav.parent.fees', icon: <CreditCard {...iconProps} /> },
      { path: '/parent/work', labelKey: 'nav.parent.parentWork', icon: <Wrench {...iconProps} /> },
      { path: '/parent/messages', labelKey: 'nav.parent.messages', icon: <MessageSquare {...iconProps} /> }
    )
  } else if (role === 'kitchen') {
    navItems.push(
      { path: '/kitchen/dashboard', labelKey: 'nav.kitchen.dashboard', icon: <LayoutDashboard {...iconProps} /> },
      { path: '/kitchen/menus', labelKey: 'nav.kitchen.menus', icon: <Utensils {...iconProps} /> },
      { path: '/kitchen/orders', labelKey: 'nav.kitchen.orders', icon: <ShoppingCart {...iconProps} /> }
    )
  } else if (role === 'support') {
    navItems.push(
      { path: '/support/dashboard', labelKey: 'nav.support.dashboard', icon: <LayoutDashboard {...iconProps} /> },
      { path: '/support/attendance', labelKey: 'nav.support.attendance', icon: <CheckSquare {...iconProps} /> },
      { path: '/support/children', labelKey: 'nav.support.children', icon: <Baby {...iconProps} /> },
      { path: '/support/messages', labelKey: 'nav.support.messages', icon: <MessageSquare {...iconProps} /> },
      { path: '/support/reports', labelKey: 'nav.support.reports', icon: <BarChart3 {...iconProps} /> },
      { path: '/support/payroll', labelKey: 'nav.support.payroll', icon: <Briefcase {...iconProps} /> }
    )
  }

  const isActive = (path: string) => pathname === path || pathname.startsWith(path + '/')

  const roleLabelKey =
    role === 'admin' || role === 'teacher' || role === 'parent' || role === 'kitchen' || role === 'support'
      ? (`roles.${role}` as const)
      : null
  const userRoleLabel = loading ? t('roles.loadingRole') : roleLabelKey ? t(roleLabelKey) : t('roles.roleUnset')

  return (
    <div className={`h-full flex flex-col bg-background text-foreground transition-all duration-300 border-r border-slate-100 dark:border-white/5 z-50 ${isCollapsed ? 'w-20' : 'w-full'}`}>
      <div className="px-5 py-8 flex items-center justify-between border-b border-slate-50 dark:border-white/5 bg-background">
        <div className="flex items-center gap-3 min-w-0 overflow-hidden">
          <div className="shrink-0 w-10 h-10 bg-linear-to-br from-indigo-600 to-indigo-500 rounded-xl flex items-center justify-center text-white font-bold text-sm shadow-lg shadow-indigo-100">
            KG
          </div>
          {!isCollapsed && (
            <div className="flex-1 min-w-0 transition-opacity duration-300">
              <p className="text-sm font-bold text-slate-900 dark:text-white tracking-tight truncate font-display">{t('brand.appTitle')}</p>
              <p className="text-[10px] text-indigo-500 font-bold tracking-widest uppercase mt-0.5">
                {loading ? '...' : userRoleLabel}
              </p>
            </div>
          )}
        </div>
      </div>
      
      <nav className="flex-1 px-4 py-4 overflow-y-auto custom-scrollbar">
        {loading ? (
          <div className="space-y-2 py-4">
            {Array.from({ length: 8 }).map((_, i) => (
              <div key={i} className="h-11 px-4 rounded-xl bg-slate-50 animate-pulse"></div>
            ))}
          </div>
        ) : (
          <>
            {/* Core nav items (always flat, no section label) */}
            <div className="space-y-0.5 py-3">
              {navItems.map((item) => {
                const active = isActive(item.path)
                return (
                  <Link
                    key={item.path}
                    href={item.path}
                    className={`group relative flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-900/40 ${
                      active
                        ? 'bg-indigo-50 text-indigo-700 font-bold shadow-sm dark:bg-indigo-950/60 dark:text-indigo-200'
                        : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-white/5 dark:hover:text-slate-100'
                    } ${isCollapsed ? 'justify-center px-0' : ''}`}
                    title={isCollapsed ? t(item.labelKey) : undefined}
                  >
                    {active && (
                      <span className="absolute left-0 top-1/2 -translate-y-1/2 w-1 h-6 bg-indigo-600 rounded-r-full" />
                    )}
                    <span className={`${active ? 'text-indigo-600 dark:text-indigo-300' : 'text-slate-400 group-hover:text-indigo-500 dark:group-hover:text-indigo-400 transition-colors'}`}>
                      {item.icon}
                    </span>
                    {!isCollapsed && (
                      <span className="truncate flex-1 tracking-tight">{t(item.labelKey)}</span>
                    )}
                  </Link>
                )
              })}
            </div>

            {/* Admin grouped sections with labels */}
            {adminSections.map((section) => (
              <div key={section.label}>
                {!isCollapsed && (
                  <div className="mt-4 mb-1 px-3 flex items-center gap-2">
                    <span className="text-[9px] font-black uppercase tracking-[0.2em] text-slate-400 dark:text-slate-600">{section.label}</span>
                    <div className="flex-1 h-px bg-slate-100 dark:bg-white/5" />
                  </div>
                )}
                {isCollapsed && <div className="my-2 mx-2 h-px bg-slate-100 dark:bg-white/5" />}
                <div className="space-y-0.5">
                  {section.items.map((item) => {
                    const active = isActive(item.path)
                    return (
                      <Link
                        key={item.path}
                        href={item.path}
                        className={`group relative flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-900/40 ${
                          active
                            ? 'bg-indigo-50 text-indigo-700 font-bold shadow-sm dark:bg-indigo-950/60 dark:text-indigo-200'
                            : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-white/5 dark:hover:text-slate-100'
                        } ${isCollapsed ? 'justify-center px-0' : ''}`}
                        title={isCollapsed ? t(item.labelKey) : undefined}
                      >
                        {active && (
                          <span className="absolute left-0 top-1/2 -translate-y-1/2 w-1 h-6 bg-indigo-600 rounded-r-full" />
                        )}
                        <span className={`${active ? 'text-indigo-600 dark:text-indigo-300' : 'text-slate-400 group-hover:text-indigo-500 dark:group-hover:text-indigo-400 transition-colors'}`}>
                          {item.icon}
                        </span>
                        {!isCollapsed && (
                          <span className="truncate flex-1 tracking-tight">{t(item.labelKey)}</span>
                        )}
                      </Link>
                    )
                  })}
                </div>
              </div>
            ))}
          </>
        )}
      </nav>

      <div className="border-t border-slate-50 dark:border-white/5 p-4 flex flex-col gap-3 mt-auto bg-slate-50/50 dark:bg-white/5">
        <Link
          href="/logout"
          className={`flex items-center gap-3 justify-center w-full px-3 py-2.5 rounded-xl text-sm font-bold text-rose-600 bg-rose-50 hover:bg-rose-100 hover:text-rose-700 dark:text-rose-400 dark:bg-rose-950/40 dark:hover:bg-rose-950/60 transition-all focus:ring-2 focus:ring-rose-100 dark:focus:ring-rose-900/50 ${isCollapsed ? 'px-0' : ''}`}
          title={isCollapsed ? t('nav.logout') : undefined}
        >
          <LogOut size={18} className="shrink-0" aria-hidden />
          {!isCollapsed && <span className="truncate tracking-tight">{t('nav.logout')}</span>}
        </Link>
        {!isCollapsed && (
          <div className="pt-2 flex flex-col gap-3">
            <div className="flex justify-center">
              <ThemeToggle />
            </div>
            <LanguageSwitcher className="w-full justify-center brightness-100" />
          </div>
        )}
      </div>
    </div>
  )
}

// components/layout/AppSidebar.vue
<template>
  <div
    class="h-full flex flex-col sidebar-container bg-white/80 backdrop-blur-xl border-r border-white/20 transition-all duration-200"
    :class="{ 'sidebar-collapsed': collapsed }"
  >
    <!-- Sidebar Header -->
    <div class="px-4 py-4 border-b border-gray-100 flex items-center justify-between">
      <div class="flex items-center gap-2 min-w-0">
        <div class="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center text-white font-bold text-sm">
          KG
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-xs font-semibold text-gray-900 truncate sidebar-label">Kita Management</p>
          <p class="text-xs text-gray-500 truncate flex items-center gap-1 sidebar-label">
            <span v-if="loadingRole" class="inline-flex h-4 w-4 border-2 border-gray-300 border-t-blue-500 rounded-full animate-spin" />
            <span>{{ userRoleLabel }}</span>
          </p>
        </div>
      </div>
      <button
        class="flex-shrink-0 w-9 h-9 rounded-lg hover:bg-gray-100 flex items-center justify-center text-gray-500 hover:text-gray-800 transition"
        @click="toggleCollapse"
        aria-label="Sidebar ein/ausklappen"
      >
        <span v-if="collapsed">»</span>
        <span v-else>«</span>
      </button>
    </div>
    
    <nav class="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
      <template v-if="loadingRole">
        <div
          v-for="i in 8"
          :key="i"
          class="h-11 px-4 rounded-lg bg-gray-100 animate-pulse"
        ></div>
      </template>
      <template v-else>
        <NuxtLink
          v-for="item in navItems"
          :key="item.path"
          :to="item.path"
          :class="[
            'group relative flex items-center gap-3 px-4 py-3 ios-rounded',
            'text-sm font-medium ios-animate ios-press',
            'hover:bg-blue-50 hover:text-blue-700 hover:shadow-sm',
            'focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-1',
            isActive(item.path)
              ? 'bg-blue-50 text-blue-700 shadow-sm font-semibold ios-glass'
              : 'text-gray-700 hover:text-blue-700'
          ]"
        >
          <!-- Active indicator bar -->
          <span
            v-if="isActive(item.path)"
            class="absolute left-0 top-1/2 -translate-y-1/2 w-1 h-8 bg-blue-600 rounded-r-full"
          />
          
          <!-- Icon -->
          <span
            :class="[
              'text-xl flex-shrink-0 transition-transform duration-200',
              isActive(item.path) ? 'scale-110' : 'group-hover:scale-110'
            ]"
          >
            {{ item.icon }}
          </span>
          
          <!-- Label -->
          <span class="truncate flex-1 sidebar-label">{{ item.label }}</span>
          
          <!-- Hover arrow indicator -->
          <span
            v-if="!isActive(item.path)"
            class="opacity-0 group-hover:opacity-100 transition-opacity duration-200 text-blue-600"
          >
            →
          </span>
        </NuxtLink>
      </template>
    </nav>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { useSupabaseClient } from '#imports'
import { useAuthStore } from '~/stores/auth'

const route = useRoute()
const authStore = useAuthStore()
const supabase = useSupabaseClient()
const loadingRole = ref(true)
const collapsedInternal = ref(false)

const props = defineProps<{
  collapsed?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:collapsed', value: boolean): void
}>()

const collapsed = computed({
  get: () => props.collapsed ?? collapsedInternal.value,
  set: (val: boolean) => {
    collapsedInternal.value = val
    emit('update:collapsed', val)
  }
})

const effectiveRole = computed(() => {
  // First check if we have a role in the store
  if (authStore.userRole) return authStore.userRole
  
  // Check if profile exists but role is missing
  if (authStore.profile && !authStore.profile.role) {
    console.warn('Sidebar: Profile exists but role is missing')
  }
  
  // If we're on an admin route and have a user, assume admin (fallback)
  if (!loadingRole.value && authStore.user && route.path.startsWith('/admin/')) {
    console.log('Sidebar: Using admin fallback based on route')
    return 'admin'
  }
  
  // If we're on a teacher route and have a user, assume teacher (fallback)
  if (!loadingRole.value && authStore.user && route.path.startsWith('/teacher/')) {
    console.log('Sidebar: Using teacher fallback based on route')
    return 'teacher'
  }
  
  // If we're on a parent route and have a user, assume parent (fallback)
  if (!loadingRole.value && authStore.user && route.path.startsWith('/parent/')) {
    console.log('Sidebar: Using parent fallback based on route')
    return 'parent'
  }
  
  // If we're on a kitchen route and have a user, assume kitchen (fallback)
  if (!loadingRole.value && authStore.user && route.path.startsWith('/kitchen/')) {
    console.log('Sidebar: Using kitchen fallback based on route')
    return 'kitchen'
  }
  
  // If we're on a support route and have a user, assume support (fallback)
  if (!loadingRole.value && authStore.user && route.path.startsWith('/support/')) {
    console.log('Sidebar: Using support fallback based on route')
    return 'support'
  }
  
  return null
})

const navItems = computed(() => {
  const role = effectiveRole.value
  const items: Array<{ path: string; label: string; icon: string }> = []

  // While loading, keep skeleton
  if (loadingRole.value) return items

  // Fallback when no role resolved
  if (!role) {
    items.push({ path: '/dashboard', label: 'Dashboard', icon: '🏠' })
    return items
  }

  if (role === 'admin') {
    items.push(
      { path: '/admin/dashboard', label: 'Dashboard', icon: '🏠' },
      { path: '/admin/children', label: 'Kinder', icon: '👶' },
      { path: '/admin/groups', label: 'Gruppen', icon: '👪' },
      { path: '/admin/staff', label: 'Personal', icon: '👥' },
      { path: '/admin/users', label: 'Benutzer', icon: '👤' },
      { path: '/admin/attendance', label: 'Anwesenheit', icon: '✅' },
      { path: '/admin/calendar', label: 'Kalender', icon: '📅' },
      { path: '/admin/applications', label: 'Bewerbungen', icon: '📋' },
      { path: '/admin/contracts', label: 'Verträge', icon: '📝' },
      { path: '/admin/consents', label: 'Einverständnisse', icon: '✅' },
      { path: '/admin/daily-reports', label: 'Tagesberichte', icon: '📄' },
      { path: '/admin/observations', label: 'Beobachtungen', icon: '👁️' },
      { path: '/admin/portfolios', label: 'Portfolios', icon: '📔' },
      { path: '/admin/learning-themes', label: 'Bildungsbereiche', icon: '🎨' },
      { path: '/admin/daily-routines', label: 'Tagesablauf', icon: '⏰' },
      { path: '/admin/lunch/menus', label: 'Mittagessen', icon: '🍽️' },
      { path: '/admin/lunch/billing', label: 'Abrechnung', icon: '💰' },
      { path: '/admin/fees', label: 'Gebühren', icon: '💳' },
      { path: '/admin/parent-work', label: 'Elternarbeit', icon: '🔧' },
      { path: '/admin/leave', label: 'Urlaub', icon: '🏖️' },
      { path: '/admin/hr/payroll', label: 'Personalabrechnung', icon: '💼' },
      { path: '/admin/messages', label: 'Nachrichten', icon: '💬' },
      { path: '/admin/settings', label: 'Einstellungen', icon: '⚙️' }
    )
  } else if (role === 'teacher') {
    items.push(
      { path: '/teacher/dashboard', label: 'Dashboard', icon: '🏠' },
      { path: '/teacher/children', label: 'Kinder', icon: '👶' },
      { path: '/teacher/attendance', label: 'Anwesenheit', icon: '✅' },
      { path: '/teacher/daily-reports', label: 'Tagesberichte', icon: '📄' },
      { path: '/teacher/observations', label: 'Beobachtungen', icon: '👁️' },
      { path: '/teacher/portfolios', label: 'Portfolios', icon: '📔' },
      { path: '/teacher/leave', label: 'Urlaub', icon: '🏖️' },
      { path: '/teacher/payroll', label: 'Gehalt', icon: '💼' },
      { path: '/teacher/messages', label: 'Nachrichten', icon: '💬' }
    )
  } else if (role === 'parent') {
    items.push(
      { path: '/parent/dashboard', label: 'Dashboard', icon: '🏠' },
      { path: '/parent/children', label: 'Meine Kinder', icon: '👶' },
      { path: '/parent/attendance', label: 'Anwesenheit', icon: '✅' },
      { path: '/parent/daily-reports', label: 'Tagesberichte', icon: '📄' },
      { path: '/parent/observations', label: 'Beobachtungen', icon: '👁️' },
      { path: '/parent/portfolios', label: 'Portfolios', icon: '📔' },
      { path: '/parent/lunch', label: 'Mittagessen', icon: '🍽️' },
      { path: '/parent/fees', label: 'Gebühren', icon: '💰' },
      { path: '/parent/messages', label: 'Nachrichten', icon: '💬' }
    )
  } else if (role === 'kitchen') {
    items.push(
      { path: '/kitchen/dashboard', label: 'Dashboard', icon: '🏠' },
      { path: '/kitchen/menus', label: 'Menüs', icon: '🍽️' },
      { path: '/kitchen/orders', label: 'Bestellungen', icon: '🛒' }
    )
  } else if (role === 'support') {
    items.push(
      { path: '/support/dashboard', label: 'Dashboard', icon: '🏠' },
      { path: '/support/attendance', label: 'Anwesenheit', icon: '✅' },
      { path: '/support/children', label: 'Kinder', icon: '👶' },
      { path: '/support/messages', label: 'Nachrichten', icon: '💬' },
      { path: '/support/reports', label: 'Berichte', icon: '📊' },
      { path: '/support/payroll', label: 'Gehalt', icon: '💼' }
    )
  }

  return items
})

const isActive = (path: string) => {
  return route.path === path || route.path.startsWith(path + '/')
}

const userRoleLabel = computed(() => {
  const role = effectiveRole.value
  const labels: Record<string, string> = {
    admin: 'Administrator',
    teacher: 'Erzieher/in',
    parent: 'Elternteil',
    kitchen: 'Küche',
    support: 'Support'
  }
  if (loadingRole.value) return 'Rolle wird geladen…'
  if (!role) return 'Rolle nicht gesetzt'
  return labels[role] || role
})

const toggleCollapse = () => {
  collapsed.value = !collapsed.value
}

const loadProfile = async () => {
  try {
    // Check if profile already exists and has role
    if (authStore.profile?.role) {
      console.log('Sidebar: Profile already loaded', authStore.profile.role)
      loadingRole.value = false
      return
    }

    // Ensure user is loaded
    if (!authStore.user) {
      const { data: { session } } = await supabase.auth.getSession()
      if (session?.user) {
        authStore.setUser(session.user)
      } else {
        loadingRole.value = false
        return
      }
    }

    // If we have a user but no profile, fetch it aggressively
    if (authStore.user?.id) {
      loadingRole.value = true
      
      // Try fetching profile multiple times with increasing delays
      for (let i = 0; i < 5; i++) {
        await authStore.fetchProfile()
        
        if (authStore.profile?.role) {
          console.log('Sidebar: Profile loaded successfully', authStore.profile.role)
          break
        }
        
        // Wait before retry (exponential backoff)
        if (i < 4) {
          await new Promise(resolve => setTimeout(resolve, 300 * (i + 1)))
        }
      }
      
      // If still no role, log for debugging
      if (!authStore.profile?.role) {
        console.warn('Sidebar: Could not load profile after retries', {
          userId: authStore.user?.id,
          hasProfile: !!authStore.profile,
          profileRole: authStore.profile?.role
        })
      }
    }
  } catch (e) {
    console.error('Sidebar loadProfile error:', e)
  } finally {
    loadingRole.value = false
  }
}

// Watch for profile changes to update nav items reactively
watch(() => authStore.profile?.role, (newRole, oldRole) => {
  if (newRole && newRole !== oldRole) {
    console.log('Sidebar: Profile role changed to', newRole)
    loadingRole.value = false
  }
}, { immediate: true })

// Watch for user changes
watch(() => authStore.user?.id, (newUserId, oldUserId) => {
  if (newUserId && newUserId !== oldUserId && !authStore.profile?.role) {
    console.log('Sidebar: User changed, loading profile')
    loadProfile()
  }
}, { immediate: true })

// Also watch the entire profile object
watch(() => authStore.profile, (newProfile) => {
  if (newProfile?.role) {
    console.log('Sidebar: Profile object changed, role:', newProfile.role)
    loadingRole.value = false
  }
}, { deep: true, immediate: true })

onMounted(async () => {
  // Check if profile already exists
  if (authStore.profile?.role) {
    console.log('Sidebar mounted: Profile already exists', authStore.profile.role)
    loadingRole.value = false
  } else {
    await loadProfile()
  }
})
</script>

<style scoped>
/* Modern Scrollbar Styling */
.sidebar-container nav::-webkit-scrollbar {
  width: 6px;
}

.sidebar-container nav::-webkit-scrollbar-track {
  background: transparent;
}

.sidebar-container nav::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 3px;
  transition: background 0.2s ease;
}

.sidebar-container nav:hover::-webkit-scrollbar-thumb {
  background: #94a3b8;
}

.sidebar-container nav::-webkit-scrollbar-thumb:hover {
  background: #64748b;
}

/* Firefox Scrollbar */
.sidebar-container nav {
  scrollbar-width: thin;
  scrollbar-color: #cbd5e1 transparent;
}

.sidebar-container nav:hover {
  scrollbar-color: #94a3b8 transparent;
}

.sidebar-container.sidebar-collapsed {
  width: 100%;
}

.sidebar-container.sidebar-collapsed .sidebar-label {
  opacity: 0;
  width: 0;
  max-width: 0;
  overflow: hidden;
}

.sidebar-container.sidebar-collapsed nav .group {
  justify-content: center;
  padding-left: 0.75rem;
  padding-right: 0.75rem;
}

.sidebar-container.sidebar-collapsed nav .group span.text-xl {
  margin-right: 0;
}
</style>
