// pages/admin/fees/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <Heading size="xl">Monthly Fees</Heading>
      <div class="flex gap-2">
        <NuxtLink
          to="/admin/fees/generate"
          class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
        >
          ➕ Generate Fees
        </NuxtLink>
        <NuxtLink
          to="/admin/fees/config"
          class="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 transition-colors"
        >
          ⚙️ Fee Config
        </NuxtLink>
      </div>
    </div>

    <div class="bg-white rounded-lg shadow p-6 mb-6">
      <form @submit.prevent="filterFees" class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Month</label>
          <select
            v-model.number="filters.month"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          >
            <option :value="0">All Months</option>
            <option v-for="m in 12" :key="m" :value="m">
              {{ getMonthName(m) }}
            </option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Year</label>
          <input
            v-model.number="filters.year"
            type="number"
            :min="2020"
            :max="2100"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Status</label>
          <select
            v-model="filters.status"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          >
            <option value="">All Statuses</option>
            <option value="pending">Pending</option>
            <option value="paid">Paid</option>
            <option value="overdue">Overdue</option>
            <option value="waived">Waived</option>
          </select>
        </div>
        <div class="flex items-end">
          <button
            type="submit"
            class="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
          >
            Filter
          </button>
        </div>
      </form>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="filteredFees.length === 0" class="p-8 text-center text-gray-500">
        No fees found.
      </div>

      <table v-else class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Child</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Period</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Fee Type</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Amount</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Due Date</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr v-for="fee in filteredFees" :key="fee.id" class="hover:bg-gray-50">
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
              {{ getChildName(fee.child_id) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              {{ getMonthName(fee.month) }} {{ fee.year }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              {{ formatFeeType(fee.fee_type) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              €{{ fee.amount.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              {{ formatDate(fee.due_date) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span
                :class="[
                  'px-2 py-1 text-xs font-medium rounded-full',
                  fee.status === 'paid' ? 'bg-green-100 text-green-800' :
                  fee.status === 'overdue' ? 'bg-red-100 text-red-800' :
                  fee.status === 'waived' ? 'bg-gray-100 text-gray-800' :
                  'bg-yellow-100 text-yellow-800'
                ]"
              >
                {{ fee.status }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
              <NuxtLink
                :to="`/admin/fees/${fee.id}`"
                class="text-blue-600 hover:text-blue-900"
              >
                View
              </NuxtLink>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useMonthlyFeesStore } from '~/stores/monthlyFees'
import { useChildrenStore } from '~/stores/children'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const monthlyFeesStore = useMonthlyFeesStore()
const childrenStore = useChildrenStore()

const { fees, loading, error } = storeToRefs(monthlyFeesStore)
const { children } = storeToRefs(childrenStore)

const filters = ref({
  month: 0,
  year: new Date().getFullYear(),
  status: ''
})

const filteredFees = computed(() => {
  let result = fees.value

  if (filters.value.month > 0) {
    result = result.filter(f => f.month === filters.value.month)
  }

  if (filters.value.year) {
    result = result.filter(f => f.year === filters.value.year)
  }

  if (filters.value.status) {
    result = result.filter(f => f.status === filters.value.status)
  }

  return result
})

onMounted(async () => {
  try {
    await Promise.all([
      monthlyFeesStore.fetchFees(),
      childrenStore.fetchChildren()
    ])
  } catch (e: any) {
    console.error('Error loading fees:', e)
  }
})

const filterFees = async () => {
  await monthlyFeesStore.fetchFees(
    undefined,
    filters.value.month || undefined,
    filters.value.year || undefined
  )
}

const getChildName = (childId: string) => {
  const child = children.value.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}

const getMonthName = (month: number) => {
  const date = new Date(2000, month - 1, 1)
  return date.toLocaleString('default', { month: 'long' })
}

const formatFeeType = (type: string) => {
  const types: Record<string, string> = {
    tuition: 'Tuition',
    lunch: 'Lunch',
    activities: 'Activities',
    other: 'Other'
  }
  return types[type] || type
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}
</script>

// src/app/admin/fees/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.fees'

import React, { useEffect, useState, useMemo } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useMonthlyFeesStore } from '@/stores/monthlyFees'
import { useChildrenStore } from '@/stores/children'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'
import { useToastStore } from '@/stores/toast'
import { downloadTextFile, toCsv } from '@/utils/export/csv'

export default function AdminFeesPage() {
  const { t } = useI18n()

  const router = useRouter()
  const { fees, loading, error, fetchFees } = useMonthlyFeesStore()
  const { children, fetchChildren } = useChildrenStore()
  const toast = useToastStore()
  
  const [filters, setFilters] = useState({
    month: 0,
    year: new Date().getFullYear(),
    status: ''
  })

  useEffect(() => {
    fetchFees(undefined, filters.month || undefined, filters.year || undefined)
    fetchChildren()
  }, [fetchFees, fetchChildren])

  const filteredFees = useMemo(() => {
    let result = fees
    if (filters.month > 0) result = result.filter(f => f.month === filters.month)
    if (filters.year) result = result.filter(f => f.year === filters.year)
    if (filters.status) result = result.filter(f => f.status === filters.status)
    return result
  }, [fees, filters])

  const getChildName = (childId: string) => {
    const child = children.find(c => c.id === childId)
    return child ? `${child.first_name} ${child.last_name}` : childId
  }

  const getMonthName = (month: number) => {
    const date = new Date(2000, month - 1, 1)
    return date.toLocaleString('de-DE', { month: 'long' })
  }

  const formatFeeType = (type: string) => {
    const types: Record<string, string> = {
      tuition: 'Grundgebühr',
      lunch: 'Verpflegung',
      activities: 'Aktivitäten',
      other: 'Sonstiges'
    }
    return types[type] || type
  }

  const handleFilterChange = (e: React.ChangeEvent<HTMLSelectElement | HTMLInputElement>) => {
    const { name, value } = e.target
    setFilters(prev => ({ ...prev, [name]: name === 'status' ? value : parseInt(value) || 0 }))
  }

  const applyFilters = (e: React.FormEvent) => {
    e.preventDefault()
    fetchFees(undefined, filters.month || undefined, filters.year || undefined)
  }

  const exportFilteredCsv = () => {
    const rows = [
      ['Kind', 'Monat', 'Jahr', 'Art', 'Betrag', 'Fälligkeit', 'Status'],
      ...filteredFees.map((f) => [
        getChildName(f.child_id),
        getMonthName(f.month),
        f.year,
        formatFeeType(f.fee_type),
        f.amount,
        new Date(f.due_date).toLocaleDateString('de-DE'),
        f.status,
      ]),
    ]
    const csv = toCsv(rows, { delimiter: ';', includeBom: true })
    downloadTextFile(`gebuehren-${filters.month || 'alle'}-${filters.year || 'alle'}.csv`, csv, 'text/csv;charset=utf-8')
    toast.push({ type: 'success', title: 'Gebühren', message: 'CSV exportiert.' })
  }

  if (loading && fees.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-7xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <Heading size="xl" className="text-gray-900">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-gray-500 mt-1">Übersicht und Verwaltung aller monatlichen Gebühren.</p>
        </div>
        <div className="flex gap-3">
          <IOSButton variant="secondary" className="px-5 py-2.5 text-sm font-bold flex items-center gap-2" onClick={exportFilteredCsv}>
            <span>📥</span>
            <span>CSV Export</span>
          </IOSButton>
          <Link href="/admin/fees/config">
            <IOSButton variant="secondary" className="px-5 py-2.5 text-sm font-bold flex items-center gap-2">
              <span>⚙️</span>
              <span>Konfiguration</span>
            </IOSButton>
          </Link>
          <Link href="/admin/fees/generate">
            <IOSButton variant="primary" className="px-6 py-2.5 text-sm font-bold flex items-center gap-2">
              <span>➕</span>
              <span>Gebühren generieren</span>
            </IOSButton>
          </Link>
        </div>
      </div>

      <IOSCard className="p-6 mb-8 border-black/5 shadow-sm bg-[#f2f2f7]/30">
        <form onSubmit={applyFilters} className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
          <div>
            <label className="block text-[10px] font-black text-black/40 uppercase tracking-widest mb-1.5 ml-1">Monat</label>
            <select
              name="month"
              value={filters.month}
              onChange={handleFilterChange}
              className="w-full px-4 py-2.5 bg-white border border-black/5 rounded-xl text-sm font-bold text-gray-800 outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
            >
              <option value="0">Alle Monate</option>
              {[...Array(12)].map((_, i) => (
                <option key={i + 1} value={i + 1}>{getMonthName(i + 1)}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-[10px] font-black text-black/40 uppercase tracking-widest mb-1.5 ml-1">Jahr</label>
            <input
              name="year"
              type="number"
              value={filters.year}
              onChange={handleFilterChange}
              className="w-full px-4 py-2.5 bg-white border border-black/5 rounded-xl text-sm font-bold text-gray-800 outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
            />
          </div>
          <div>
            <label className="block text-[10px] font-black text-black/40 uppercase tracking-widest mb-1.5 ml-1">Status</label>
            <select
              name="status"
              value={filters.status}
              onChange={handleFilterChange}
              className="w-full px-4 py-2.5 bg-white border border-black/5 rounded-xl text-sm font-bold text-gray-800 outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
            >
              <option value="">Alle Status</option>
              <option value="pending">Ausstehend</option>
              <option value="paid">Bezahlt</option>
              <option value="overdue">Überfällig</option>
              <option value="waived">Erlassen</option>
            </select>
          </div>
          <IOSButton type="submit" variant="primary" className="w-full py-2.5 font-black text-xs uppercase tracking-widest">
            Filter anwenden
          </IOSButton>
        </form>
      </IOSCard>

      {error ? (
        <ErrorAlert message={error.message || 'Fehler beim Laden der Gebühren'} />
      ) : filteredFees.length === 0 ? (
        <IOSCard className="p-16 text-center bg-gray-50/50">
          <div className="text-5xl opacity-40 mb-4">💰</div>
          <p className="text-gray-500 font-medium">Keine Gebühren für die gewählten Filter gefunden.</p>
        </IOSCard>
      ) : (
        <IOSCard className="p-0 overflow-hidden shadow-sm border-black/5">
            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-gray-50/50">
                            <th className="px-6 py-4 text-[10px] font-black text-black/30 uppercase tracking-widest border-b border-black/5">Kind</th>
                            <th className="px-6 py-4 text-[10px] font-black text-black/30 uppercase tracking-widest border-b border-black/5">Zeitraum</th>
                            <th className="px-6 py-4 text-[10px] font-black text-black/30 uppercase tracking-widest border-b border-black/5">Art</th>
                            <th className="px-6 py-4 text-[10px] font-black text-black/30 uppercase tracking-widest border-b border-black/5">Betrag</th>
                            <th className="px-6 py-4 text-[10px] font-black text-black/30 uppercase tracking-widest border-b border-black/5">Fälligkeit</th>
                            <th className="px-6 py-4 text-[10px] font-black text-black/30 uppercase tracking-widest border-b border-black/5">Status</th>
                            <th className="px-6 py-4 text-[10px] font-black text-black/30 uppercase tracking-widest border-b border-black/5"></th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-black/5 font-medium text-sm text-gray-700">
                        {filteredFees.map(fee => (
                            <tr key={fee.id} className="hover:bg-gray-50/80 transition-colors group">
                                <td className="px-6 py-5 font-black text-gray-900 group-hover:text-[#667eea] transition-colors">{getChildName(fee.child_id)}</td>
                                <td className="px-6 py-5 whitespace-nowrap">{getMonthName(fee.month)} {fee.year}</td>
                                <td className="px-6 py-5 whitespace-nowrap">
                                    <span className="px-2 py-0.5 bg-gray-100 text-[10px] font-black text-gray-600 rounded-md uppercase tracking-widest">
                                        {formatFeeType(fee.fee_type)}
                                    </span>
                                </td>
                                <td className="px-6 py-5 font-black text-gray-900">€{fee.amount.toFixed(2)}</td>
                                <td className="px-6 py-5 whitespace-nowrap text-gray-400">{new Date(fee.due_date).toLocaleDateString('de-DE')}</td>
                                <td className="px-6 py-5 whitespace-nowrap">
                                    <span className={`px-2.5 py-1 text-[9px] font-black uppercase tracking-widest rounded-md ${
                                        fee.status === 'paid' ? 'bg-green-50 text-green-700 border border-green-100' :
                                        fee.status === 'overdue' ? 'bg-red-50 text-red-700 border border-red-100' :
                                        fee.status === 'waived' ? 'bg-gray-50 text-gray-500 border border-gray-100' :
                                        'bg-amber-50 text-amber-700 border border-amber-100'
                                    }`}>
                                        {fee.status === 'paid' ? 'Bezahlt' : fee.status === 'overdue' ? 'Fällig' : fee.status === 'waived' ? 'Erlassen' : 'Offen'}
                                    </span>
                                </td>
                                <td className="px-6 py-5 text-right">
                                    <Link href={`/admin/fees/${fee.id}`} className="text-[#667eea]/40 hover:text-[#667eea] transition-colors">
                                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 5l7 7-7 7" />
                                        </svg>
                                    </Link>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </IOSCard>
      )}
    </div>
  )
}
