// pages/login.vue
<template>
          <div class="login-page min-h-screen flex items-center justify-center p-4 relative overflow-hidden ios-background">
    
    <!-- Login Card -->
    <div class="login-container relative z-10 w-full max-w-md">
      <IOSCard class="p-8 md:p-10">
        <!-- Logo/Title -->
        <div class="text-center mb-8">
          <div class="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-purple-400 to-pink-400 rounded-2xl mb-4 shadow-lg">
            <span class="text-3xl">🎓</span>
          </div>
          <h1 class="text-3xl md:text-4xl font-bold text-gray-900 mb-2 tracking-tight">
            KG School
          </h1>
          <p class="text-gray-600 text-sm md:text-base">Kindergarten Management System</p>
        </div>
        
        <form @submit.prevent.stop="handleLogin" method="post" class="space-y-5" novalidate>
          <IOSInput
            id="email"
            v-model="email"
            label="E-Mail"
            type="email"
            placeholder="Geben Sie Ihre E-Mail ein"
            required
            :error="error && error.includes('email') ? error : undefined"
          />

          <IOSInput
            id="password"
            v-model="password"
            label="Passwort"
            type="password"
            placeholder="Geben Sie Ihr Passwort ein"
            required
            :error="error && error.includes('password') ? error : undefined"
          />

          <IOSButton
            type="button"
            :disabled="loading"
            variant="primary"
            size="large"
            class="w-full mt-6"
            @click="handleLogin($event)"
          >
            <span v-if="loading" class="flex items-center justify-center gap-2">
              <span class="ios-spinner"></span>
              Wird angemeldet...
            </span>
            <span v-else>Anmelden</span>
          </IOSButton>

          <div v-if="error && !error.includes('email') && !error.includes('password')" 
               class="ios-error-alert">
            <span class="ios-error-icon">⚠️</span>
            <span>{{ error }}</span>
          </div>
        </form>

        <div class="mt-8 text-center">
          <NuxtLink to="/" class="ios-link">
            ← Zurück zur Startseite
          </NuxtLink>
        </div>
      </IOSCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useSupabaseClient } from '#imports'
import { useRouter } from 'vue-router'
import IOSCard from '~/components/ui/IOSCard.vue'
import IOSButton from '~/components/ui/IOSButton.vue'
import IOSInput from '~/components/ui/IOSInput.vue'

// Use auth layout (no sidebar/header)
definePageMeta({
  layout: 'auth',
  // Disable i18n on login page to avoid loading issues
  keepalive: false
})

const supabase = useSupabaseClient()
const router = useRouter()

const email = ref('')
const password = ref('')
const loading = ref(false)
const error = ref('')

const handleLogin = async (event?: Event | MouseEvent) => {
  console.log('handleLogin called', { event, email: email.value, hasPassword: !!password.value })
  
  // Prevent any default form submission
  if (event) {
    event.preventDefault()
    event.stopPropagation()
    if ('stopImmediatePropagation' in event) {
      event.stopImmediatePropagation()
    }
  }
  
  // Prevent double submission
  if (loading.value) {
    console.log('Login already in progress, ignoring duplicate request')
    return
  }
  
  // Validate inputs
  if (!email.value || !email.value.trim()) {
    error.value = 'Email is required'
    console.log('Validation failed: Email required')
    return
  }
  
  if (!password.value) {
    error.value = 'Password is required'
    console.log('Validation failed: Password required')
    return
  }
  
  loading.value = true
  error.value = ''
  console.log('Starting login process...')

  try {
    console.log('Login attempt started for:', email.value.trim())
    
    const { data, error: err } = await supabase.auth.signInWithPassword({
      email: email.value.trim(),
      password: password.value
    })

    if (err) {
      console.error('Login error from Supabase:', err)
      error.value = err.message || 'Invalid email or password'
      loading.value = false
      return
    }

    if (!data || !data.session) {
      console.error('No session in response')
      error.value = 'Login failed: No session returned'
      loading.value = false
      return
    }

    console.log('Login successful, session received:', data.session.user.id)

    // Wait for session to be established and persisted
    await new Promise(resolve => setTimeout(resolve, 800))

    // Verify session is actually available before redirecting
    const { data: { session: verifySession }, error: verifyError } = await supabase.auth.getSession()
    
    if (verifyError || !verifySession?.user) {
      console.error('Login - Session verification failed:', verifyError)
      error.value = 'Session could not be established. Please try again.'
      loading.value = false
      return
    }

    console.log('Login - Session verified, redirecting to callback')

    // Use window.location for more reliable redirect
    window.location.href = '/auth/callback'
  } catch (e: any) {
    console.error('Login error:', e)
    error.value = e.message || 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.'
    loading.value = false
  }
}
</script>

<style scoped>
.login-page {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%);
  background-size: 200% 200%;
  animation: gradientShift 15s ease infinite;
}

@keyframes gradientShift {
  0% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}

.login-container {
  animation: fadeInUp 0.6s cubic-bezier(0.4, 0, 0.2, 1);
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.ios-spinner {
  width: 16px;
  height: 16px;
  border: 2px solid rgba(0, 0, 0, 0.2);
  border-top-color: #667eea;
  border-radius: 50%;
  animation: spin 0.6s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.ios-error-alert {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 16px;
  background: rgba(255, 59, 48, 0.15);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 59, 48, 0.3);
  border-radius: 12px;
  color: #ff3b30;
  font-size: 14px;
  animation: shake 0.4s ease;
}

@keyframes shake {
  0%, 100% { transform: translateX(0); }
  25% { transform: translateX(-5px); }
  75% { transform: translateX(5px); }
}

.ios-error-icon {
  font-size: 18px;
}

.ios-link {
  color: #6e6e73;
  font-size: 14px;
  text-decoration: none;
  transition: all 0.2s ease;
  display: inline-block;
}

.ios-link:hover {
  color: #1d1d1f;
  transform: translateX(-3px);
}

/* Mobile optimizations */
@media (max-width: 768px) {
  .login-page {
    padding: 16px;
  }
  
  .login-container {
    max-width: 100%;
  }
}

/* iOS safe area support */
@supports (padding: max(0px)) {
  .login-page {
    padding-left: max(16px, env(safe-area-inset-left));
    padding-right: max(16px, env(safe-area-inset-right));
    padding-bottom: max(16px, env(safe-area-inset-bottom));
  }
}
</style>

// src/app/login/page.tsx
'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSInput } from '@/components/ui/IOSInput'
import { IOSButton } from '@/components/ui/IOSButton'
import { useAuth } from '@/hooks/useAuth'
import { useRouter } from 'next/navigation'
import { useI18n } from '@/i18n/I18nProvider'
import { LanguageSwitcher } from '@/components/common/LanguageSwitcher'

export default function LoginPage() {
  const { t } = useI18n()
  const router = useRouter()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const { login } = useAuth()

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (loading) return
    
    if (!email.trim()) {
      setError(t('login.emailRequired'))
      return
    }
    
    if (!password) {
      setError(t('login.passwordRequired'))
      return
    }

    setLoading(true)
    setError('')

    try {
      await login(email.trim(), password)
      router.replace('/dashboard')
    } catch (e: any) {
      console.error('Login error:', e)
      setError(e.message || t('login.loginFailed'))
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center p-4 relative overflow-hidden bg-[linear-gradient(135deg,#667eea_0%,#764ba2_50%,#f093fb_100%)] bg-size-[200%_200%] animate-[gradientShift_15s_ease_infinite]">
      <style dangerouslySetInnerHTML={{__html: `
        @keyframes gradientShift {
          0% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }
      `}} />
      
      <div className="relative z-10 w-full max-w-md animate-[fadeInUp_0.6s_cubic-bezier(0.4,0,0.2,1)]">
        <style dangerouslySetInnerHTML={{__html: `
          @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(30px); }
            to { opacity: 1; transform: translateY(0); }
          }
        `}} />
        
        <IOSCard className="p-8 md:p-10">
          <div className="mb-4 flex justify-end">
            <LanguageSwitcher />
          </div>
          <div className="text-center mb-8">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-linear-to-br from-purple-400 to-pink-400 rounded-2xl mb-4 shadow-lg">
              <span className="text-3xl">🎓</span>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2 tracking-tight">
              {t('login.title')}
            </h1>
            <p className="text-gray-600 text-sm md:text-base">{t('login.subtitle')}</p>
          </div>
          
          <form onSubmit={handleLogin} className="space-y-5" noValidate>
            <IOSInput
              id="email"
              label={t('login.emailLabel')}
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder={t('login.emailPlaceholder')}
              required
              error={error.includes('email') || error.includes('Email') ? error : undefined}
            />

            <IOSInput
              id="password"
              label={t('login.passwordLabel')}
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder={t('login.passwordPlaceholder')}
              required
              error={error.includes('password') || error.includes('Password') ? error : undefined}
            />

            <IOSButton
              type="submit"
              disabled={loading}
              variant="primary"
              size="large"
              className="w-full mt-6"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="w-4 h-4 border-2 border-black/20 border-t-white rounded-full animate-spin"></span>
                  {t('login.submitting')}
                </span>
              ) : (
                <span>{t('login.submit')}</span>
              )}
            </IOSButton>

            {error && !error.includes('email') && !error.includes('Email') && !error.includes('password') && !error.includes('Password') && (
              <div className="flex items-center gap-2.5 p-3 px-4 bg-[#ff3b30]/15 backdrop-blur-[10px] border border-[#ff3b30]/30 rounded-xl text-[#ff3b30] text-sm animate-[shake_0.4s_ease]">
                <style dangerouslySetInnerHTML={{__html: `
                  @keyframes shake {
                    0%, 100% { transform: translateX(0); }
                    25% { transform: translateX(-5px); }
                    75% { transform: translateX(5px); }
                  }
                `}} />
                <span className="text-[18px]">⚠️</span>
                <span>{error}</span>
              </div>
            )}
          </form>

          <div className="mt-8 text-center">
            <Link href="/" className="text-[#6e6e73] text-sm no-underline transition-all duration-200 inline-block hover:text-[#1d1d1f] hover:-translate-x-[3px]">
              ← {t('common.backToHome')}
            </Link>
            <div className="mt-3 flex justify-center gap-4 text-xs text-gray-500">
              <Link href="/privacy" className="hover:text-gray-700">
                {t('common.privacy')}
              </Link>
              <Link href="/imprint" className="hover:text-gray-700">
                {t('common.imprint')}
              </Link>
              <Link href="/security" className="hover:text-gray-700">
                {t('common.security')}
              </Link>
            </div>
          </div>
        </IOSCard>
      </div>
    </div>
  )
}
