// pages/admin/learning-themes/new.vue
<template>
  <div>
    <div class="mb-6">
      <NuxtLink
        to="/admin/learning-themes"
        class="text-gray-600 hover:text-gray-900 mb-4 inline-block"
      >
        ← Back to Learning Themes
      </NuxtLink>
      <Heading size="xl">Create Learning Theme</Heading>
    </div>

    <div class="bg-white rounded-lg shadow p-6 max-w-3xl">
      <LearningThemeForm @submit="handleSubmit" @cancel="handleCancel" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useLearningThemesStore } from '~/stores/learningThemes'
import Heading from '~/components/ui/Heading.vue'
import LearningThemeForm from '~/components/forms/LearningThemeForm.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const router = useRouter()
const learningThemesStore = useLearningThemesStore()

const handleSubmit = async (data: any) => {
  try {
    await learningThemesStore.createLearningTheme(data)
    alert('Learning theme created successfully!')
    router.push('/admin/learning-themes')
  } catch (error: any) {
    alert(error.message || 'Failed to create learning theme')
  }
}

const handleCancel = () => {
  router.push('/admin/learning-themes')
}
</script>

// next-app/src/app/admin/observations/new/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.observations.new'

import React, { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useObservationsStore, type Observation } from '@/stores/observations'
import { ObservationForm } from '@/components/forms/ObservationForm'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { ErrorAlert } from '@/components/common/ErrorAlert'

export default function AdminObservationsNewPage() {
  const { t } = useI18n()

  const router = useRouter()
  const observationsStore = useObservationsStore()

  const [error, setError] = useState('')

  const handleSubmit = async (data: {
    child_id: string
    observation_date: string
    context: string
    description: string
    development_area: string
    photos: string[]
    videos: string[]
  }) => {
    try {
      setError('')

      const payload: Partial<Observation> = {
        child_id: data.child_id,
        observation_date: data.observation_date,
        context: data.context ? data.context : undefined,
        description: data.description,
        development_area: data.development_area ? data.development_area : undefined,
        photos: data.photos,
        videos: data.videos,
      }

      await observationsStore.createObservation(payload)
      alert('Observation created successfully!')
      router.push('/admin/observations')
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to create observation')
    }
  }

  const handleCancel = () => {
    router.push('/admin/observations')
  }

  return (
    <div>
      <div className="mb-6">
        <button
          type="button"
          onClick={() => router.push('/admin/observations')}
          className="text-gray-600 hover:text-gray-900 mb-4 inline-block"
        >
          ← Back to Observations
        </button>
        <Heading size="xl">{t(pT(ROUTE))}</Heading>
      </div>

      <IOSCard className="max-w-3xl p-6">
        {error && <ErrorAlert message={error} />}
        <ObservationForm onSubmit={handleSubmit} onCancel={handleCancel} />
      </IOSCard>
    </div>
  )
}
