// pages/parent/leave/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <Heading size="xl">Leave Requests</Heading>
      <NuxtLink
        to="/parent/leave/new"
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
      >
        ➕ New Request
      </NuxtLink>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="leaveRequests.length === 0" class="p-8 text-center text-gray-500">
        No leave requests yet.
        <NuxtLink
          to="/parent/leave/new"
          class="text-blue-600 hover:text-blue-700 underline ml-1"
        >
          Create one now
        </NuxtLink>
      </div>

      <div v-else class="divide-y divide-gray-200">
        <div
          v-for="request in leaveRequests"
          :key="request.id"
          class="p-6 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-3 mb-2">
                <p class="font-medium text-gray-900">
                  {{ getChildName(request.child_id) }}
                </p>
                <span
                  :class="[
                    'px-2 py-1 text-xs font-medium rounded-full',
                    request.status === 'approved' ? 'bg-green-100 text-green-800' :
                    request.status === 'rejected' ? 'bg-red-100 text-red-800' :
                    'bg-yellow-100 text-yellow-800'
                  ]"
                >
                  {{ request.status }}
                </span>
              </div>
              
              <div class="text-sm text-gray-600 space-y-1">
                <p>
                  <strong>Dates:</strong> {{ formatDate(request.start_date) }} - {{ formatDate(request.end_date) }}
                </p>
                <p>
                  <strong>Type:</strong> {{ request.leave_type }}
                </p>
                <p>
                  <strong>Reason:</strong> {{ request.reason }}
                </p>
                <p v-if="request.notes">
                  <strong>Notes:</strong> {{ request.notes }}
                </p>
                <p v-if="request.admin_notes" class="mt-2 text-gray-500 italic">
                  <strong>Admin Response:</strong> {{ request.admin_notes }}
                </p>
                <p class="text-xs text-gray-500 mt-2">
                  Submitted: {{ formatDateTime(request.created_at) }}
                </p>
                <p v-if="request.reviewed_at" class="text-xs text-gray-500">
                  Reviewed: {{ formatDateTime(request.reviewed_at) }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useSupabaseClient } from '#imports'
import { useAuthStore } from '~/stores/auth'
import { useLeaveRequestsStore } from '~/stores/leaveRequests'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'parent'
})

const supabase = useSupabaseClient()
const authStore = useAuthStore()
const leaveRequestsStore = useLeaveRequestsStore()

const loading = ref(true)
const error = ref('')
const myChildren = ref<any[]>([])
const { leaveRequests } = storeToRefs(leaveRequestsStore)

onMounted(async () => {
  try {
    const userId = authStore.user?.id
    if (!userId) return

    // Fetch my children
    const { data: children } = await supabase
      .from('children')
      .select('*')
      .contains('parent_ids', [userId])

    myChildren.value = children || []

    // Fetch leave requests for my children
    if (myChildren.value.length > 0) {
      const childIds = myChildren.value.map(c => c.id)
      await Promise.all(
        childIds.map(childId => leaveRequestsStore.fetchLeaveRequests(childId))
      )
    }
  } catch (e: any) {
    error.value = e.message
  } finally {
    loading.value = false
  }
})

const getChildName = (childId: string) => {
  const child = myChildren.value.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}

const formatDateTime = (date: string) => {
  return new Date(date).toLocaleString()
}
</script>

// next-app/src/app/admin/leave/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.leave'

import React, { useEffect, useState } from 'react'
import { useLeaveRequestsStore, LeaveRequest } from '@/stores/leaveRequests'
import { useTeacherLeaveRequestsStore, TeacherLeaveRequest } from '@/stores/teacherLeaveRequests'
import { useChildrenStore } from '@/stores/children'
import { useStaffStore } from '@/stores/staff'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

export default function AdminLeavePage() {
  const { t } = useI18n()

  const { leaveRequests, fetchLeaveRequests, updateLeaveRequestStatus } = useLeaveRequestsStore()
  const {
    leaveRequests: teacherRequests,
    fetchLeaveRequests: fetchTeacherRequests,
    updateLeaveRequestStatus: updateTeacherStatus,
  } = useTeacherLeaveRequestsStore()
  const { children, fetchChildren } = useChildrenStore()
  const { staff, fetchStaff } = useStaffStore()
  
  const [activeTab, setActiveTab] = useState<'children' | 'staff'>('children')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function loadData() {
        await Promise.all([
            fetchLeaveRequests(),
            fetchTeacherRequests(),
            fetchChildren(),
            fetchStaff()
        ])
        setLoading(false)
    }
    loadData()
  }, [fetchLeaveRequests, fetchTeacherRequests, fetchChildren, fetchStaff])

  const getChildName = (id: string) => {
    const c = children.find(c => c.id === id)
    return c ? `${c.first_name} ${c.last_name}` : 'Unbekannt'
  }

  const getStaffName = (id: string) => {
    const s = staff.find(s => s.id === id)
    return s ? s.full_name : 'Unbekannt'
  }

  const handleReview = async (id: string, status: 'approved' | 'rejected', type: 'child' | 'staff') => {
      try {
          if (type === 'child') await updateLeaveRequestStatus(id, status)
          else await updateTeacherStatus(id, status)
          alert('Status aktualisiert!')
      } catch (e: any) {
          alert(e.message)
      }
  }

  if (loading) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-7xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-10">
        <div>
          <Heading size="xl" className="text-gray-900 tracking-tight">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-gray-500 mt-1">Verwalten Sie Urlaubsanträge und Krankmeldungen von Kindern und Personal.</p>
        </div>
      </div>

      <div className="mb-10 flex gap-2">
            <button 
                onClick={() => setActiveTab('children')}
                className={`px-8 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all duration-300 ${
                    activeTab === 'children' ? 'bg-black text-white border-black shadow-lg' : 'bg-white text-gray-400 border-black/5 hover:border-black/10'
                }`}
            >
                Kinder
            </button>
            <button 
                onClick={() => setActiveTab('staff')}
                className={`px-8 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all duration-300 ${
                    activeTab === 'staff' ? 'bg-black text-white border-black shadow-lg' : 'bg-white text-gray-400 border-black/5 hover:border-black/10'
                }`}
            >
                Personal
            </button>
      </div>

      <div className="grid grid-cols-1 gap-4">
            {activeTab === 'children' ? (
                leaveRequests.length === 0 ? <p className="text-center py-20 text-gray-400 font-bold uppercase tracking-widest opacity-20 text-4xl">Leer</p> :
                leaveRequests.map(req => (
                    <IOSCard key={req.id} className="p-0 overflow-hidden border-black/5 group">
                        <div className="p-6 md:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6">
                            <div className="flex-1">
                                <div className="flex items-center gap-3 mb-2">
                                    <h3 className="text-lg font-black text-gray-900">{getChildName(req.child_id)}</h3>
                                    <span className={`px-2 py-0.5 text-[9px] font-black uppercase rounded-md border ${
                                        req.status === 'approved' ? 'bg-green-50 text-green-600 border-green-100' : 
                                        req.status === 'rejected' ? 'bg-red-50 text-red-600 border-red-100' :
                                        'bg-amber-50 text-amber-600 border-amber-100'
                                    }`}>
                                        {req.status}
                                    </span>
                                </div>
                                <p className="text-[10px] font-black text-black/30 uppercase tracking-widest">
                                    📅 {new Date(req.start_date).toLocaleDateString()} - {new Date(req.end_date).toLocaleDateString()} | Typ: {req.leave_type}
                                </p>
                            </div>
                            {req.status === 'pending' && (
                                <div className="flex gap-2">
                                    <IOSButton onClick={() => handleReview(req.id, 'approved', 'child')} className="px-6 py-2 text-[10px] font-black uppercase tracking-widest bg-black text-white border-none">Genehmigen</IOSButton>
                                    <IOSButton onClick={() => handleReview(req.id, 'rejected', 'child')} variant="secondary" className="px-6 py-2 text-[10px] font-black uppercase tracking-widest border-black/5">Ablehnen</IOSButton>
                                </div>
                            )}
                        </div>
                    </IOSCard>
                ))
            ) : (
                teacherRequests.length === 0 ? <p className="text-center py-20 text-gray-400 font-bold uppercase tracking-widest opacity-20 text-4xl">Leer</p> :
                teacherRequests.map(req => (
                    <IOSCard key={req.id} className="p-0 overflow-hidden border-black/5 group">
                        <div className="p-6 md:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6">
                            <div className="flex-1">
                                <div className="flex items-center gap-3 mb-2">
                                    <h3 className="text-lg font-black text-gray-900">{getStaffName(req.teacher_id)}</h3>
                                    <span className={`px-2 py-0.5 text-[9px] font-black uppercase rounded-md border ${
                                        req.status === 'approved' ? 'bg-green-50 text-green-600 border-green-100' : 
                                        req.status === 'rejected' ? 'bg-red-50 text-red-600 border-red-100' :
                                        'bg-amber-50 text-amber-600 border-amber-100'
                                    }`}>
                                        {req.status}
                                    </span>
                                </div>
                                <p className="text-[10px] font-black text-black/30 uppercase tracking-widest">
                                    📅 {new Date(req.start_date).toLocaleDateString()} - {new Date(req.end_date).toLocaleDateString()} | Typ: {req.leave_type}
                                </p>
                            </div>
                            {req.status === 'pending' && (
                                <div className="flex gap-2">
                                    <IOSButton onClick={() => handleReview(req.id, 'approved', 'staff')} className="px-6 py-2 text-[10px] font-black uppercase tracking-widest bg-black text-white border-none">Genehmigen</IOSButton>
                                    <IOSButton onClick={() => handleReview(req.id, 'rejected', 'staff')} variant="secondary" className="px-6 py-2 text-[10px] font-black uppercase tracking-widest border-black/5">Ablehnen</IOSButton>
                                </div>
                            )}
                        </div>
                    </IOSCard>
                ))
            )}
      </div>
    </div>
  )
}
