// next-app/src/components/ui/IOSInput.tsx
import React from 'react'
import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

interface IOSInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string
  error?: string
}

export function IOSInput({ label, error, className, id, ...props }: IOSInputProps) {
  return (
    <div className="w-full">
      {label && (
        <label htmlFor={id} className="block text-[14px] font-semibold text-[#1d1d1f] mb-2 tracking-[0.3px]">
          {label}
        </label>
      )}
      <div className="relative">
        <input
          id={id}
          className={cn(
            'w-full px-4 py-3 bg-white/90 backdrop-blur-[10px] border border-black/10 rounded-[12px] text-[#1d1d1f] text-base transition-all duration-200 outline-none appearance-none placeholder:text-black/40',
            'focus:bg-white focus:border-[#667eea]/50 focus:shadow-[0_0_0_4px_rgba(102,126,234,0.2)] focus:scale-[1.01]',
            'disabled:opacity-50 disabled:cursor-not-allowed',
            error && 'border-[#ff3b30]/60 bg-[#ff3b30]/10',
            className
          )}
          {...props}
        />
        {error && (
          <div className="mt-[6px] text-[13px] text-[#ff3b30] font-medium">
            {error}
          </div>
        )}
      </div>
    </div>
  )
}

// components/ui/IOSInput.vue
<template>
  <div class="ios-input-wrapper">
    <label v-if="label" :for="id" class="ios-input-label">
      {{ label }}
    </label>
    <div class="ios-input-container">
      <input
        :id="id"
        :type="type"
        :value="modelValue"
        :placeholder="placeholder"
        :required="required"
        :disabled="disabled"
        :class="['ios-input', error ? 'ios-input-error' : '', customClass]"
        @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)"
        @focus="$emit('focus', $event)"
        @blur="$emit('blur', $event)"
      />
      <div v-if="error" class="ios-input-error-message">{{ error }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  id?: string
  label?: string
  type?: string
  modelValue: string
  placeholder?: string
  required?: boolean
  disabled?: boolean
  error?: string
  customClass?: string
}

withDefaults(defineProps<Props>(), {
  id: undefined,
  label: undefined,
  type: 'text',
  placeholder: '',
  required: false,
  disabled: false,
  error: undefined,
  customClass: ''
})

defineEmits<{
  'update:modelValue': [value: string]
  focus: [event: FocusEvent]
  blur: [event: FocusEvent]
}>()
</script>

<style scoped>
.ios-input-wrapper {
  width: 100%;
}

.ios-input-label {
  display: block;
  font-size: 14px;
  font-weight: 600;
  color: #1d1d1f;
  margin-bottom: 8px;
  letter-spacing: 0.3px;
}

.ios-input-container {
  position: relative;
}

.ios-input {
  width: 100%;
  padding: 14px 16px;
  background: rgba(255, 255, 255, 0.9);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: 12px;
  color: #1d1d1f;
  font-size: 16px;
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  outline: none;
  -webkit-appearance: none;
}

.ios-input::placeholder {
  color: rgba(0, 0, 0, 0.4);
}

.ios-input:focus {
  background: rgba(255, 255, 255, 1);
  border-color: rgba(102, 126, 234, 0.5);
  box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.2);
  transform: scale(1.01);
}

.ios-input:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.ios-input-error {
  border-color: rgba(255, 59, 48, 0.6);
  background: rgba(255, 59, 48, 0.1);
}

.ios-input-error-message {
  margin-top: 6px;
  font-size: 13px;
  color: #ff3b30;
  font-weight: 500;
}

@media (max-width: 768px) {
  .ios-input {
    padding: 12px 14px;
    font-size: 16px; /* Prevents zoom on iOS */
    border-radius: 10px;
  }
  
  .ios-input-label {
    font-size: 13px;
  }
}
</style>
