// pages/admin/lunch/menus/[id].vue
<template>
  <div>
    <div class="mb-6">
      <NuxtLink
        to="/admin/lunch/menus"
        class="link-fiori mb-4 inline-block"
      >
        ← Back to Lunch Menus
      </NuxtLink>
      <Heading size="xl" class="text-white drop-shadow">Mittagessen-Menü</Heading>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

      <div v-else-if="!menu" class="empty-state-fiori">
        <div class="empty-state-fiori-icon">🍽️</div>
        <p class="empty-state-fiori-title">Menü nicht gefunden</p>
      </div>

    <div v-else class="card-fiori card-orange rounded-lg shadow p-6 max-w-3xl">
      <div class="space-y-4">
        <div>
          <h3 class="form-label-fiori text-fiori-blue-600">Gerichtname</h3>
          <p class="mt-1 text-lg text-fiori-gray-900 font-semibold">{{ menu.meal_name }}</p>
        </div>

        <div>
          <h3 class="form-label-fiori text-fiori-blue-600">Datum</h3>
          <p class="mt-1 text-fiori-gray-900">{{ formatDate(menu.date) }}</p>
        </div>

        <div v-if="menu.description">
          <h3 class="form-label-fiori text-fiori-blue-600">Beschreibung</h3>
          <p class="mt-1 text-fiori-gray-900">{{ menu.description }}</p>
        </div>

        <div v-if="menu.allergens && menu.allergens.length > 0">
          <h3 class="form-label-fiori text-fiori-blue-600">Allergene</h3>
          <div class="mt-1 flex flex-wrap gap-2">
            <span
              v-for="allergen in menu.allergens"
              :key="allergen"
              class="badge-fiori badge-fiori-warning"
            >
              {{ allergen }}
            </span>
          </div>
        </div>

        <div v-if="menu.nutritional_info && Object.keys(menu.nutritional_info).length > 0">
          <h3 class="form-label-fiori text-fiori-blue-600">Nährwertinformationen</h3>
          <div class="mt-1 grid grid-cols-2 gap-4">
            <div v-for="(value, key) in menu.nutritional_info" :key="key">
              <span class="text-sm text-fiori-gray-900 capitalize font-medium">{{ key }}:</span>
              <span class="ml-2 text-fiori-gray-700">{{ value }}</span>
            </div>
          </div>
        </div>

        <div v-if="menu.photo_url" class="mt-4">
          <h3 class="form-label-fiori text-fiori-blue-600 mb-2">Foto</h3>
          <img
            :src="menu.photo_url"
            :alt="menu.meal_name"
            class="w-full max-w-md h-64 object-cover rounded-md"
          />
        </div>

        <div class="pt-4 border-t border-fiori-gray-200 flex justify-between items-center mb-4">
          <h3 class="form-label-fiori text-fiori-blue-600">Bestellungen für dieses Menü</h3>
          <NuxtLink
            :to="`/admin/lunch/menus/${menu.id}/edit`"
            class="ios-button ios-button-primary inline-flex items-center gap-2"
          >
            ✏️ Menü bearbeiten
          </NuxtLink>
        </div>
        <div>
          <div v-if="orders.length === 0" class="text-fiori-gray-600 text-sm">
            Noch keine Bestellungen für dieses Menü.
          </div>
          <div v-else class="space-y-2">
            <div
              v-for="order in orders"
              :key="order.id"
              class="p-3 bg-fiori-gray-50 rounded-md flex items-center justify-between"
            >
              <div>
                <p class="font-medium text-sm text-fiori-gray-900">{{ getChildName(order.child_id) }}</p>
                <p class="text-xs text-fiori-gray-700">
                  Status: 
                  <span
                    :class="[
                      'badge-fiori ml-1',
                      order.status === 'confirmed' ? 'badge-fiori-success' :
                      order.status === 'cancelled' ? 'badge-fiori-error' :
                      'badge-fiori-neutral'
                    ]"
                  >
                    {{ order.status === 'confirmed' ? 'Bestätigt' : order.status === 'cancelled' ? 'Storniert' : order.status }}
                  </span>
                </p>
                <p v-if="order.special_requests" class="text-xs text-fiori-gray-700 mt-1">
                  Besondere Wünsche: {{ order.special_requests }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useRoute } from 'vue-router'
import { useSupabaseClient } from '#imports'
import { useLunchStore } from '~/stores/lunch'
import { useChildrenStore } from '~/stores/children'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: ['admin', 'kitchen']
})

const route = useRoute()
const supabase = useSupabaseClient()
const lunchStore = useLunchStore()
const childrenStore = useChildrenStore()

const loading = ref(true)
const error = ref('')
const menu = ref<any>(null)
const orders = ref<any[]>([])

const { children } = storeToRefs(childrenStore)

onMounted(async () => {
  try {
    const menuId = route.params.id as string
    
    // Fetch menu
    const { data: menuData, error: menuError } = await supabase
      .from('lunch_menus')
      .select('*')
      .eq('id', menuId)
      .single()

    if (menuError) throw menuError
    if (!menuData) {
      error.value = 'Menu not found'
      return
    }

    menu.value = menuData

    // Fetch orders for this menu
    await lunchStore.fetchOrders(undefined, menuId)
    orders.value = lunchStore.orders.filter(o => o.menu_id === menuId)

    // Fetch children for names
    await childrenStore.fetchChildren()
  } catch (e: any) {
    error.value = e.message || 'Failed to load menu'
  } finally {
    loading.value = false
  }
})

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}

const getChildName = (childId: string) => {
  const child = children.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}
</script>

// src/app/teacher/observations/[id]/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'teacher.observations.id'

import React, { useEffect, useState, use } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { useObservationsStore } from '@/stores/observations'
import { useChildrenStore } from '@/stores/children'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'
import { ObservationForm } from '@/components/forms/ObservationForm'

interface PageProps {
  params: Promise<{ id: string }>
}

export default function TeacherObservationDetailPage({ params }: PageProps) {
  const { t } = useI18n()

  const { id } = use(params)
  const router = useRouter()
  const searchParams = useSearchParams()
  const { observations, loading, error, fetchObservations, updateObservation, deleteObservation } = useObservationsStore()
  const { children, fetchChildren } = useChildrenStore()

  const [isEditing, setIsEditing] = useState(searchParams.get('edit') === 'true')
  const [submitting, setSubmitting] = useState(false)

  useEffect(() => {
    fetchChildren()
    fetchObservations()
  }, [fetchChildren, fetchObservations])

  const observation = observations.find(o => o.id === id)

  const getChildName = (childId: string) => {
    const child = (children || []).find((c: any) => c.id === childId)
    return child ? `${child.first_name} ${child.last_name}` : childId
  }

  const formatDate = (d: string) => {
    return new Date(d).toLocaleDateString('de-DE', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  const handleUpdate = async (data: any) => {
    setSubmitting(true)
    try {
      await updateObservation(id, data)
      setIsEditing(false)
      // Refresh observations is handled by the store (ideally)
    } catch (e: any) {
      console.error('Error updating observation:', e)
    } finally {
      setSubmitting(false)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Beobachtung wirklich löschen?')) return
    try {
      await deleteObservation(id)
      router.push('/teacher/observations')
    } catch (e: any) {
      console.error('Error deleting observation:', e)
    }
  }

  if (loading && !observation) {
    return (
      <div className="flex justify-center py-24">
        <LoadingSpinner />
      </div>
    )
  }

  if (error) {
    return (
      <div className="max-w-2xl mx-auto py-10 px-4">
        <ErrorAlert message={error.message || 'Fehler beim Laden der Beobachtung'} />
        <Link href="/teacher/observations" className="mt-4 inline-block text-[#667eea] font-medium">
          ← Zurück zur Übersicht
        </Link>
      </div>
    )
  }

  if (!observation) {
    return (
      <div className="max-w-2xl mx-auto py-24 px-4 text-center">
        <div className="text-5xl mb-4">🔍</div>
        <Heading size="lg">Beobachtung nicht gefunden</Heading>
        <Link href="/teacher/observations" className="mt-4 inline-block text-[#667eea] font-medium font-fiori">
          ← Zurück zur Übersicht
        </Link>
      </div>
    )
  }

  return (
    <div className="max-w-3xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <Link
            href="/teacher/observations"
            className="text-sm font-semibold text-[#667eea] mb-2 inline-flex items-center gap-1 hover:translate-x-[-4px] transition-transform"
          >
            ← Zurück zu Beobachtungen
          </Link>
          <Heading size="xl" className="text-slate-900 dark:text-slate-50">{t(pT(ROUTE))}</Heading>
        </div>
        {!isEditing && (
          <div className="flex items-center gap-2">
            <IOSButton
              variant="secondary"
              onClick={() => setIsEditing(true)}
              className="px-4 py-2 text-sm flex items-center gap-2"
            >
              ✏️ Bearbeiten
            </IOSButton>
            <IOSButton
              variant="secondary"
              onClick={handleDelete}
              className="px-4 py-2 text-sm text-red-500 hover:text-red-600 flex items-center gap-2"
            >
              🗑️ Löschen
            </IOSButton>
          </div>
        )}
      </div>

      <IOSCard className={isEditing ? 'p-6' : 'p-0 overflow-hidden'}>
        {isEditing ? (
          <ObservationForm
            initialData={observation}
            onSubmit={handleUpdate}
            onCancel={() => setIsEditing(false)}
            loading={submitting}
          />
        ) : (
          <div className="divide-y divide-black/5">
            <div className="p-6">
              <h3 className="text-xs font-bold text-black/40 uppercase tracking-wider mb-2">Kind</h3>
              <p className="text-lg font-bold text-slate-900 dark:text-slate-50">{getChildName(observation.child_id)}</p>
            </div>

            <div className="p-6">
              <h3 className="text-xs font-bold text-black/40 uppercase tracking-wider mb-2">Datum</h3>
              <p className="text-base font-semibold text-slate-800 dark:text-slate-100">{formatDate(observation.observation_date)}</p>
            </div>

            {observation.development_area && (
              <div className="p-6">
                <h3 className="text-xs font-bold text-black/40 uppercase tracking-wider mb-2">Entwicklungsbereich</h3>
                <span className="inline-flex px-3 py-1 bg-blue-50 text-blue-700 text-xs font-bold rounded-full border border-blue-100">
                  {observation.development_area}
                </span>
              </div>
            )}

            {observation.context && (
              <div className="p-6">
                <h3 className="text-xs font-bold text-black/40 uppercase tracking-wider mb-2">Kontext</h3>
                <p className="text-base text-slate-700 dark:text-slate-200 italic font-medium">"{observation.context}"</p>
              </div>
            )}

            <div className="p-6">
              <h3 className="text-xs font-bold text-black/40 uppercase tracking-wider mb-2">Beschreibung</h3>
              <p className="text-base text-slate-800 dark:text-slate-100 leading-relaxed whitespace-pre-wrap font-medium">
                {observation.description}
              </p>
            </div>

            {observation.photos && observation.photos.length > 0 && (
              <div className="p-6">
                <h3 className="text-xs font-bold text-black/40 uppercase tracking-wider mb-3">Fotos</h3>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                  {observation.photos.map((photo: string, index: number) => (
                    <div key={index} className="aspect-square rounded-2xl overflow-hidden border border-black/5">
                      <img
                        src={photo}
                        alt={`Observation photo ${index + 1}`}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </IOSCard>
    </div>
  )
}
