// src/app/admin/daily-routines/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'
import { sT } from '@/i18n/sT'

const ROUTE = 'admin.daily-routines'

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { useDailyRoutinesStore, DailyRoutine } from '@/stores/dailyRoutines'
import { useGroupsStore } from '@/stores/groups'
import { Heading } from '@/components/ui/Heading'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

export default function AdminDailyRoutinesPage() {
  const { t } = useI18n()

  const { dailyRoutines, loading, error, fetchDailyRoutines } = useDailyRoutinesStore()
  const { groups, fetchGroups } = useGroupsStore()
  
  const [selectedGroup, setSelectedGroup] = useState('')

  useEffect(() => {
    fetchDailyRoutines(selectedGroup || undefined)
    fetchGroups()
  }, [selectedGroup, fetchDailyRoutines, fetchGroups])

  if (loading && dailyRoutines.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-7xl mx-auto pb-20">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
        <div>
          <h1 className="text-4xl font-black text-slate-900 tracking-tight mb-2">
            {t(pT(ROUTE))}
          </h1>
          <p className="text-lg text-slate-500 font-medium max-w-2xl">{t(sT('dailyRoutinesListSubtitle'))}</p>
        </div>
        <div className="flex gap-3">
          <Link href="/admin/daily-routines/new" className="px-6 py-3 bg-indigo-600 text-white rounded-2xl font-bold text-sm shadow-xl shadow-indigo-100 hover:bg-indigo-700 hover:-translate-y-1 transition-all">
            {t(sT('createRoutine'))}
          </Link>
        </div>
      </div>

      <div className="mb-10">
        <div className="relative inline-block w-full md:w-64">
            <select 
                value={selectedGroup} 
                onChange={(e) => setSelectedGroup(e.target.value)}
                className="w-full pl-6 pr-12 py-3 bg-white border border-slate-100 rounded-2xl text-[11px] font-black text-slate-900 uppercase tracking-widest shadow-sm focus:ring-2 focus:ring-indigo-100 outline-none transition-all appearance-none cursor-pointer"
            >
                <option value="">{t(sT('allGroups'))}</option>
                {groups.map(g => (
                    <option key={g.id} value={g.id}>{g.name}</option>
                ))}
            </select>
            <div className="absolute right-5 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">
                ▼
            </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {dailyRoutines.map(routine => (
                <IOSCard key={routine.id} className="p-0 overflow-hidden group hover:border-indigo-100 transition-all duration-500">
                    <div className="p-8 flex items-center gap-8">
                        <div className="shrink-0 w-24 flex flex-col items-center justify-center p-4 bg-indigo-50 rounded-2xl border border-indigo-100 group-hover:bg-indigo-600 group-hover:text-white transition-all duration-500 shadow-sm">
                            <span className="text-xs font-black uppercase tracking-tight opacity-60 mb-1">Start</span>
                            <span className="text-xl font-black">{routine.start_time}</span>
                        </div>
                        
                        <div className="flex-1 min-w-0">
                            <h3 className="text-xl font-black text-slate-900 mb-1 group-hover:text-indigo-600 transition-colors tracking-tight truncate">{routine.routine_name}</h3>
                            <div className="flex flex-wrap items-center gap-4">
                                <span className="flex items-center gap-2 text-[10px] font-black text-slate-400 uppercase tracking-widest">
                                    <span className="w-1.5 h-1.5 rounded-full bg-slate-300" />
                                    {routine.location || 'Classroom'}
                                </span>
                                <span className="px-3 py-1 bg-slate-100 text-slate-500 text-[9px] font-black uppercase tracking-widest rounded-full">
                                    {routine.day_of_week === null ? 'Every Day' : `Day ${routine.day_of_week}`}
                                </span>
                            </div>
                        </div>

                        <div className="shrink-0">
                             <Link href={`/admin/daily-routines/edit/${routine.id}`} className="w-12 h-12 bg-slate-50 border border-slate-100 rounded-xl flex items-center justify-center text-sm shadow-sm group-hover:bg-slate-900 group-hover:text-white transition-all">
                                ✏️
                             </Link>
                        </div>
                    </div>
                </IOSCard>
            ))}
      </div>

      {dailyRoutines.length === 0 && !loading && (
        <IOSCard className="p-24 text-center border-dashed border-2 border-slate-200 bg-transparent shadow-none">
            <div className="text-6xl opacity-10 mb-6">📅</div>
            <p className="text-slate-500 font-bold text-xl">{t(sT('dailyRoutinesEmptyTitle'))}</p>
            <p className="text-slate-400 mt-2 font-medium">{t(sT('dailyRoutinesEmptyHint'))}</p>
        </IOSCard>
      )}
    </div>
  )
}

// pages/admin/daily-routines/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <div>
        <Heading size="xl">Tagesablauf</Heading>
        <p class="text-sm text-gray-600 mt-1">Tägliche Routinen und Abläufe für die Gruppen</p>
      </div>
      <NuxtLink
        to="/admin/daily-routines/new"
        class="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors shadow-sm"
      >
        <span>➕</span>
        <span>Neue Routine</span>
      </NuxtLink>
    </div>

    <div class="mb-4">
      <select
        v-model="selectedGroupId"
        class="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        @change="fetchRoutines"
      >
        <option value="">Alle Gruppen</option>
        <option v-for="group in groups" :key="group.id" :value="group.id">
          {{ group.name }}
        </option>
      </select>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error.message || 'Error loading daily routines'" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="routines.length === 0" class="p-8 text-center text-gray-500">
        No daily routines found.
      </div>

      <div v-else class="divide-y divide-gray-200">
        <div
          v-for="routine in routines"
          :key="routine.id"
          class="p-6 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="flex items-center gap-3 mb-2">
                <h3 class="text-lg font-medium text-gray-900">{{ routine.routine_name }}</h3>
                <span class="text-sm text-gray-500">{{ getGroupName(routine.group_id) }}</span>
              </div>
              <p class="text-sm text-gray-600 mb-2">
                {{ formatTime(routine.start_time) }}
                <span v-if="routine.end_time"> - {{ formatTime(routine.end_time) }}</span>
              </p>
              <p v-if="routine.day_of_week !== null" class="text-sm text-gray-500 mb-2">
                {{ getDayName(routine.day_of_week) }}
              </p>
              <p v-else class="text-sm text-gray-500 mb-2">Every day</p>
              <p v-if="routine.description" class="text-gray-700 mb-2">{{ routine.description }}</p>
              <p v-if="routine.location" class="text-sm text-gray-500">📍 {{ routine.location }}</p>
              <div v-if="!routine.is_active" class="mt-2">
                <span class="px-2 py-1 bg-gray-100 text-gray-600 text-xs rounded">Inaktiv</span>
              </div>
            </div>
            <div class="flex items-center gap-2">
              <NuxtLink
                :to="`/admin/daily-routines/${routine.id}?edit=true`"
                class="inline-flex items-center gap-1 px-3 py-1.5 bg-yellow-50 text-yellow-700 rounded-md hover:bg-yellow-100 transition-colors"
              >
                <span>✏️</span>
                <span>Bearbeiten</span>
              </NuxtLink>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useDailyRoutinesStore } from '~/stores/dailyRoutines'
import { useGroupsStore } from '~/stores/groups'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const dailyRoutinesStore = useDailyRoutinesStore()
const groupsStore = useGroupsStore()

const selectedGroupId = ref('')
const { dailyRoutines: routines, loading, error } = storeToRefs(dailyRoutinesStore)
const { groups } = storeToRefs(groupsStore)

onMounted(async () => {
  await Promise.all([
    dailyRoutinesStore.fetchDailyRoutines(),
    groupsStore.fetchGroups()
  ])
})

const fetchRoutines = async () => {
  await dailyRoutinesStore.fetchDailyRoutines(selectedGroupId.value || undefined)
}

const getGroupName = (groupId: string) => {
  const group = groups.value.find(g => g.id === groupId)
  return group ? group.name : groupId
}

const formatTime = (time: string) => {
  return time.substring(0, 5) // HH:MM format
}

const getDayName = (day: number) => {
  const days = ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag']
  return days[day] || 'Unbekannt'
}
</script>
