// src/app/dashboard/page.tsx
'use client'

import { useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'

export default function DashboardRedirect() {
  const router = useRouter()
  const { profile, loading, user } = useAuth()

  useEffect(() => {
    if (loading) return
    
    // If no user is logged in, useAuth middleware might catch it, but just in case:
    if (!user) {
      router.push('/login')
      return
    }

    const role = profile?.role
    if (role === 'admin') router.push('/admin/dashboard')
    else if (role === 'teacher') router.push('/teacher/dashboard')
    else if (role === 'parent') router.push('/parent/dashboard')
    else if (role === 'kitchen') router.push('/kitchen/dashboard')
    else if (role === 'support') router.push('/support/dashboard')
    else {
      // Fallback if role is missing or not fully loaded
      console.warn('No specific role found, staying on /dashboard')
    }
  }, [profile, loading, user, router])

  return (
    <div className="flex h-screen items-center justify-center">
      <div className="text-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
        <p className="text-gray-500">Lade Dashboard...</p>
      </div>
    </div>
  )
}

// pages/dashboard.vue
<template>
  <div class="flex items-center justify-center min-h-screen">
    <div class="text-center">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
      <p class="text-gray-600">Redirecting...</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useSupabaseClient } from '#imports'
import { useAuthStore } from '~/stores/auth'

const router = useRouter()
const supabase = useSupabaseClient()
const authStore = useAuthStore()

onMounted(async () => {
  try {
    // Check if user is authenticated
    const { data: { session } } = await supabase.auth.getSession()
    
    if (!session?.user) {
      await router.push('/login')
      return
    }

    // Set user and fetch profile
    authStore.setUser(session.user)
    await authStore.fetchProfile()

    // Redirect based on role
    const role = authStore.userRole
    
    if (role === 'admin') {
      await router.push('/admin/dashboard')
    } else if (role === 'teacher') {
      await router.push('/teacher/dashboard')
    } else if (role === 'parent') {
      await router.push('/parent/dashboard')
    } else if (role === 'kitchen') {
      await router.push('/kitchen/dashboard')
    } else {
      await router.push('/')
    }
  } catch (error) {
    console.error('Dashboard redirect error:', error)
    await router.push('/login')
  }
})
</script>
