// pages/admin/fees/[id].vue
<template>
  <div>
    <div class="mb-6">
      <NuxtLink
        to="/admin/fees"
        class="text-gray-600 hover:text-gray-900 mb-4 inline-block"
      >
        ← Back to Fees
      </NuxtLink>
      <Heading size="xl">Fee Details</Heading>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else-if="fee" class="space-y-6">
      <div class="bg-white rounded-lg shadow p-6">
        <div class="grid grid-cols-2 gap-4 mb-4">
          <div>
            <label class="block text-sm font-medium text-gray-600">Child</label>
            <p class="mt-1 text-gray-900">{{ getChildName(fee.child_id) }}</p>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-600">Period</label>
            <p class="mt-1 text-gray-900">{{ getMonthName(fee.month) }} {{ fee.year }}</p>
          </div>
        </div>

        <div class="grid grid-cols-2 gap-4 mb-4">
          <div>
            <label class="block text-sm font-medium text-gray-600">Fee Type</label>
            <p class="mt-1 text-gray-900">{{ formatFeeType(fee.fee_type) }}</p>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-600">Amount</label>
            <p class="mt-1 text-lg font-bold text-gray-900">€{{ fee.amount.toFixed(2) }}</p>
          </div>
        </div>

        <div class="grid grid-cols-2 gap-4 mb-4">
          <div>
            <label class="block text-sm font-medium text-gray-600">Due Date</label>
            <p class="mt-1 text-gray-900">{{ formatDate(fee.due_date) }}</p>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-600">Status</label>
            <span
              :class="[
                'inline-block mt-1 px-2 py-1 text-xs font-medium rounded-full',
                fee.status === 'paid' ? 'bg-green-100 text-green-800' :
                fee.status === 'overdue' ? 'bg-red-100 text-red-800' :
                fee.status === 'waived' ? 'bg-gray-100 text-gray-800' :
                'bg-yellow-100 text-yellow-800'
              ]"
            >
              {{ fee.status }}
            </span>
          </div>
        </div>

        <div v-if="fee.notes" class="mb-4">
          <label class="block text-sm font-medium text-gray-600">Notes</label>
          <p class="mt-1 text-gray-900">{{ fee.notes }}</p>
        </div>

        <div v-if="fee.paid_at" class="mb-4">
          <label class="block text-sm font-medium text-gray-600">Paid At</label>
          <p class="mt-1 text-gray-900">{{ formatDateTime(fee.paid_at) }}</p>
        </div>

        <div v-if="fee.payment_method" class="mb-4">
          <label class="block text-sm font-medium text-gray-600">Payment Method</label>
          <p class="mt-1 text-gray-900">{{ fee.payment_method }}</p>
        </div>

        <div class="pt-4 border-t">
          <h3 class="text-sm font-medium text-gray-700 mb-2">Payment History</h3>
          <div v-if="payments.length === 0" class="text-sm text-gray-500">
            No payments recorded yet.
          </div>
          <div v-else class="space-y-2">
            <div
              v-for="payment in payments"
              :key="payment.id"
              class="p-3 bg-gray-50 rounded-md"
            >
              <div class="flex justify-between items-center">
                <div>
                  <p class="text-sm font-medium text-gray-900">€{{ payment.amount.toFixed(2) }}</p>
                  <p class="text-xs text-gray-500">{{ formatDate(payment.payment_date) }}</p>
                  <p v-if="payment.payment_method" class="text-xs text-gray-500">
                    Method: {{ payment.payment_method }}
                  </p>
                </div>
                <p v-if="payment.transaction_id" class="text-xs text-gray-500">
                  Ref: {{ payment.transaction_id }}
                </p>
              </div>
            </div>
          </div>
        </div>

        <div v-if="fee.status !== 'paid' && fee.status !== 'waived'" class="pt-4 border-t">
          <button
            @click="editFee"
            class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors mr-2"
          >
            Edit
          </button>
          <button
            @click="waiveFee"
            class="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 transition-colors"
          >
            Waive Fee
          </button>
        </div>
      </div>

      <div v-if="showEditForm" class="bg-white rounded-lg shadow p-6">
        <Heading size="md" class="mb-4">Edit Fee</Heading>
        <form @submit.prevent="handleUpdate" class="space-y-4">
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label for="amount" class="block text-sm font-medium text-gray-700 mb-2">
                Amount (€) <span class="text-red-500">*</span>
              </label>
              <input
                id="amount"
                v-model.number="editForm.amount"
                type="number"
                step="0.01"
                required
                min="0"
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label for="due_date" class="block text-sm font-medium text-gray-700 mb-2">
                Due Date <span class="text-red-500">*</span>
              </label>
              <input
                id="due_date"
                v-model="editForm.due_date"
                type="date"
                required
                class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>
          <div>
            <label for="status" class="block text-sm font-medium text-gray-700 mb-2">
              Status
            </label>
            <select
              id="status"
              v-model="editForm.status"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
            >
              <option value="pending">Pending</option>
              <option value="paid">Paid</option>
              <option value="overdue">Overdue</option>
              <option value="waived">Waived</option>
            </select>
          </div>
          <div>
            <label for="notes" class="block text-sm font-medium text-gray-700 mb-2">
              Notes
            </label>
            <textarea
              id="notes"
              v-model="editForm.notes"
              rows="3"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <div class="flex gap-3 justify-end">
            <button
              type="button"
              @click="showEditForm = false"
              class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="updating"
              class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50"
            >
              {{ updating ? 'Updating...' : 'Update Fee' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useMonthlyFeesStore } from '~/stores/monthlyFees'
import { useChildrenStore } from '~/stores/children'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const route = useRoute()
const router = useRouter()
const monthlyFeesStore = useMonthlyFeesStore()
const childrenStore = useChildrenStore()

const feeId = route.params.id as string
const loading = ref(true)
const error = ref('')
const fee = ref<any>(null)
const payments = ref<any[]>([])
const showEditForm = ref(false)
const updating = ref(false)

const editForm = ref({
  amount: 0,
  due_date: '',
  status: 'pending',
  notes: ''
})

onMounted(async () => {
  try {
    await Promise.all([
      fetchFee(),
      childrenStore.fetchChildren()
    ])
  } catch (e: any) {
    error.value = e.message || 'Failed to load fee'
  } finally {
    loading.value = false
  }
})

const fetchFee = async () => {
  try {
    await monthlyFeesStore.fetchFees()
    const found = monthlyFeesStore.fees.find(f => f.id === feeId)
    if (!found) {
      error.value = 'Fee not found'
      return
    }
    fee.value = found
    editForm.value = {
      amount: found.amount,
      due_date: found.due_date,
      status: found.status,
      notes: found.notes || ''
    }

    await monthlyFeesStore.fetchPayments(feeId)
    payments.value = monthlyFeesStore.payments
  } catch (e: any) {
    error.value = e.message || 'Failed to load fee'
  }
}

const getChildName = (childId: string) => {
  const child = childrenStore.children.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}

const getMonthName = (month: number) => {
  const date = new Date(2000, month - 1, 1)
  return date.toLocaleString('default', { month: 'long' })
}

const formatFeeType = (type: string) => {
  const types: Record<string, string> = {
    tuition: 'Tuition',
    lunch: 'Lunch',
    activities: 'Activities',
    other: 'Other'
  }
  return types[type] || type
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}

const formatDateTime = (date: string) => {
  return new Date(date).toLocaleString()
}

const editFee = () => {
  showEditForm.value = true
}

const handleUpdate = async () => {
  updating.value = true
  try {
    await monthlyFeesStore.updateFee(feeId, editForm.value)
    alert('Fee updated successfully!')
    showEditForm.value = false
    await fetchFee()
  } catch (e: any) {
    alert(e.message || 'Failed to update fee')
  } finally {
    updating.value = false
  }
}

const waiveFee = async () => {
  if (!confirm('Are you sure you want to waive this fee?')) return

  try {
    await monthlyFeesStore.updateFee(feeId, { status: 'waived' })
    alert('Fee waived successfully!')
    await fetchFee()
  } catch (e: any) {
    alert(e.message || 'Failed to waive fee')
  }
}
</script>

// src/app/admin/hr/payroll/[id]/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.hr.payroll.id'

import React, { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { IOSCard } from '@/components/ui/IOSCard'
import { Heading } from '@/components/ui/Heading'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { IOSButton } from '@/components/ui/IOSButton'
import { usePayrollStore, type StaffPayroll } from '@/stores/payroll'
import { useStaffStore } from '@/stores/staff'
import { PayrollForm } from '@/components/forms/PayrollForm'

export default function AdminPayrollDetailsPage() {
  const { t } = useI18n()

  const router = useRouter()
  const params = useParams<{ id: string }>()
  const payrollId = params?.id

  const payrollStore = usePayrollStore()
  const { staff, fetchStaff } = useStaffStore()

  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [payrollRecord, setPayrollRecord] = useState<StaffPayroll | null>(null)
  const [showEditForm, setShowEditForm] = useState(false)

  const getStaffName = (staffId: string) => {
    const s = staff.find((st) => st.id === staffId)
    return s ? s.full_name : staffId
  }

  const getMonthName = (month: number) => {
    const date = new Date(2000, month - 1, 1)
    return date.toLocaleString('default', { month: 'long' })
  }

  useEffect(() => {
    const run = async () => {
      setLoading(true)
      setError('')
      try {
        await Promise.all([payrollStore.fetchPayroll(), fetchStaff()])
        if (!payrollId) throw new Error('Payroll record not found')
        const found = payrollStore.payroll.find((p) => p.id === payrollId) || null
        if (!found) {
          setError('Payroll record not found')
          setPayrollRecord(null)
          return
        }
        setPayrollRecord(found)
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : 'Failed to load payroll')
      } finally {
        setLoading(false)
      }
    }

    void run()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [payrollId])

  const refreshPayroll = async () => {
    await payrollStore.fetchPayroll()
    if (!payrollId) return
    const found = payrollStore.payroll.find((p) => p.id === payrollId) || null
    setPayrollRecord(found)
  }

  const handleUpdate = async (data: Partial<StaffPayroll>) => {
    if (!payrollId) return
    try {
      await payrollStore.updatePayroll(payrollId, data)
      alert('Payroll updated successfully!')
      setShowEditForm(false)
      await refreshPayroll()
    } catch (e: unknown) {
      alert(e instanceof Error ? e.message : 'Failed to update payroll')
    }
  }

  const markAsPaid = async () => {
    if (!payrollId) return
    if (!confirm('Mark this payroll as paid?')) return
    try {
      await payrollStore.markAsPaid(payrollId)
      await refreshPayroll()
      alert('Payroll marked as paid!')
    } catch (e: unknown) {
      alert(e instanceof Error ? e.message : 'Failed to mark as paid')
    }
  }

  return (
    <div className="max-w-5xl mx-auto">
      <div className="mb-6">
        <button
          type="button"
          onClick={() => router.push('/admin/hr/payroll')}
          className="text-gray-600 hover:text-gray-900 mb-4 inline-block"
        >
          ← Back to Payroll
        </button>
        <Heading size="xl">{t(pT(ROUTE))}</Heading>
      </div>

      {loading ? (
        <div className="flex justify-center py-12">
          <LoadingSpinner />
        </div>
      ) : error ? (
        <div className="mb-6">
          <ErrorAlert message={error} />
        </div>
      ) : payrollRecord ? (
        <div className="space-y-6">
          <IOSCard className="p-6">
            <div className="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label className="block text-sm font-medium text-gray-600">Staff Member</label>
                <p className="mt-1 text-gray-900">{getStaffName(payrollRecord.staff_id)}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-600">Period</label>
                <p className="mt-1 text-gray-900">
                  {getMonthName(payrollRecord.month)} {payrollRecord.year}
                </p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label className="block text-sm font-medium text-gray-600">Base Salary</label>
                <p className="mt-1 text-gray-900">€{payrollRecord.base_salary.toFixed(2)}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-600">Overtime Amount</label>
                <p className="mt-1 text-gray-900">€{payrollRecord.overtime_amount.toFixed(2)}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label className="block text-sm font-medium text-gray-600">Bonuses</label>
                <p className="mt-1 text-green-600">€{payrollRecord.bonuses.toFixed(2)}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-600">Deductions</label>
                <p className="mt-1 text-red-600">€{payrollRecord.deductions.toFixed(2)}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label className="block text-sm font-medium text-gray-600">Tax Amount</label>
                <p className="mt-1 text-gray-900">€{payrollRecord.tax_amount.toFixed(2)}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-600">Net Salary</label>
                <p className="mt-1 text-lg font-bold text-gray-900">
                  €{payrollRecord.net_salary.toFixed(2)}
                </p>
              </div>
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-600">Status</label>
              <span
                className={[
                  'inline-block mt-1 px-2 py-1 text-xs font-medium rounded-full',
                  payrollRecord.status === 'paid'
                    ? 'bg-green-100 text-green-800'
                    : payrollRecord.status === 'approved'
                      ? 'bg-blue-100 text-blue-800'
                      : 'bg-yellow-100 text-yellow-800',
                ].join(' ')}
              >
                {payrollRecord.status}
              </span>
            </div>

            {payrollRecord.notes && (
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-600">Notes</label>
                <p className="mt-1 text-gray-900">{payrollRecord.notes}</p>
              </div>
            )}

            {payrollRecord.status !== 'paid' && (
              <div className="pt-4 border-t flex gap-2">
                <IOSButton
                  onClick={() => setShowEditForm(true)}
                  variant="primary"
                  className="px-4 py-2"
                >
                  Edit
                </IOSButton>
                <IOSButton
                  onClick={() => void markAsPaid()}
                  variant="secondary"
                  className="px-4 py-2 bg-green-600 text-white border-none"
                >
                  Mark as Paid
                </IOSButton>
              </div>
            )}
          </IOSCard>

          {showEditForm && (
            <IOSCard className="p-6">
              <Heading size="md" className="mb-4">
                Edit Payroll
              </Heading>
              <PayrollForm
                staffId={payrollRecord.staff_id}
                initialData={payrollRecord}
                onSubmit={(data) => void handleUpdate(data)}
                onCancel={() => setShowEditForm(false)}
              />
            </IOSCard>
          )}
        </div>
      ) : (
        <IOSCard className="p-20 text-center bg-gray-50/30 border-black/5">
          <p className="text-gray-400 font-bold">No payroll record found.</p>
        </IOSCard>
      )}
    </div>
  )
}
