// src/app/admin/users/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'
import { sT } from '@/i18n/sT'

const ROUTE = 'admin.users'

import React, { useEffect, useState, useMemo } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'

export default function AdminUsersPage() {
  const { t } = useI18n()

  const router = useRouter()
  const supabase = createClient()
  
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [users, setUsers] = useState<any[]>([])
  const [selectedRole, setSelectedRole] = useState('')

  const roles = ['', 'admin', 'teacher', 'parent', 'kitchen', 'support']

  const fetchUsers = async () => {
    setLoading(true)
    setError(null)
    try {
      let query = supabase.from('profiles').select('*')
      if (selectedRole) {
        query = query.eq('role', selectedRole)
      }
      query = query.order('created_at', { ascending: false })
      
      const { data, error: err } = await query
      if (err) throw err
      setUsers(data || [])
    } catch (e: any) {
      setError(e.message || t(sT('errLoadUsers')))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchUsers()
  }, [selectedRole])

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('de-DE')
  }

  const getRoleBadgeColor = (role: string) => {
    const colors: Record<string, string> = {
      admin: 'bg-blue-50 text-blue-600 border-blue-100',
      teacher: 'bg-indigo-50 text-indigo-600 border-indigo-100',
      parent: 'bg-green-50 text-green-600 border-green-100',
      kitchen: 'bg-amber-50 text-amber-600 border-amber-100',
      support: 'bg-gray-50 text-gray-600 border-gray-100'
    }
    return colors[role] || 'bg-gray-50 text-gray-600 border-gray-100'
  }

  if (loading && users.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-7xl mx-auto pb-20">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
        <div>
          <h1 className="text-4xl font-black text-slate-900 tracking-tight mb-2">
            {t(pT(ROUTE))}
          </h1>
          <p className="text-lg text-slate-500 font-medium max-w-2xl">{t(sT('usersListSubtitle'))}</p>
        </div>
        <div className="flex gap-3">
          <Link href="/admin/users/new" className="px-6 py-3 bg-indigo-600 text-white rounded-2xl font-bold text-sm shadow-xl shadow-indigo-100 hover:bg-indigo-700 hover:-translate-y-1 transition-all">
            {t(sT('addNewUser'))}
          </Link>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="mb-10 flex flex-wrap gap-2">
        {roles.map(role => (
          <button
            key={role}
            onClick={() => setSelectedRole(role)}
            className={`px-6 py-2 rounded-2xl text-[11px] font-black uppercase tracking-[0.1em] border transition-all duration-300 ${
              selectedRole === role 
                ? 'bg-indigo-600 text-white border-indigo-600 shadow-lg shadow-indigo-100' 
                : 'bg-white text-slate-400 border-slate-100 hover:border-slate-200 hover:text-slate-600'
            }`}
          >
            {role ? t(`roles.${role}`) : t(sT('allUsers'))}
          </button>
        ))}
      </div>

      {error ? (
        <ErrorAlert message={error} />
      ) : users.length === 0 ? (
        <IOSCard className="p-24 text-center border-dashed border-2 border-slate-200 bg-transparent shadow-none">
          <div className="text-5xl opacity-20 mb-6">👤</div>
          <p className="text-slate-500 font-bold text-xl">
            {selectedRole
              ? t(sT('noUsersForRole')).replace('{{role}}', t(`roles.${selectedRole}`))
              : t(sT('noUsersSystem'))}
          </p>
          <p className="text-slate-400 mt-2 font-medium">{t(sT('tryAdjustFiltersUsers'))}</p>
        </IOSCard>
      ) : (
        <IOSCard className="p-0 overflow-hidden shadow-xl shadow-slate-200/40 border-slate-100">
            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-slate-50/50">
                            <th className="px-8 py-5 text-[11px] font-black text-slate-400 uppercase tracking-widest">User Profile</th>
                            <th className="px-8 py-5 text-[11px] font-black text-slate-400 uppercase tracking-widest">Role</th>
                            <th className="px-8 py-5 text-[11px] font-black text-slate-400 uppercase tracking-widest">Added On</th>
                            <th className="px-8 py-5 text-[11px] font-black text-slate-400 uppercase tracking-widest text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-50">
                        {users.map(u => (
                            <tr key={u.id} className="hover:bg-slate-50/50 transition-colors group">
                                <td className="px-8 py-6">
                                    <div className="flex items-center gap-4">
                                        <div className="w-12 h-12 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center text-lg font-black group-hover:bg-indigo-600 group-hover:text-white transition-all shadow-sm">
                                            {u.full_name?.charAt(0) || '?'}
                                        </div>
                                        <div>
                                            <span className="block font-black text-slate-900 text-lg tracking-tight group-hover:text-indigo-600 transition-colors">
                                                {u.full_name || 'Unbekannt'}
                                            </span>
                                            <span className="text-xs font-bold text-slate-400 uppercase tracking-tight">{u.email}</span>
                                        </div>
                                    </div>
                                </td>
                                <td className="px-8 py-6">
                                    <span className={`px-4 py-1 text-[10px] font-black uppercase tracking-widest rounded-full shadow-sm border ${getRoleBadgeColor(u.role)}`}>
                                        {u.role}
                                    </span>
                                </td>
                                <td className="px-8 py-6 text-sm text-slate-400 font-bold uppercase tracking-tight">{formatDate(u.created_at)}</td>
                                <td className="px-8 py-6 text-right">
                                    <Link href={`/admin/users/${u.id}`} className="inline-flex px-6 py-2 bg-slate-100 hover:bg-indigo-600 text-[10px] font-black uppercase tracking-widest text-slate-600 hover:text-white rounded-xl transition-all shadow-sm">
                                        View Profile
                                    </Link>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </IOSCard>
      )}
    </div>
  )
}

// pages/admin/users/index.vue
<template>
  <div>
    <div class="ios-page-header">
      <div class="flex justify-between items-center">
        <div>
          <h1>Benutzerverwaltung</h1>
          <p>Systembenutzer und deren Rollen verwalten</p>
        </div>
        <NuxtLink to="/admin/users/new" class="ios-button ios-button-primary inline-flex items-center gap-2">
          ➕ Benutzer erstellen
        </NuxtLink>
      </div>
    </div>

    <div class="mb-6 flex gap-2 flex-wrap">
      <button
        v-for="role in ['', 'admin', 'teacher', 'parent', 'kitchen', 'support']"
        :key="role"
        @click="selectedRole = role"
        :class="[
          'ios-button transition-all duration-200 capitalize',
          selectedRole === role 
            ? 'ios-button-primary' 
            : 'ios-button-secondary'
        ]"
      >
        {{ role || 'Alle' }}
      </button>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else>
      <div v-if="filteredUsers.length === 0">
        <IOSCard customClass="p-8 text-center">
          <div class="text-6xl mb-4 opacity-50">👤</div>
          <p class="text-lg font-semibold text-gray-900 mb-2">Keine Benutzer gefunden</p>
          <p class="text-sm text-gray-600 mb-4">
            {{ selectedRole ? `Keine ${selectedRole}-Benutzer gefunden.` : 'Erstellen Sie Ihren ersten Benutzer, um zu beginnen.' }}
          </p>
          <NuxtLink to="/admin/users/new" class="ios-button ios-button-primary inline-flex items-center gap-2">
            Benutzer erstellen
          </NuxtLink>
        </IOSCard>
      </div>

      <div v-else>
        <IOSCard customClass="overflow-hidden p-0">
          <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="ios-glass">
                <tr>
                  <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Name</th>
                  <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Email</th>
                  <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Rolle</th>
                  <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Erstellt</th>
                  <th class="px-6 py-3 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">Aktionen</th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <tr v-for="user in filteredUsers" :key="user.id" class="hover:bg-gray-50 transition-colors">
                  <td class="px-6 py-4 whitespace-nowrap font-semibold text-gray-900">
                    {{ user.full_name }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                    {{ user.email }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <span
                      :class="[
                        'px-3 py-1 text-xs font-semibold rounded-full capitalize',
                        user.role === 'admin' ? 'bg-blue-100 text-blue-800' :
                        user.role === 'teacher' ? 'bg-blue-100 text-blue-800' :
                        user.role === 'parent' ? 'bg-green-100 text-green-800' :
                        user.role === 'kitchen' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-gray-100 text-gray-800'
                      ]"
                    >
                      {{ user.role }}
                    </span>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                    {{ formatDate(user.created_at) }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <button
                      @click="editUser(user)"
                      class="text-blue-600 hover:text-blue-700 font-medium"
                    >
                      Bearbeiten
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </IOSCard>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useSupabaseClient } from '#imports'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'
import IOSCard from '~/components/ui/IOSCard.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const supabase = useSupabaseClient()
const loading = ref(true)
const error = ref('')
const users = ref<any[]>([])
const selectedRole = ref('')

const filteredUsers = computed(() => {
  if (!selectedRole.value) return users.value
  return users.value.filter(u => u.role === selectedRole.value)
})

onMounted(async () => {
  await fetchUsers()
})

watch(selectedRole, async () => {
  await fetchUsers()
})

const fetchUsers = async () => {
  try {
    loading.value = true
    error.value = ''
    
    let query = supabase.from('profiles').select('*')
    
    if (selectedRole.value) {
      query = query.eq('role', selectedRole.value)
    }
    
    query = query.order('created_at', { ascending: false })
    
    const { data, error: err } = await query
    
    if (err) {
      console.error('Error fetching users:', err)
      throw err
    }
    
    console.log('Fetched users:', data?.length || 0, 'users')
    users.value = data || []
    
    if (users.value.length === 0) {
      console.log('No users found in database')
    }
  } catch (e: any) {
    console.error('Failed to load users:', e)
    error.value = e.message || 'Failed to load users'
  } finally {
    loading.value = false
  }
}

const editUser = (user: any) => {
  // Navigate to edit page or open modal
  navigateTo(`/admin/users/${user.id}`)
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}
</script>
