// components/common/IOSStatCard.vue
<template>
  <NuxtLink v-if="to" :to="to" class="ios-stat-card ios-animate ios-press block no-underline" :class="customClass">
    <div class="flex items-start justify-between">
      <div class="flex-1">
        <p class="ios-stat-label">{{ title }}</p>
        <p class="ios-stat-value">{{ formatValue }}</p>
        <p v-if="subtitle" class="ios-stat-subtitle">{{ subtitle }}</p>
      </div>
      <div v-if="icon" class="ios-stat-icon">{{ icon }}</div>
    </div>
    <div v-if="trend" class="ios-stat-trend">
      <div class="flex items-center text-xs" :class="trend.type === 'up' ? 'text-green-500' : 'text-red-500'">
        <span v-if="trend.type === 'up'">↑</span>
        <span v-else>↓</span>
        <span class="ml-1">{{ trend.value }}</span>
      </div>
    </div>
  </NuxtLink>
  <div v-else class="ios-stat-card ios-animate ios-press" :class="customClass">
    <div class="flex items-start justify-between">
      <div class="flex-1">
        <p class="ios-stat-label">{{ title }}</p>
        <p class="ios-stat-value">{{ formatValue }}</p>
        <p v-if="subtitle" class="ios-stat-subtitle">{{ subtitle }}</p>
      </div>
      <div v-if="icon" class="ios-stat-icon">{{ icon }}</div>
    </div>
    <div v-if="trend" class="ios-stat-trend">
      <div class="flex items-center text-xs" :class="trend.type === 'up' ? 'text-green-500' : 'text-red-500'">
        <span v-if="trend.type === 'up'">↑</span>
        <span v-else>↓</span>
        <span class="ml-1">{{ trend.value }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  title: string
  value: number | string
  icon?: string
  subtitle?: string
  trend?: {
    type: 'up' | 'down'
    value: string
  }
  customClass?: string
  to?: string
}

const props = defineProps<Props>()

const formatValue = computed(() => {
  if (typeof props.value === 'number') {
    return props.value.toLocaleString()
  }
  return props.value
})
</script>

<style scoped>
.ios-stat-card {
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(20px) saturate(180%);
  -webkit-backdrop-filter: blur(20px) saturate(180%);
  border: 1px solid rgba(255, 255, 255, 0.3);
  border-radius: 20px;
  padding: 20px;
  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  cursor: pointer;
  text-decoration: none;
  color: inherit;
  display: block;
}

.ios-stat-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 12px 40px 0 rgba(31, 38, 135, 0.5);
}

.ios-stat-label {
  font-size: 13px;
  font-weight: 600;
  color: rgba(0, 0, 0, 0.6);
  margin-bottom: 8px;
  letter-spacing: 0.3px;
  text-transform: uppercase;
}

.ios-stat-value {
  font-size: 32px;
  font-weight: 700;
  color: rgba(0, 0, 0, 0.9);
  line-height: 1.2;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.ios-stat-subtitle {
  font-size: 12px;
  color: rgba(0, 0, 0, 0.5);
  margin-top: 6px;
}

.ios-stat-icon {
  font-size: 36px;
  opacity: 0.8;
  filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1));
}

.ios-stat-trend {
  margin-top: 12px;
  padding-top: 12px;
  border-top: 1px solid rgba(0, 0, 0, 0.1);
}

@media (max-width: 768px) {
  .ios-stat-card {
    padding: 16px;
    border-radius: 16px;
  }
  
  .ios-stat-value {
    font-size: 28px;
  }
  
  .ios-stat-icon {
    font-size: 32px;
  }
}

@media (prefers-color-scheme: dark) {
  .ios-stat-card {
    background: rgba(30, 30, 30, 0.7);
    border-color: rgba(255, 255, 255, 0.1);
  }
  
  .ios-stat-label {
    color: rgba(255, 255, 255, 0.7);
  }
  
  .ios-stat-value {
    color: rgba(255, 255, 255, 0.95);
  }
  
  .ios-stat-subtitle {
    color: rgba(255, 255, 255, 0.6);
  }
}
</style>

// src/components/common/IOSStatCard.tsx
import React from 'react'
import Link from 'next/link'
import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

interface Trend {
  type: 'up' | 'down'
  value: string
}

interface IOSStatCardProps {
  title: string
  value: number | string
  icon?: string
  subtitle?: string
  trend?: Trend
  className?: string
  to?: string
  color?: string
}

export function IOSStatCard({
  title,
  value,
  icon,
  subtitle,
  trend,
  className,
  to,
  color
}: IOSStatCardProps) {
  const formatValue = typeof value === 'number' ? value.toLocaleString() : value

  const Content = (
    <>
      <div className="flex items-start justify-between">
        <div className="flex-1 min-w-0">
          <p className="text-[12px] font-bold text-ui-soft mb-2 tracking-wider uppercase">
            {title}
          </p>
          <p className="text-[32px] md:text-[28px] font-black leading-tight text-slate-900 dark:text-white tracking-tight">
            {formatValue}
          </p>
          {subtitle && (
            <p className="text-[12px] text-ui-soft mt-1 font-medium">
              {subtitle}
            </p>
          )}
        </div>
        {icon && (
          <div className="w-12 h-12 shrink-0 rounded-2xl bg-indigo-50 dark:bg-indigo-950/50 flex items-center justify-center text-[24px] text-indigo-600 dark:text-indigo-300">
            {icon}
          </div>
        )}
      </div>
      {trend && (
        <div className="mt-4 pt-4 border-t border-slate-100 dark:border-white/10">
          <div className={cn("flex items-center text-xs font-bold", trend.type === 'up' ? 'text-emerald-500' : 'text-rose-500')}>
            <span className="flex items-center gap-1 px-2 py-1 rounded-full bg-current bg-opacity-10">
              <span>{trend.type === 'up' ? '↑' : '↓'}</span>
              <span>{trend.value}</span>
            </span>
            <span className="ml-2 text-ui-soft font-medium whitespace-nowrap">vs last month</span>
          </div>
        </div>
      )}
    </>
  )

  const cardClasses = cn(
    'block rounded-3xl border border-slate-100 dark:border-white/10 bg-white dark:bg-slate-900/60 p-6 shadow-xl shadow-slate-200/40 dark:shadow-none transition-all duration-500 ease-[cubic-bezier(0.2,0.8,0.2,1)] text-inherit no-underline group h-full',
    to && 'cursor-pointer hover:-translate-y-2 hover:shadow-2xl hover:shadow-indigo-200/30 dark:hover:border-indigo-500/30 hover:border-indigo-100 active:scale-[0.98]',
    color,
    className
  )

  if (to) {
    return (
      <Link href={to} className={cardClasses}>
        {Content}
      </Link>
    )
  }

  return (
    <div className={cardClasses}>
      {Content}
    </div>
  )
}
