// pages/admin/hr/payroll/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <Heading size="xl">Payroll Management</Heading>
      <div class="flex gap-2">
        <NuxtLink
          to="/admin/hr/payroll/generate"
          class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
        >
          ➕ Generate Payroll
        </NuxtLink>
        <NuxtLink
          to="/admin/hr/salary-config"
          class="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 transition-colors"
        >
          ⚙️ Salary Config
        </NuxtLink>
      </div>
    </div>

    <div class="bg-white rounded-lg shadow p-6 mb-6">
      <form @submit.prevent="filterPayroll" class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Month</label>
          <select
            v-model.number="filters.month"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          >
            <option :value="0">All Months</option>
            <option v-for="m in 12" :key="m" :value="m">
              {{ getMonthName(m) }}
            </option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Year</label>
          <input
            v-model.number="filters.year"
            type="number"
            :min="2020"
            :max="2100"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Status</label>
          <select
            v-model="filters.status"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          >
            <option value="">All Statuses</option>
            <option value="draft">Draft</option>
            <option value="approved">Approved</option>
            <option value="paid">Paid</option>
          </select>
        </div>
        <div class="flex items-end">
          <button
            type="submit"
            class="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
          >
            Filter
          </button>
        </div>
      </form>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="filteredPayroll.length === 0" class="p-8 text-center text-gray-500">
        No payroll records found.
      </div>

      <table v-else class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Staff</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Period</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Base Salary</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Overtime</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Bonuses</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Deductions</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Net Salary</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr v-for="record in filteredPayroll" :key="record.id" class="hover:bg-gray-50">
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
              {{ getStaffName(record.staff_id) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              {{ getMonthName(record.month) }} {{ record.year }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              €{{ record.base_salary.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              €{{ record.overtime_amount.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-green-600">
              €{{ record.bonuses.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-red-600">
              €{{ record.deductions.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
              €{{ record.net_salary.toFixed(2) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span
                :class="[
                  'px-2 py-1 text-xs font-medium rounded-full',
                  record.status === 'paid' ? 'bg-green-100 text-green-800' :
                  record.status === 'approved' ? 'bg-blue-100 text-blue-800' :
                  'bg-yellow-100 text-yellow-800'
                ]"
              >
                {{ record.status }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
              <NuxtLink
                :to="`/admin/hr/payroll/${record.id}`"
                class="text-blue-600 hover:text-blue-900 mr-3"
              >
                View
              </NuxtLink>
              <button
                v-if="record.status !== 'paid'"
                @click="markAsPaid(record.id)"
                class="text-green-600 hover:text-green-900"
              >
                Mark Paid
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useSupabaseClient } from '#imports'
import { usePayrollStore } from '~/stores/payroll'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const supabase = useSupabaseClient()
const payrollStore = usePayrollStore()

const { payroll, loading, error } = storeToRefs(payrollStore)
const staff = ref<any[]>([])

const filters = ref({
  month: 0,
  year: new Date().getFullYear(),
  status: ''
})

const filteredPayroll = computed(() => {
  let result = payroll.value

  if (filters.value.month > 0) {
    result = result.filter(p => p.month === filters.value.month)
  }

  if (filters.value.year) {
    result = result.filter(p => p.year === filters.value.year)
  }

  if (filters.value.status) {
    result = result.filter(p => p.status === filters.value.status)
  }

  return result
})

onMounted(async () => {
  try {
    await Promise.all([
      payrollStore.fetchPayroll(),
      fetchStaff()
    ])
  } catch (e: any) {
    console.error('Error loading payroll:', e)
  }
})

const fetchStaff = async () => {
  try {
    const { data } = await supabase
      .from('profiles')
      .select('id, full_name')
      .in('role', ['teacher', 'support', 'kitchen'])
      .order('full_name')

    staff.value = data || []
  } catch (e: any) {
    console.error('Error fetching staff:', e)
  }
}

const filterPayroll = async () => {
  await payrollStore.fetchPayroll(
    undefined,
    filters.value.month || undefined,
    filters.value.year || undefined
  )
}

const getStaffName = (staffId: string) => {
  const s = staff.value.find(s => s.id === staffId)
  return s?.full_name || staffId
}

const getMonthName = (month: number) => {
  const date = new Date(2000, month - 1, 1)
  return date.toLocaleString('default', { month: 'long' })
}

const markAsPaid = async (id: string) => {
  if (!confirm('Mark this payroll as paid?')) return

  try {
    await payrollStore.markAsPaid(id)
    await payrollStore.fetchPayroll()
  } catch (e: any) {
    alert(e.message || 'Failed to mark as paid')
  }
}
</script>

// src/app/admin/hr/payroll/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.hr.payroll'

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { usePayrollStore, StaffPayroll } from '@/stores/payroll'
import { useStaffStore } from '@/stores/staff'
import { useAuth } from '@/hooks/useAuth'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'
import { useToastStore } from '@/stores/toast'
import { downloadTextFile, toCsv } from '@/utils/export/csv'

export default function AdminPayrollPage() {
  const { t } = useI18n()

  const { profile } = useAuth()
  const { payroll, loading, error, fetchPayroll, markAsPaid } = usePayrollStore()
  const { staff, fetchStaff } = useStaffStore()
  const toast = useToastStore()
  
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1)
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())

  useEffect(() => {
    if (profile?.kita_id) {
        fetchPayroll(undefined, selectedMonth, selectedYear, profile.kita_id)
        fetchStaff()
    }
  }, [profile, selectedMonth, selectedYear, fetchPayroll, fetchStaff])

  const getStaffName = (staffId: string) => {
    const s = staff.find(s => s.id === staffId)
    return s ? s.full_name : 'Unbekannt'
  }

  const handleMarkPaid = async (id: string) => {
    if (!confirm('Gehalt als ausgezahlt markieren?')) return
    try {
        await markAsPaid(id)
        if (profile?.kita_id) fetchPayroll(undefined, selectedMonth, selectedYear, profile.kita_id)
        toast.push({ type: 'success', title: 'Payroll', message: 'Als bezahlt markiert.' })
    } catch (e: any) {
        toast.push({ type: 'error', title: 'Payroll', message: e?.message || 'Aktion fehlgeschlagen.' })
    }
  }

  const exportCsv = () => {
    const rows = [
      ['Mitarbeiter', 'Monat', 'Jahr', 'Netto', 'Überstunden (h)', 'Status'],
      ...payroll.map((p) => [
        getStaffName(p.staff_id),
        new Date(2000, p.month - 1).toLocaleString('de-DE', { month: 'long' }),
        p.year,
        p.net_salary,
        p.overtime_hours,
        p.status,
      ]),
    ]
    const csv = toCsv(rows, { delimiter: ';', includeBom: true })
    downloadTextFile(`payroll-${selectedMonth}-${selectedYear}.csv`, csv, 'text/csv;charset=utf-8')
    toast.push({ type: 'success', title: 'Payroll', message: 'CSV exportiert.' })
  }

  if (loading && payroll.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-7xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-10">
        <div>
          <Heading size="xl" className="text-gray-900 tracking-tight">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-gray-500 mt-1">Verwalten Sie Gehälter, Überstunden und Auszahlungen.</p>
        </div>
        <div className="flex gap-2">
            <IOSButton variant="secondary" className="px-6 py-2.5 text-sm font-black uppercase tracking-widest border-black/10" onClick={exportCsv}>
              📥 Export
            </IOSButton>
            <Link href="/admin/hr/salary-config">
                <IOSButton variant="secondary" className="px-6 py-2.5 text-sm font-black uppercase tracking-widest border-black/10">
                    ⚙️ Konfiguration
                </IOSButton>
            </Link>
            <Link href="/admin/hr/payroll/generate">
              <IOSButton className="px-6 py-2.5 text-sm font-black uppercase tracking-widest bg-black text-white border-none">
                ➕ Abrechnung erstellen
              </IOSButton>
            </Link>
        </div>
      </div>

      <div className="mb-10 flex gap-4">
            <select 
                value={selectedMonth} 
                onChange={(e) => setSelectedMonth(parseInt(e.target.value))}
                className="px-4 py-2 bg-white border border-black/5 rounded-2xl text-sm font-black uppercase tracking-widest shadow-sm focus:ring-2 focus:ring-black/5 outline-none"
            >
                {Array.from({ length: 12 }, (_, i) => (
                    <option key={i+1} value={i+1}>
                        {new Date(2000, i).toLocaleString('de-DE', { month: 'long' })}
                    </option>
                ))}
            </select>
            <select 
                value={selectedYear} 
                onChange={(e) => setSelectedYear(parseInt(e.target.value))}
                className="px-4 py-2 bg-white border border-black/5 rounded-2xl text-sm font-black uppercase tracking-widest shadow-sm focus:ring-2 focus:ring-black/5 outline-none"
            >
                {[2024, 2025, 2026].map(y => (
                    <option key={y} value={y}>{y}</option>
                ))}
            </select>
      </div>

      {error ? (
        <ErrorAlert message={error.message || 'Fehler beim Laden der Abrechnungen'} />
      ) : payroll.length === 0 ? (
        <IOSCard className="p-20 text-center bg-gray-50/30 border-black/5">
          <div className="text-6xl opacity-10 mb-6">💰</div>
          <p className="text-gray-400 font-bold max-w-xs mx-auto">Keine Abrechnungen für diesen Zeitraum gefunden.</p>
        </IOSCard>
      ) : (
        <div className="grid grid-cols-1 gap-4">
            {payroll.map(entry => (
                <IOSCard key={entry.id} className="p-0 overflow-hidden border-black/5 group hover:shadow-xl transition-all duration-300">
                    <div className="p-6 md:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6">
                        <div className="flex-1">
                            <div className="flex items-center gap-3 mb-2">
                                <h3 className="text-lg font-black text-gray-900">{getStaffName(entry.staff_id)}</h3>
                                <span className={`px-2 py-0.5 text-[9px] font-black uppercase tracking-widest rounded-md border ${
                                    entry.status === 'paid' ? 'bg-green-50 text-green-600 border-green-100' :
                                    entry.status === 'approved' ? 'bg-blue-50 text-blue-600 border-blue-100' :
                                    'bg-amber-50 text-amber-600 border-amber-100'
                                }`}>
                                    {entry.status === 'paid' ? 'Bezahlt' : entry.status === 'approved' ? 'Freigegeben' : 'Entwurf'}
                                </span>
                            </div>
                            <div className="flex flex-wrap gap-x-6 gap-y-2 text-[10px] font-black text-black/30 uppercase tracking-widest">
                                <span className="text-[#667eea]">💵 Netto: {entry.net_salary.toFixed(2)}€</span>
                                <span>🕒 Überstunden: {entry.overtime_hours}h</span>
                                <span>📅 {new Date(entry.year, entry.month - 1).toLocaleString('de-DE', { month: 'long', year: 'numeric' })}</span>
                            </div>
                        </div>

                        <div className="flex gap-2">
                            {entry.status !== 'paid' && (
                                <IOSButton onClick={() => handleMarkPaid(entry.id)} className="px-4 py-2 text-[10px] font-black uppercase tracking-widest bg-green-600 text-white border-none hover:bg-green-700">Bezahlt markieren</IOSButton>
                            )}
                            <Link href={`/admin/hr/payroll/${entry.id}`}>
                              <IOSButton variant="secondary" className="px-4 py-2 text-[10px] font-black uppercase tracking-widest border-black/5 bg-gray-50 hover:bg-white">
                                Details
                              </IOSButton>
                            </Link>
                        </div>
                    </div>
                </IOSCard>
            ))}
        </div>
      )}
    </div>
  )
}
