// src/app/admin/staff/page.tsx
'use client'

import { useI18n } from '@/i18n/I18nProvider'
import { pT } from '@/i18n/pT'

const ROUTE = 'admin.staff'

import React, { useEffect, useState, useMemo } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useStaffStore } from '@/stores/staff'
import { Heading } from '@/components/ui/Heading'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { ErrorAlert } from '@/components/common/ErrorAlert'
import { IOSCard } from '@/components/ui/IOSCard'
import { IOSButton } from '@/components/ui/IOSButton'

export default function AdminStaffPage() {
  const { t } = useI18n()

  const router = useRouter()
  const { staff, loading, error, fetchStaff } = useStaffStore()
  const [selectedRole, setSelectedRole] = useState('')

  const roles = [
    { value: '', label: 'Alle' },
    { value: 'teacher', label: 'Erzieher' },
    { value: 'kitchen', label: 'Küche' },
    { value: 'support', label: 'Support' }
  ]

  useEffect(() => {
    fetchStaff(selectedRole || undefined)
  }, [selectedRole, fetchStaff])

  const getRoleLabel = (role: string) => {
    const r = roles.find(r => r.value === role)
    return r ? r.label : role
  }

  const getRoleBadgeColor = (role: string) => {
    const colors: Record<string, string> = {
      teacher: 'bg-indigo-50 text-indigo-600 border-indigo-100',
      kitchen: 'bg-amber-50 text-amber-600 border-amber-100',
      support: 'bg-green-50 text-green-600 border-green-100',
      admin: 'bg-blue-50 text-blue-600 border-blue-100'
    }
    return colors[role] || 'bg-gray-50 text-gray-600 border-gray-100'
  }

  if (loading && staff.length === 0) return <div className="flex justify-center py-24"><LoadingSpinner /></div>

  return (
    <div className="max-w-7xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-10">
        <div>
          <Heading size="xl" className="text-gray-900 tracking-tight">{t(pT(ROUTE))}</Heading>
          <p className="text-sm text-gray-500 mt-1">Verwalten Sie Ihre Mitarbeiter, Profile und Qualifikationen.</p>
        </div>
        <Link href="/admin/staff/new">
          <IOSButton variant="primary" className="px-6 py-2.5 text-sm font-black uppercase tracking-widest flex items-center gap-2 shadow-xl shadow-blue-500/20">
            <span>➕</span>
            <span>Mitarbeiter hinzufügen</span>
          </IOSButton>
        </Link>
      </div>

      <div className="mb-10 overflow-x-auto pb-2 -mx-2 px-2">
          <div className="flex gap-2">
            {roles.map(role => (
              <button
                key={role.value}
                onClick={() => setSelectedRole(role.value)}
                className={`px-5 py-2 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all duration-300 ${
                  selectedRole === role.value
                    ? 'bg-black text-white border-black shadow-lg shadow-black/10' 
                    : 'bg-white text-gray-400 border-black/5 hover:border-black/10'
                }`}
              >
                {role.label}
              </button>
            ))}
          </div>
      </div>

      {error ? (
        <ErrorAlert message={error.message || 'Fehler beim Laden des Personals'} />
      ) : staff.length === 0 ? (
        <IOSCard className="p-20 text-center bg-gray-50/30 border-black/5">
          <div className="text-6xl opacity-10 mb-6">👥</div>
          <p className="text-gray-400 font-bold max-w-xs mx-auto">
            {selectedRole ? `Keine Mitarbeiter mit der Rolle "${getRoleLabel(selectedRole)}" gefunden.` : 'Keine Mitarbeiter im System gefunden.'}
          </p>
        </IOSCard>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {staff.map(member => (
                <Link key={member.id} href={`/admin/staff/${member.id}`}>
                    <IOSCard className="p-0 overflow-hidden group hover:shadow-2xl hover:scale-[1.02] transition-all duration-500 border-black/5 h-full flex flex-col">
                        <div className="p-8 flex-1">
                            <div className="flex justify-between items-start mb-6">
                                <div className="w-14 h-14 rounded-2xl bg-black/5 group-hover:bg-[#667eea] group-hover:text-white flex items-center justify-center text-xl font-black text-black/20 shadow-inner transition-all duration-500">
                                    {member.full_name?.charAt(0) || '?'}
                                </div>
                                <span className={`px-2.5 py-1 text-[9px] font-black uppercase tracking-widest rounded-md border ${getRoleBadgeColor(member.role)}`}>
                                    {member.role}
                                </span>
                            </div>
                            <h3 className="text-xl font-black text-gray-900 mb-1 group-hover:text-[#667eea] transition-colors">{member.full_name}</h3>
                            <p className="text-xs font-bold text-gray-400 truncate mb-6">{member.email}</p>
                            
                            <div className="flex items-center gap-2 text-[10px] font-black text-black/20 uppercase tracking-widest italic">
                                <span>📱</span>
                                <span className="group-hover:text-gray-800 transition-colors">{member.phone || 'Keine Nummer'}</span>
                            </div>
                        </div>
                        <div className="px-8 py-5 bg-gray-50/50 border-t border-black/5 transition-colors group-hover:bg-white flex items-center justify-between">
                            <span className="text-[10px] font-black text-[#667eea] uppercase tracking-widest group-hover:translate-x-1 transition-all duration-500">Profil ansehen →</span>
                            <div className="w-8 h-8 rounded-full bg-white flex items-center justify-center text-xs opacity-0 group-hover:opacity-100 shadow-sm border border-black/5 transition-all">✏️</div>
                        </div>
                    </IOSCard>
                </Link>
            ))}
        </div>
      )}
    </div>
  )
}

// pages/admin/staff/index.vue
<template>
  <div>
    <div class="flex justify-between items-center mb-6">
      <div class="ios-page-header">
        <h1>Personalverwaltung</h1>
      </div>
      <div class="flex justify-end mb-6">
        <NuxtLink
          to="/admin/staff/new"
          class="ios-button ios-button-primary inline-flex items-center gap-2"
        >
          ➕ Personalmitglied hinzufügen
        </NuxtLink>
      </div>
    </div>

    <div class="mb-4 flex gap-2">
      <button
        @click="selectedRole = ''"
        :class="[
          'ios-button transition-colors',
          selectedRole === '' 
            ? 'ios-button-primary' 
            : 'ios-button-secondary'
        ]"
      >
        Alle
      </button>
      <button
        @click="selectedRole = 'teacher'"
        :class="[
          'ios-button transition-colors',
          selectedRole === 'teacher' 
            ? 'ios-button-primary' 
            : 'ios-button-secondary'
        ]"
      >
        Erzieher
      </button>
      <button
        @click="selectedRole = 'kitchen'"
        :class="[
          'ios-button transition-colors',
          selectedRole === 'kitchen' 
            ? 'ios-button-primary' 
            : 'ios-button-secondary'
        ]"
      >
        Küche
      </button>
      <button
        @click="selectedRole = 'support'"
        :class="[
          'ios-button transition-colors',
          selectedRole === 'support' 
            ? 'ios-button-primary' 
            : 'ios-button-secondary'
        ]"
      >
        Support
      </button>
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else>
      <IOSCard customClass="overflow-hidden p-0">
        <div v-if="filteredStaff.length === 0" class="p-8 text-center text-gray-600">
          <div class="text-6xl mb-4 opacity-50">👥</div>
          <p class="text-lg font-semibold text-gray-900 mb-2">Keine Mitarbeiter gefunden</p>
          <p class="text-sm text-gray-600">Fügen Sie Ihren ersten Mitarbeiter hinzu, um zu beginnen.</p>
        </div>

        <template v-else>
          <!-- Mobile Card View -->
          <div class="block md:hidden space-y-3">
            <div
              v-for="member in filteredStaff"
              :key="member.id"
              class="bg-white rounded-lg shadow-sm border border-gray-200 p-4"
            >
              <div class="flex items-start justify-between mb-3">
                <div>
                  <h3 class="text-base font-semibold text-gray-900">
                    {{ member.full_name }}
                  </h3>
                  <p class="text-sm text-gray-600 mt-1">{{ member.email }}</p>
                </div>
                <span
                  :class="[
                    'px-2 py-1 text-xs font-semibold rounded-full',
                    getRoleClass(member.role)
                  ]"
                >
                  {{ getRoleLabel(member.role) }}
                </span>
              </div>
              <div class="text-sm text-gray-600 mb-3" v-if="member.phone">
                <span class="font-medium">Telefon:</span> {{ member.phone }}
              </div>
              <div class="flex gap-2">
                <NuxtLink
                  :to="`/admin/staff/${member.id}`"
                  class="flex-1 ios-button ios-button-secondary text-sm px-3 py-2 text-center"
                >
                  👁️ Ansehen
                </NuxtLink>
                <NuxtLink
                  :to="`/admin/staff/${member.id}?edit=true`"
                  class="flex-1 ios-button ios-button-secondary text-sm px-3 py-2 text-center"
                >
                  ✏️ Bearbeiten
                </NuxtLink>
              </div>
            </div>
          </div>

          <!-- Desktop Table View -->
          <div class="hidden md:block overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="ios-glass">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Name</th>
                <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">E-Mail</th>
                <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Rolle</th>
                <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider">Telefon</th>
                <th class="px-6 py-3 text-right text-xs font-semibold text-gray-700 uppercase tracking-wider">Aktionen</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr v-for="member in filteredStaff" :key="member.id" class="hover:bg-gray-50 transition-colors">
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm font-semibold text-gray-900">
                    {{ member.full_name }}
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                  {{ member.email }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span
                    :class="[
                      'px-3 py-1 text-xs font-semibold rounded-full capitalize',
                      member.role === 'teacher' ? 'bg-blue-100 text-blue-800' :
                      member.role === 'kitchen' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-gray-100 text-gray-800'
                    ]"
                  >
                    {{ member.role }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                  {{ member.phone || '-' }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <NuxtLink
                    :to="`/admin/staff/${member.id}`"
                    class="text-blue-600 hover:text-blue-700 font-medium"
                  >
                    Ansehen
                  </NuxtLink>
                </td>
              </tr>
            </tbody>
          </table>
          </div>
        </template>
      </IOSCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useStaffStore } from '~/stores/staff'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'
import IOSCard from '~/components/ui/IOSCard.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'admin'
})

const staffStore = useStaffStore()
const { staff, loading, error } = storeToRefs(staffStore)
const selectedRole = ref('')

const filteredStaff = computed(() => {
  if (!selectedRole.value) return staff.value
  return staff.value.filter(s => s.role === selectedRole.value)
})

onMounted(async () => {
  await staffStore.fetchStaff()
})

watch(selectedRole, async (newRole) => {
  await staffStore.fetchStaff(newRole || undefined)
})

const getRoleLabel = (role: string) => {
  const labels: Record<string, string> = {
    teacher: 'Erzieher',
    kitchen: 'Küche',
    support: 'Support',
    admin: 'Admin'
  }
  return labels[role] || role
}

const getRoleClass = (role: string) => {
  if (role === 'teacher') return 'bg-blue-100 text-blue-800'
  if (role === 'kitchen') return 'bg-yellow-100 text-yellow-800'
  if (role === 'support') return 'bg-green-100 text-green-800'
  return 'bg-gray-100 text-gray-800'
}
</script>
