// components/forms/AbsenceSubmissionForm.vue
<template>
  <div class="p-6">
    <h3 class="text-lg font-medium text-gray-900 mb-4">Submit Absence</h3>
    
    <form @submit.prevent="handleSubmit">
      <div class="mb-4">
        <label for="reason" class="block text-sm font-medium text-gray-700 mb-2">
          Reason <span class="text-red-500">*</span>
        </label>
        <textarea
          id="reason"
          v-model="form.reason"
          rows="3"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="Enter reason for absence..."
        />
      </div>

      <div class="mb-4">
        <label for="notes" class="block text-sm font-medium text-gray-700 mb-2">
          Additional Notes (Optional)
        </label>
        <textarea
          id="notes"
          v-model="form.notes"
          rows="2"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="Any additional information..."
        />
      </div>

      <div v-if="error" class="mb-4 p-3 bg-red-50 text-red-700 rounded-md text-sm">
        {{ error }}
      </div>

      <div class="flex gap-3 justify-end">
        <button
          type="button"
          @click="$emit('cancel')"
          class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          :disabled="loading || !form.reason.trim()"
          class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ loading ? 'Submitting...' : 'Submit' }}
        </button>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useAttendanceStore } from '~/stores/attendance'

const emit = defineEmits<{
  (e: 'submit', data: { reason: string; notes?: string }): void
  (e: 'cancel'): void
}>()

const attendanceStore = useAttendanceStore()

const form = ref({
  reason: '',
  notes: ''
})

const loading = ref(false)
const error = ref('')

const handleSubmit = async () => {
  if (!form.value.reason.trim()) {
    error.value = 'Reason is required'
    return
  }

  loading.value = true
  error.value = ''

  try {
    emit('submit', {
      reason: form.value.reason.trim(),
      notes: form.value.notes.trim() || undefined
    })
  } catch (e: any) {
    error.value = e.message || 'Failed to submit absence'
  } finally {
    loading.value = false
  }
}
</script>

// src/components/forms/AbsenceSubmissionForm.tsx
'use client'

import React, { useState } from 'react'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

interface AbsenceSubmissionFormProps {
  onSubmit: (data: { reason: string; notes?: string }) => void
  onCancel: () => void
  loading?: boolean
}

export const AbsenceSubmissionForm = ({ onSubmit, onCancel, loading }: AbsenceSubmissionFormProps) => {
  const [form, setForm] = useState({
    reason: '',
    notes: ''
  })
  const [error, setError] = useState('')

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!form.reason.trim()) {
      setError('Grund ist erforderlich')
      return
    }
    setError('')
    onSubmit({
      reason: form.reason.trim(),
      notes: form.notes.trim() || undefined
    })
  }

  return (
    <div className="p-1">
      <h3 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-6">Abwesenheit melden</h3>
      
      <form onSubmit={handleSubmit} className="space-y-5">
        <div>
          <label htmlFor="reason" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
            Grund <span className="text-red-500">*</span>
          </label>
          <textarea
            id="reason"
            value={form.reason}
            onChange={(e) => setForm(prev => ({ ...prev, reason: e.target.value }))}
            rows={3}
            required
            className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
            placeholder="Grund für die Abwesenheit..."
          />
        </div>

        <div>
          <label htmlFor="notes" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
            Zusätzliche Notizen (Optional)
          </label>
          <textarea
            id="notes"
            value={form.notes}
            onChange={(e) => setForm(prev => ({ ...prev, notes: e.target.value }))}
            rows={2}
            className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
            placeholder="Weitere Informationen..."
          />
        </div>

        {error && (
          <div className="p-3 bg-red-50 text-red-700 rounded-xl text-xs font-medium border border-red-100">
            {error}
          </div>
        )}

        <div className="flex gap-3 justify-end pt-2">
          <IOSButton
            type="button"
            variant="secondary"
            onClick={onCancel}
            className="px-6 py-2.5 font-bold"
          >
            Abbrechen
          </IOSButton>
          <IOSButton
            type="submit"
            variant="primary"
            disabled={loading || !form.reason.trim()}
            className="px-6 py-2.5 font-bold min-w-[120px]"
          >
            {loading ? <LoadingSpinner size="sm" /> : 'Senden'}
          </IOSButton>
        </div>
      </form>
    </div>
  )
}
