// components/forms/GroupForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-4">
    <div>
      <label for="name" class="block text-sm font-medium text-gray-700 mb-1">
        Group Name *
      </label>
      <input
        id="name"
        v-model="form.name"
        type="text"
        required
        class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        placeholder="e.g., Bears Group"
      />
    </div>

    <div>
      <label for="age_range" class="block text-sm font-medium text-gray-700 mb-1">
        Age Range *
      </label>
      <select
        id="age_range"
        v-model="form.age_range"
        required
        class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
      >
        <option value="">Select age range</option>
        <option value="U3">Under 3 (U3)</option>
        <option value="Ü3">Over 3 (Ü3)</option>
      </select>
    </div>

    <div>
      <label for="capacity" class="block text-sm font-medium text-gray-700 mb-1">
        Capacity *
      </label>
      <input
        id="capacity"
        v-model.number="form.capacity"
        type="number"
        required
        min="1"
        class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
      />
    </div>

    <div>
      <label for="educator_id" class="block text-sm font-medium text-gray-700 mb-1">
        Assigned Teacher
      </label>
      <select
        id="educator_id"
        v-model="form.educator_id"
        class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
      >
        <option value="">No teacher assigned</option>
        <option v-for="teacher in teachers" :key="teacher.id" :value="teacher.id">
          {{ teacher.full_name }}
        </option>
      </select>
    </div>

    <div v-if="error" class="p-3 bg-red-50 text-red-700 rounded-md text-sm">
      {{ error }}
    </div>

    <div class="flex gap-3 justify-end pt-4">
      <button
        type="button"
        @click="$emit('cancel')"
        class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
      >
        Cancel
      </button>
      <button
        type="submit"
        :disabled="loading"
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {{ loading ? 'Saving...' : (isEdit ? 'Update' : 'Create') }}
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useSupabaseClient } from '#imports'
import type { Group } from '~/stores/groups'

interface Props {
  group?: Group
}

const props = defineProps<Props>()
const emit = defineEmits<{
  submit: [data: any]
  cancel: []
}>()

const supabase = useSupabaseClient()
const isEdit = computed(() => !!props.group)
const loading = ref(false)
const error = ref('')
const teachers = ref<any[]>([])

const form = ref({
  name: props.group?.name || '',
  age_range: props.group?.age_range || '',
  capacity: props.group?.capacity || 20,
  educator_id: props.group?.educator_id || ''
})

onMounted(async () => {
  // Fetch teachers
  const { data } = await supabase
    .from('profiles')
    .select('*')
    .eq('role', 'teacher')
    .order('full_name')

  teachers.value = data || []
})

const handleSubmit = async () => {
  loading.value = true
  error.value = ''

  try {
    emit('submit', form.value)
  } catch (e: any) {
    error.value = e.message || 'Failed to save group'
  } finally {
    loading.value = false
  }
}
</script>

// src/components/forms/GroupForm.tsx
'use client'

import React, { useState, useEffect } from 'react'
import { createClient } from '@/utils/supabase/client'
import { getActiveKitaId } from '@/utils/tenant/client'
import { getProfileIdsForKita } from '@/utils/tenant/profileScope'
import { IOSInput } from '@/components/ui/IOSInput'
import { IOSButton } from '@/components/ui/IOSButton'

interface GroupFormProps {
  group?: any
  onSubmit: (data: any) => void
  onCancel: () => void
  loading?: boolean
}

export function GroupForm({ group, onSubmit, onCancel, loading }: GroupFormProps) {
  const supabase = createClient()
  const isEdit = !!group
  const [error, setError] = useState('')
  const [teachers, setTeachers] = useState<any[]>([])

  const [form, setForm] = useState({
    name: group?.name || '',
    age_range: group?.age_range || '',
    capacity: group?.capacity || 20,
    educator_id: group?.educator_id || ''
  })

  useEffect(() => {
    const run = async () => {
      const kitaId = await getActiveKitaId()
      if (!kitaId) {
        setTeachers([])
        return
      }
      const tenantIds = await getProfileIdsForKita(supabase, kitaId)
      if (tenantIds.length === 0) {
        setTeachers([])
        return
      }
      const { data } = await supabase
        .from('profiles')
        .select('*')
        .in('id', tenantIds)
        .eq('role', 'teacher')
        .order('full_name')
      setTeachers(data || [])
    }
    void run()
  }, [supabase])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    onSubmit(form)
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <IOSInput
        id="name"
        label="Group Name *"
        type="text"
        required
        value={form.name}
        onChange={e => setForm({ ...form, name: e.target.value })}
        placeholder="e.g., Bears Group"
      />

      <div>
        <label className="block text-[14px] font-semibold text-[#1d1d1f] mb-2 tracking-[0.3px]">Age Range *</label>
        <select
          required
          value={form.age_range}
          onChange={e => setForm({ ...form, age_range: e.target.value })}
          className="w-full px-4 py-3 bg-white/90 border border-black/10 rounded-[12px] text-[#1d1d1f] outline-none focus:border-[#667eea]/50 focus:shadow-[0_0_0_4px_rgba(102,126,234,0.2)] transition-all"
        >
          <option value="">Select age range</option>
          <option value="U3">Under 3 (U3)</option>
          <option value="Ü3">Over 3 (Ü3)</option>
        </select>
      </div>

      <IOSInput
        id="capacity"
        label="Capacity *"
        type="number"
        required
        min={1}
        value={form.capacity}
        onChange={e => setForm({ ...form, capacity: Number(e.target.value) })}
      />

      <div>
        <label className="block text-[14px] font-semibold text-[#1d1d1f] mb-2 tracking-[0.3px]">Assigned Teacher</label>
        <select
          value={form.educator_id}
          onChange={e => setForm({ ...form, educator_id: e.target.value })}
          className="w-full px-4 py-3 bg-white/90 border border-black/10 rounded-[12px] text-[#1d1d1f] outline-none focus:border-[#667eea]/50 focus:shadow-[0_0_0_4px_rgba(102,126,234,0.2)] transition-all"
        >
          <option value="">No teacher assigned</option>
          {teachers.map(t => (
            <option key={t.id} value={t.id}>{t.full_name}</option>
          ))}
        </select>
      </div>

      {error && (
        <div className="p-3 bg-red-50/80 border border-red-100 rounded-xl text-sm font-semibold text-red-600">
          {error}
        </div>
      )}

      <div className="flex gap-3 justify-end pt-4 border-t border-black/5">
        <IOSButton type="button" variant="secondary" onClick={onCancel} className="px-6 py-2">
          Cancel
        </IOSButton>
        <IOSButton type="submit" variant="primary" disabled={loading} className="px-6 py-2">
          {loading ? 'Saving...' : (isEdit ? 'Update' : 'Create')}
        </IOSButton>
      </div>
    </form>
  )
}
