// components/forms/ObservationForm.vue
<template>
  <form @submit.prevent="handleSubmit">
    <div class="space-y-4">
      <div>
        <label for="child_id" class="block text-sm font-medium text-gray-700 mb-2">
          Child <span class="text-red-500">*</span>
        </label>
        <select
          id="child_id"
          v-model="form.child_id"
          required
          :disabled="childrenLoading"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <option value="">{{ childrenLoading ? 'Loading children...' : 'Select a child' }}</option>
          <option v-for="child in children" :key="child.id" :value="child.id">
            {{ child.first_name }} {{ child.last_name }}
          </option>
        </select>
        <p v-if="childrenError" class="mt-1 text-sm text-red-600">
          Error loading children: {{ childrenError.message }}
        </p>
      </div>

      <div>
        <label for="observation_date" class="block text-sm font-medium text-gray-700 mb-2">
          Date <span class="text-red-500">*</span>
        </label>
        <input
          id="observation_date"
          v-model="form.observation_date"
          type="date"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="context" class="block text-sm font-medium text-gray-700 mb-2">
          Context (Where/When)
        </label>
        <input
          id="context"
          v-model="form.context"
          type="text"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., During free play, Morning circle"
        />
      </div>

      <div>
        <label for="description" class="block text-sm font-medium text-gray-700 mb-2">
          Description <span class="text-red-500">*</span>
        </label>
        <textarea
          id="description"
          v-model="form.description"
          rows="6"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          placeholder="Describe what you observed..."
        />
      </div>

      <div>
        <label for="development_area" class="block text-sm font-medium text-gray-700 mb-2">
          Development Area
        </label>
        <select
          id="development_area"
          v-model="form.development_area"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        >
          <option value="">Select area</option>
          <option value="Social">Social</option>
          <option value="Motor">Motor</option>
          <option value="Language">Language</option>
          <option value="Cognitive">Cognitive</option>
          <option value="Emotional">Emotional</option>
          <option value="Creative">Creative</option>
        </select>
      </div>

      <div v-if="error" class="p-3 bg-red-50 text-red-700 rounded-md text-sm">
        {{ error }}
      </div>

      <div class="flex gap-3 justify-end">
        <button
          type="button"
          @click="$emit('cancel')"
          class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          :disabled="loading || !isFormValid"
          class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ loading ? 'Creating...' : 'Create Observation' }}
        </button>
      </div>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useChildrenStore } from '~/stores/children'

const emit = defineEmits<{
  (e: 'submit', data: any): void
  (e: 'cancel'): void
}>()

const childrenStore = useChildrenStore()
const { children, loading: childrenLoading, error: childrenError } = storeToRefs(childrenStore)

const form = ref({
  child_id: '',
  observation_date: new Date().toISOString().split('T')[0],
  context: '',
  description: '',
  development_area: '',
  photos: [] as string[],
  videos: [] as string[]
})

const loading = ref(false)
const error = ref('')

const isFormValid = computed(() => {
  return form.value.child_id &&
    form.value.observation_date &&
    form.value.description.trim()
})

onMounted(async () => {
  await childrenStore.fetchChildren()
})

const handleSubmit = () => {
  if (!isFormValid.value) {
    error.value = 'Please fill in all required fields'
    return
  }

  loading.value = true
  error.value = ''

  emit('submit', form.value)
}
</script>

// src/components/forms/ObservationForm.tsx
'use client'

import React, { useEffect, useState } from 'react'
import { useChildrenStore } from '@/stores/children'
import type { Child } from '@/stores/children'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

type ObservationFormData = {
  child_id: string
  observation_date: string
  context: string
  description: string
  development_area: string
  photos: string[]
  videos: string[]
}

interface ObservationFormProps {
  initialData?: Partial<ObservationFormData>
  onSubmit: (data: ObservationFormData) => void
  onCancel: () => void
  loading?: boolean
}

export const ObservationForm = ({ initialData, onSubmit, onCancel, loading: submitting }: ObservationFormProps) => {
  const { children, loading: childrenLoading, error: childrenError, fetchChildren } = useChildrenStore()
  
  const [form, setForm] = useState<ObservationFormData>({
    child_id: initialData?.child_id || '',
    observation_date: initialData?.observation_date || new Date().toISOString().split('T')[0],
    context: initialData?.context || '',
    description: initialData?.description || '',
    development_area: initialData?.development_area || '',
    photos: initialData?.photos || [],
    videos: initialData?.videos || [],
  })

  const [error, setError] = useState('')

  useEffect(() => {
    fetchChildren()
  }, [fetchChildren])

  const isFormValid = form.child_id && form.observation_date && form.description.trim()

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!isFormValid) {
      setError('Bitte füllen Sie alle erforderlichen Felder aus.')
      return
    }
    setError('')
    onSubmit(form)
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { id, value } = e.target
    setForm((prev) => ({ ...prev, [id as keyof ObservationFormData]: value }))
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <div>
        <label htmlFor="child_id" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Kind <span className="text-red-500">*</span>
        </label>
        <select
          id="child_id"
          value={form.child_id}
          onChange={handleChange}
          required
          disabled={childrenLoading}
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all disabled:opacity-50"
        >
          <option value="">{childrenLoading ? 'Lade Kinder...' : 'Kind auswählen'}</option>
          {(children || []).map((child: Child) => (
            <option key={child.id} value={child.id}>
              {child.first_name} {child.last_name}
            </option>
          ))}
        </select>
        {childrenError && (
          <p className="mt-1 text-xs text-red-500">
            Fehler beim Laden der Kinder: {childrenError.message}
          </p>
        )}
      </div>

      <div>
        <label htmlFor="observation_date" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Datum <span className="text-red-500">*</span>
        </label>
        <input
          id="observation_date"
          type="date"
          value={form.observation_date.split('T')[0]}
          onChange={handleChange}
          required
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
        />
      </div>

      <div>
        <label htmlFor="context" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Kontext (Wo/Wann)
        </label>
        <input
          id="context"
          type="text"
          value={form.context}
          onChange={handleChange}
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          placeholder="z.B. Freispiel, Morgenkreis"
        />
      </div>

      <div>
        <label htmlFor="development_area" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Entwicklungsbereich
        </label>
        <select
          id="development_area"
          value={form.development_area}
          onChange={handleChange}
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
        >
          <option value="">Bereich auswählen</option>
          <option value="Social">Sozial</option>
          <option value="Motor">Motorik</option>
          <option value="Language">Sprache</option>
          <option value="Cognitive">Kognitiv</option>
          <option value="Emotional">Emotional</option>
          <option value="Creative">Kreativ</option>
        </select>
      </div>

      <div>
        <label htmlFor="description" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Beschreibung <span className="text-red-500">*</span>
        </label>
        <textarea
          id="description"
          value={form.description}
          onChange={handleChange}
          rows={5}
          required
          className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
          placeholder="Beschreiben Sie Ihre Beobachtung..."
        />
      </div>

      {error && (
        <div className="p-3 bg-red-50 text-red-700 rounded-xl text-xs font-medium border border-red-100">
          {error}
        </div>
      )}

      <div className="flex gap-3 justify-end pt-4">
        <IOSButton
          type="button"
          variant="secondary"
          onClick={onCancel}
          className="px-6 py-2.5"
        >
          Abbrechen
        </IOSButton>
        <IOSButton
          type="submit"
          variant="primary"
          disabled={submitting || !isFormValid}
          className="px-6 py-2.5 min-w-[120px]"
        >
          {submitting ? <LoadingSpinner size="sm" /> : initialData ? 'Speichern' : 'Erstellen'}
        </IOSButton>
      </div>
    </form>
  )
}
