// components/forms/PayrollForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-4">
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="month" class="block text-sm font-medium text-gray-700 mb-2">
          Month <span class="text-red-500">*</span>
        </label>
        <select
          id="month"
          v-model.number="form.month"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        >
          <option v-for="m in 12" :key="m" :value="m">
            {{ getMonthName(m) }}
          </option>
        </select>
      </div>

      <div>
        <label for="year" class="block text-sm font-medium text-gray-700 mb-2">
          Year <span class="text-red-500">*</span>
        </label>
        <input
          id="year"
          v-model.number="form.year"
          type="number"
          required
          :min="2020"
          :max="2100"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="base_salary" class="block text-sm font-medium text-gray-700 mb-2">
          Base Salary (€) <span class="text-red-500">*</span>
        </label>
        <input
          id="base_salary"
          v-model.number="form.base_salary"
          type="number"
          step="0.01"
          required
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="overtime_hours" class="block text-sm font-medium text-gray-700 mb-2">
          Overtime Hours
        </label>
        <input
          id="overtime_hours"
          v-model.number="form.overtime_hours"
          type="number"
          step="0.5"
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="overtime_rate" class="block text-sm font-medium text-gray-700 mb-2">
          Overtime Rate (€/hour)
        </label>
        <input
          id="overtime_rate"
          v-model.number="form.overtime_rate"
          type="number"
          step="0.01"
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="overtime_amount" class="block text-sm font-medium text-gray-700 mb-2">
          Overtime Amount (€)
        </label>
        <input
          id="overtime_amount"
          v-model.number="form.overtime_amount"
          type="number"
          step="0.01"
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="bonuses" class="block text-sm font-medium text-gray-700 mb-2">
          Bonuses (€)
        </label>
        <input
          id="bonuses"
          v-model.number="form.bonuses"
          type="number"
          step="0.01"
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="deductions" class="block text-sm font-medium text-gray-700 mb-2">
          Deductions (€)
        </label>
        <input
          id="deductions"
          v-model.number="form.deductions"
          type="number"
          step="0.01"
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="tax_amount" class="block text-sm font-medium text-gray-700 mb-2">
          Tax Amount (€)
        </label>
        <input
          id="tax_amount"
          v-model.number="form.tax_amount"
          type="number"
          step="0.01"
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="net_salary" class="block text-sm font-medium text-gray-700 mb-2">
          Net Salary (€) <span class="text-red-500">*</span>
        </label>
        <input
          id="net_salary"
          v-model.number="form.net_salary"
          type="number"
          step="0.01"
          required
          min="0"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>
    </div>

    <div>
      <label for="status" class="block text-sm font-medium text-gray-700 mb-2">
        Status <span class="text-red-500">*</span>
      </label>
      <select
        id="status"
        v-model="form.status"
        required
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
      >
        <option value="draft">Draft</option>
        <option value="approved">Approved</option>
        <option value="paid">Paid</option>
      </select>
    </div>

    <div>
      <label for="notes" class="block text-sm font-medium text-gray-700 mb-2">
        Notes
      </label>
      <textarea
        id="notes"
        v-model="form.notes"
        rows="3"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        placeholder="Additional notes..."
      />
    </div>

    <div v-if="error" class="p-3 bg-red-50 text-red-700 rounded-md text-sm">
      {{ error }}
    </div>

    <div class="flex gap-3 justify-end pt-4">
      <button
        type="button"
        @click="$emit('cancel')"
        class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
      >
        Cancel
      </button>
      <button
        type="submit"
        :disabled="loading"
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {{ loading ? 'Saving...' : 'Save Payroll' }}
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import type { StaffPayroll } from '~/stores/payroll'

interface Props {
  staffId?: string
  initialData?: StaffPayroll
}

const props = withDefaults(defineProps<Props>(), {
  staffId: undefined,
  initialData: undefined
})

const emit = defineEmits<{
  (e: 'submit', data: any): void
  (e: 'cancel'): void
}>()

const loading = ref(false)
const error = ref('')

const form = ref({
  staff_id: props.staffId || props.initialData?.staff_id || '',
  month: props.initialData?.month || new Date().getMonth() + 1,
  year: props.initialData?.year || new Date().getFullYear(),
  base_salary: props.initialData?.base_salary || 0,
  overtime_hours: props.initialData?.overtime_hours || 0,
  overtime_rate: props.initialData?.overtime_rate || 0,
  overtime_amount: props.initialData?.overtime_amount || 0,
  bonuses: props.initialData?.bonuses || 0,
  deductions: props.initialData?.deductions || 0,
  tax_amount: props.initialData?.tax_amount || 0,
  net_salary: props.initialData?.net_salary || 0,
  status: props.initialData?.status || 'draft',
  notes: props.initialData?.notes || ''
})

// Auto-calculate overtime amount
watch([() => form.value.overtime_hours, () => form.value.overtime_rate], () => {
  if (form.value.overtime_hours && form.value.overtime_rate) {
    form.value.overtime_amount = form.value.overtime_hours * form.value.overtime_rate
  }
})

// Auto-calculate net salary
watch([
  () => form.value.base_salary,
  () => form.value.overtime_amount,
  () => form.value.bonuses,
  () => form.value.deductions,
  () => form.value.tax_amount
], () => {
  form.value.net_salary = 
    form.value.base_salary +
    form.value.overtime_amount +
    form.value.bonuses -
    form.value.deductions -
    form.value.tax_amount
})

const getMonthName = (month: number) => {
  const date = new Date(2000, month - 1, 1)
  return date.toLocaleString('default', { month: 'long' })
}

const handleSubmit = () => {
  loading.value = true
  error.value = ''

  emit('submit', {
    ...form.value
  })
}
</script>

// src/components/forms/PayrollForm.tsx
'use client'

import React, { useEffect, useMemo, useState } from 'react'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import type { StaffPayroll } from '@/stores/payroll'

type PayrollFormProps = {
  staffId?: string
  initialData?: StaffPayroll
  onSubmit: (data: Partial<StaffPayroll>) => void | Promise<void>
  onCancel: () => void
}

type PayrollFormState = {
  staff_id: string
  month: number
  year: number
  base_salary: number
  overtime_hours: number
  overtime_rate: number
  overtime_amount: number
  bonuses: number
  deductions: number
  tax_amount: number
  net_salary: number
  status: 'draft' | 'approved' | 'paid'
  notes: string
}

function toNumber(value: string) {
  if (value === '') return 0
  const n = Number(value)
  return Number.isFinite(n) ? n : 0
}

export function PayrollForm({ staffId, initialData, onSubmit, onCancel }: PayrollFormProps) {
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const defaultMonth = useMemo(() => new Date().getMonth() + 1, [])
  const defaultYear = useMemo(() => new Date().getFullYear(), [])

  const [form, setForm] = useState<PayrollFormState>(() => ({
    staff_id: staffId || initialData?.staff_id || '',
    month: initialData?.month || defaultMonth,
    year: initialData?.year || defaultYear,
    base_salary: initialData?.base_salary || 0,
    overtime_hours: initialData?.overtime_hours || 0,
    overtime_rate: initialData?.overtime_rate || 0,
    overtime_amount: initialData?.overtime_amount || 0,
    bonuses: initialData?.bonuses || 0,
    deductions: initialData?.deductions || 0,
    tax_amount: initialData?.tax_amount || 0,
    net_salary: initialData?.net_salary || 0,
    status: initialData?.status || 'draft',
    notes: initialData?.notes || '',
  }))

  useEffect(() => {
    setForm({
      staff_id: staffId || initialData?.staff_id || '',
      month: initialData?.month || defaultMonth,
      year: initialData?.year || defaultYear,
      base_salary: initialData?.base_salary || 0,
      overtime_hours: initialData?.overtime_hours || 0,
      overtime_rate: initialData?.overtime_rate || 0,
      overtime_amount: initialData?.overtime_amount || 0,
      bonuses: initialData?.bonuses || 0,
      deductions: initialData?.deductions || 0,
      tax_amount: initialData?.tax_amount || 0,
      net_salary: initialData?.net_salary || 0,
      status: initialData?.status || 'draft',
      notes: initialData?.notes || '',
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [staffId, initialData?.id])

  // Auto-calculate overtime amount from hours * rate.
  useEffect(() => {
    const hours = form.overtime_hours || 0
    const rate = form.overtime_rate || 0
    const overtime_amount = hours * rate
    setForm((prev) => ({ ...prev, overtime_amount }))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.overtime_hours, form.overtime_rate])

  // Auto-calculate net salary.
  useEffect(() => {
    const net_salary =
      (form.base_salary || 0) +
      (form.overtime_amount || 0) +
      (form.bonuses || 0) -
      (form.deductions || 0) -
      (form.tax_amount || 0)

    setForm((prev) => ({ ...prev, net_salary }))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.base_salary, form.overtime_amount, form.bonuses, form.deductions, form.tax_amount])

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { id, value } = e.target

    const numberFields: Array<keyof PayrollFormState> = [
      'month',
      'year',
      'base_salary',
      'overtime_hours',
      'overtime_rate',
      'overtime_amount',
      'bonuses',
      'deductions',
      'tax_amount',
      'net_salary',
    ]

    if (numberFields.includes(id as keyof PayrollFormState)) {
      const nextValue = toNumber(value)
      setForm((prev) => ({ ...prev, [id]: nextValue } as PayrollFormState))
      return
    }

    if (id === 'status') {
      setForm((prev) => ({ ...prev, status: value as PayrollFormState['status'] }))
      return
    }

    if (id === 'staff_id' || id === 'notes') {
      setForm((prev) => ({ ...prev, [id]: value } as PayrollFormState))
      return
    }

    // Fallback (shouldn't happen)
    setForm((prev) => ({ ...prev, [id]: value } as unknown as PayrollFormState))
  }

  const getMonthName = (month: number) => {
    const date = new Date(2000, month - 1, 1)
    return date.toLocaleString('default', { month: 'long' })
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitting(true)
    setError('')

    try {
      if (!form.staff_id) {
        setError('Please select a staff member')
        return
      }

      if (!form.month || !form.year) {
        setError('Please select month and year')
        return
      }

      if (!form.net_salary && form.net_salary !== 0) {
        setError('Please enter a net salary')
        return
      }

      await onSubmit({
        staff_id: form.staff_id,
        month: form.month,
        year: form.year,
        base_salary: form.base_salary,
        overtime_hours: form.overtime_hours,
        overtime_rate: form.overtime_rate,
        overtime_amount: form.overtime_amount,
        bonuses: form.bonuses,
        deductions: form.deductions,
        tax_amount: form.tax_amount,
        net_salary: form.net_salary,
        status: form.status,
        notes: form.notes || undefined,
      })
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to save payroll')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label htmlFor="month" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Month <span className="text-red-500">*</span>
          </label>
          <select
            id="month"
            value={form.month}
            onChange={handleChange}
            required
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          >
            {Array.from({ length: 12 }, (_, i) => i + 1).map((m) => (
              <option key={m} value={m}>
                {getMonthName(m)}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label htmlFor="year" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Year <span className="text-red-500">*</span>
          </label>
          <input
            id="year"
            value={form.year}
            onChange={handleChange}
            type="number"
            required
            min={2020}
            max={2100}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label htmlFor="base_salary" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Base Salary (€) <span className="text-red-500">*</span>
          </label>
          <input
            id="base_salary"
            value={form.base_salary}
            onChange={handleChange}
            type="number"
            step="0.01"
            required
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label htmlFor="overtime_hours" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Overtime Hours
          </label>
          <input
            id="overtime_hours"
            value={form.overtime_hours}
            onChange={handleChange}
            type="number"
            step="0.5"
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label htmlFor="overtime_rate" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Overtime Rate (€/hour)
          </label>
          <input
            id="overtime_rate"
            value={form.overtime_rate}
            onChange={handleChange}
            type="number"
            step="0.01"
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label htmlFor="overtime_amount" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Overtime Amount (€)
          </label>
          <input
            id="overtime_amount"
            value={form.overtime_amount}
            onChange={handleChange}
            type="number"
            step="0.01"
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label htmlFor="bonuses" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Bonuses (€)
          </label>
          <input
            id="bonuses"
            value={form.bonuses}
            onChange={handleChange}
            type="number"
            step="0.01"
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label htmlFor="deductions" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Deductions (€)
          </label>
          <input
            id="deductions"
            value={form.deductions}
            onChange={handleChange}
            type="number"
            step="0.01"
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label htmlFor="tax_amount" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Tax Amount (€)
          </label>
          <input
            id="tax_amount"
            value={form.tax_amount}
            onChange={handleChange}
            type="number"
            step="0.01"
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label htmlFor="net_salary" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Net Salary (€) <span className="text-red-500">*</span>
          </label>
          <input
            id="net_salary"
            value={form.net_salary}
            onChange={handleChange}
            type="number"
            step="0.01"
            required
            min={0}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      <div>
        <label htmlFor="status" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
          Status <span className="text-red-500">*</span>
        </label>
        <select
          id="status"
          value={form.status}
          onChange={handleChange}
          required
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        >
          <option value="draft">Draft</option>
          <option value="approved">Approved</option>
          <option value="paid">Paid</option>
        </select>
      </div>

      <div>
        <label htmlFor="notes" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
          Notes
        </label>
        <textarea
          id="notes"
          value={form.notes}
          onChange={handleChange}
          rows={3}
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          placeholder="Additional notes..."
        />
      </div>

      {error && <div className="p-3 bg-red-50 text-red-700 rounded-md text-sm">{error}</div>}

      <div className="flex gap-3 justify-end pt-4">
        <IOSButton
          type="button"
          variant="secondary"
          onClick={onCancel}
          className="px-4 py-2"
        >
          Cancel
        </IOSButton>
        <IOSButton type="submit" variant="primary" disabled={submitting} className="px-4 py-2">
          {submitting ? <LoadingSpinner size="sm" /> : 'Save Payroll'}
        </IOSButton>
      </div>
    </form>
  )
}
