// components/forms/SalaryConfigForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-4">
    <div>
      <label for="base_salary" class="block text-sm font-medium text-gray-700 mb-2">
        Base Salary (€) <span class="text-red-500">*</span>
      </label>
      <input
        id="base_salary"
        v-model.number="form.base_salary"
        type="number"
        step="0.01"
        required
        min="0"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
      />
    </div>

    <div>
      <label for="hourly_rate" class="block text-sm font-medium text-gray-700 mb-2">
        Hourly Rate (€)
      </label>
      <input
        id="hourly_rate"
        v-model.number="form.hourly_rate"
        type="number"
        step="0.01"
        min="0"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
      />
    </div>

    <div>
      <label for="overtime_multiplier" class="block text-sm font-medium text-gray-700 mb-2">
        Overtime Multiplier
      </label>
      <input
        id="overtime_multiplier"
        v-model.number="form.overtime_multiplier"
        type="number"
        step="0.1"
        min="1"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
      />
      <p class="text-xs text-gray-500 mt-1">Default: 1.5 (time and a half)</p>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="effective_from" class="block text-sm font-medium text-gray-700 mb-2">
          Effective From <span class="text-red-500">*</span>
        </label>
        <input
          id="effective_from"
          v-model="form.effective_from"
          type="date"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="effective_to" class="block text-sm font-medium text-gray-700 mb-2">
          Effective To (Optional)
        </label>
        <input
          id="effective_to"
          v-model="form.effective_to"
          type="date"
          :min="form.effective_from"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>
    </div>

    <div>
      <label for="notes" class="block text-sm font-medium text-gray-700 mb-2">
        Notes
      </label>
      <textarea
        id="notes"
        v-model="form.notes"
        rows="3"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        placeholder="Additional notes about this salary configuration..."
      />
    </div>

    <div v-if="error" class="p-3 bg-red-50 text-red-700 rounded-md text-sm">
      {{ error }}
    </div>

    <div class="flex gap-3 justify-end pt-4">
      <button
        type="button"
        @click="$emit('cancel')"
        class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
      >
        Cancel
      </button>
      <button
        type="submit"
        :disabled="loading"
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {{ loading ? 'Saving...' : 'Save Configuration' }}
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { SalaryConfig } from '~/stores/salaryConfig'

interface Props {
  staffId?: string
  initialData?: SalaryConfig
}

const props = withDefaults(defineProps<Props>(), {
  staffId: undefined,
  initialData: undefined
})

const emit = defineEmits<{
  (e: 'submit', data: any): void
  (e: 'cancel'): void
}>()

const loading = ref(false)
const error = ref('')

const form = ref({
  staff_id: props.staffId || props.initialData?.staff_id || '',
  base_salary: props.initialData?.base_salary || 0,
  hourly_rate: props.initialData?.hourly_rate || undefined,
  overtime_multiplier: props.initialData?.overtime_multiplier || 1.5,
  effective_from: props.initialData?.effective_from || new Date().toISOString().split('T')[0],
  effective_to: props.initialData?.effective_to || undefined,
  notes: props.initialData?.notes || ''
})

const handleSubmit = () => {
  loading.value = true
  error.value = ''

  const submitData: any = {
    ...form.value
  }

  if (!submitData.effective_to) {
    delete submitData.effective_to
  }

  if (!submitData.hourly_rate) {
    delete submitData.hourly_rate
  }

  emit('submit', submitData)
}
</script>

// src/components/forms/SalaryConfigForm.tsx
'use client'

import React, { useEffect, useMemo, useState } from 'react'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { type SalaryConfig } from '@/stores/salaryConfig'

type SalaryConfigFormProps = {
  staffId?: string
  initialData?: SalaryConfig
  onSubmit: (data: Partial<SalaryConfig>) => void | Promise<void>
  onCancel: () => void
}

export function SalaryConfigForm({ staffId, initialData, onSubmit, onCancel }: SalaryConfigFormProps) {
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const defaultEffectiveFrom = useMemo(
    () => new Date().toISOString().split('T')[0],
    []
  )

  const [form, setForm] = useState<{
    staff_id: string
    base_salary: number
    hourly_rate?: number
    overtime_multiplier: number
    effective_from: string
    effective_to?: string
    notes: string
  }>(() => ({
    staff_id: staffId || initialData?.staff_id || '',
    base_salary: initialData?.base_salary || 0,
    hourly_rate: initialData?.hourly_rate,
    overtime_multiplier: initialData?.overtime_multiplier || 1.5,
    effective_from: initialData?.effective_from || defaultEffectiveFrom,
    effective_to: initialData?.effective_to,
    notes: initialData?.notes || '',
  }))

  useEffect(() => {
    setForm({
      staff_id: staffId || initialData?.staff_id || '',
      base_salary: initialData?.base_salary || 0,
      hourly_rate: initialData?.hourly_rate,
      overtime_multiplier: initialData?.overtime_multiplier || 1.5,
      effective_from: initialData?.effective_from || defaultEffectiveFrom,
      effective_to: initialData?.effective_to,
      notes: initialData?.notes || '',
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [staffId, initialData?.id])

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { id, value } = e.target

    if (id === 'hourly_rate') {
      const num = value === '' ? undefined : Number(value)
      setForm((prev) => ({ ...prev, hourly_rate: num }))
      return
    }

    if (id === 'base_salary' || id === 'overtime_multiplier') {
      const num = value === '' ? 0 : Number(value)
      setForm((prev) => ({ ...prev, [id]: num }))
      return
    }

    if (id === 'effective_to') {
      setForm((prev) => ({
        ...prev,
        effective_to: value ? value : undefined,
      }))
      return
    }

    if (id === 'staff_id' || id === 'effective_from' || id === 'notes') {
      setForm((prev) => ({
        ...prev,
        [id]: value,
      }))
      return
    }

    setForm((prev) => ({ ...prev, [id]: value }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitting(true)
    setError('')

    try {
      if (!form.staff_id) {
        setError('Please select a staff member')
        return
      }

      if (!form.base_salary && form.base_salary !== 0) {
        setError('Please enter a base salary')
        return
      }

      const payload: Partial<SalaryConfig> = {
        staff_id: form.staff_id,
        base_salary: form.base_salary,
        overtime_multiplier: form.overtime_multiplier,
        effective_from: form.effective_from,
        notes: form.notes || undefined,
        ...(typeof form.hourly_rate === 'number' ? { hourly_rate: form.hourly_rate } : {}),
        ...(form.effective_to ? { effective_to: form.effective_to } : {}),
      }

      await onSubmit(payload)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to save configuration')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label htmlFor="base_salary" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
          Base Salary (€) <span className="text-red-500">*</span>
        </label>
        <input
          id="base_salary"
          value={form.base_salary}
          onChange={handleChange}
          type="number"
          step="0.01"
          required
          min="0"
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label htmlFor="hourly_rate" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
          Hourly Rate (€)
        </label>
        <input
          id="hourly_rate"
          value={form.hourly_rate ?? ''}
          onChange={handleChange}
          type="number"
          step="0.01"
          min="0"
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label htmlFor="overtime_multiplier" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
          Overtime Multiplier
        </label>
        <input
          id="overtime_multiplier"
          value={form.overtime_multiplier}
          onChange={handleChange}
          type="number"
          step="0.1"
          min="1"
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
        <p className="text-xs text-ui-soft mt-1">Default: 1.5 (time and a half)</p>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label htmlFor="effective_from" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Effective From <span className="text-red-500">*</span>
          </label>
          <input
            id="effective_from"
            value={form.effective_from}
            onChange={handleChange}
            type="date"
            required
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>

        <div>
          <label htmlFor="effective_to" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
            Effective To (Optional)
          </label>
          <input
            id="effective_to"
            value={form.effective_to ?? ''}
            onChange={handleChange}
            type="date"
            min={form.effective_from}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      <div>
        <label htmlFor="notes" className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-2">
          Notes
        </label>
        <textarea
          id="notes"
          value={form.notes}
          onChange={handleChange}
          rows={3}
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          placeholder="Additional notes about this salary configuration..."
        />
      </div>

      {error && (
        <div className="p-3 bg-red-50 text-red-700 rounded-md text-sm">
          {error}
        </div>
      )}

      <div className="flex gap-3 justify-end pt-4">
        <IOSButton
          type="button"
          variant="secondary"
          onClick={onCancel}
          className="px-4 py-2"
        >
          Cancel
        </IOSButton>
        <IOSButton
          type="submit"
          variant="primary"
          disabled={submitting}
          className="px-4 py-2"
        >
          {submitting ? <LoadingSpinner size="sm" /> : 'Save Configuration'}
        </IOSButton>
      </div>
    </form>
  )
}
