// components/forms/TeacherLeaveRequestForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-4">
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="start_date" class="block text-sm font-medium text-gray-700 mb-2">
          Start Date <span class="text-red-500">*</span>
        </label>
        <input
          id="start_date"
          v-model="form.start_date"
          type="date"
          required
          :min="minDate"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="end_date" class="block text-sm font-medium text-gray-700 mb-2">
          End Date <span class="text-red-500">*</span>
        </label>
        <input
          id="end_date"
          v-model="form.end_date"
          type="date"
          required
          :min="form.start_date || minDate"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>
    </div>

    <div>
      <label for="leave_type" class="block text-sm font-medium text-gray-700 mb-2">
        Leave Type <span class="text-red-500">*</span>
      </label>
      <select
        id="leave_type"
        v-model="form.leave_type"
        required
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
      >
        <option value="vacation">Vacation</option>
        <option value="sick">Sick Leave</option>
        <option value="personal">Personal</option>
        <option value="other">Other</option>
      </select>
    </div>

    <div>
      <label for="reason" class="block text-sm font-medium text-gray-700 mb-2">
        Reason <span class="text-red-500">*</span>
      </label>
      <textarea
        id="reason"
        v-model="form.reason"
        required
        rows="4"
        class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        placeholder="Please provide a reason for your leave request..."
      />
    </div>

    <div v-if="error" class="p-3 bg-red-50 text-red-700 rounded-md text-sm">
      {{ error }}
    </div>

    <div class="flex gap-3 justify-end pt-4">
      <button
        type="button"
        @click="$emit('cancel')"
        class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
      >
        Cancel
      </button>
      <button
        type="submit"
        :disabled="loading || !isFormValid"
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {{ loading ? 'Submitting...' : 'Submit Request' }}
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

interface Props {
  initialData?: any
}

const props = withDefaults(defineProps<Props>(), {
  initialData: undefined
})

const emit = defineEmits<{
  (e: 'submit', data: any): void
  (e: 'cancel'): void
}>()

const loading = ref(false)
const error = ref('')

const minDate = new Date().toISOString().split('T')[0]

const form = ref({
  start_date: props.initialData?.start_date || '',
  end_date: props.initialData?.end_date || '',
  leave_type: props.initialData?.leave_type || 'vacation',
  reason: props.initialData?.reason || ''
})

const isFormValid = computed(() => {
  return form.value.start_date &&
    form.value.end_date &&
    form.value.leave_type &&
    form.value.reason.trim() &&
    new Date(form.value.end_date) >= new Date(form.value.start_date)
})

const handleSubmit = () => {
  if (!isFormValid.value) {
    error.value = 'Please fill in all required fields and ensure end date is after start date'
    return
  }

  loading.value = true
  error.value = ''

  emit('submit', {
    ...form.value
  })
}
</script>

// src/components/forms/TeacherLeaveRequestForm.tsx
'use client'

import React, { useState, useMemo } from 'react'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

interface TeacherLeaveRequestFormProps {
  initialData?: any
  onSubmit: (data: any) => void
  onCancel: () => void
  loading?: boolean
}

export const TeacherLeaveRequestForm = ({
  initialData,
  onSubmit,
  onCancel,
  loading: submitting
}: TeacherLeaveRequestFormProps) => {
  const [form, setForm] = useState({
    start_date: initialData?.start_date || '',
    end_date: initialData?.end_date || '',
    leave_type: initialData?.leave_type || 'vacation',
    reason: initialData?.reason || ''
  })

  const [error, setError] = useState('')

  const minDate = useMemo(() => new Date().toISOString().split('T')[0], [])

  const isFormValid = 
    form.start_date && 
    form.end_date && 
    form.leave_type && 
    form.reason.trim() &&
    new Date(form.end_date) >= new Date(form.start_date)

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { id, value } = e.target
    setForm(prev => ({ ...prev, [id]: value }))
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!isFormValid) {
      setError('Bitte füllen Sie alle erforderlichen Felder aus und stellen Sie sicher, dass das Enddatum nach dem Startdatum liegt.')
      return
    }

    setError('')
    onSubmit({
      ...form,
      reason: form.reason.trim(),
      status: 'pending'
    })
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label htmlFor="start_date" className="block text-sm font-semibold text-gray-700 mb-1.5">
            Startdatum <span className="text-red-500">*</span>
          </label>
          <input
            id="start_date"
            type="date"
            value={form.start_date}
            onChange={handleChange}
            required
            min={minDate}
            className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          />
        </div>

        <div>
          <label htmlFor="end_date" className="block text-sm font-semibold text-gray-700 mb-1.5">
            Enddatum <span className="text-red-500">*</span>
          </label>
          <input
            id="end_date"
            type="date"
            value={form.end_date}
            onChange={handleChange}
            required
            min={form.start_date || minDate}
            className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          />
        </div>
      </div>

      <div>
        <label htmlFor="leave_type" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Art des Urlaubs <span className="text-red-500">*</span>
        </label>
        <select
          id="leave_type"
          value={form.leave_type}
          onChange={handleChange}
          required
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
        >
          <option value="vacation">Erholungsurlaub</option>
          <option value="sick">Krankmeldung</option>
          <option value="personal">Persönliche Gründe</option>
          <option value="other">Sonstiges</option>
        </select>
      </div>

      <div>
        <label htmlFor="reason" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Grund <span className="text-red-500">*</span>
        </label>
        <textarea
          id="reason"
          value={form.reason}
          onChange={handleChange}
          rows={4}
          required
          className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
          placeholder="Bitte geben Sie einen Grund für Ihren Urlaubsantrag an..."
        />
      </div>

      {error && (
        <div className="p-3 bg-red-50 text-red-700 rounded-xl text-xs font-medium border border-red-100">
          {error}
        </div>
      )}

      <div className="flex gap-3 justify-end pt-4">
        <IOSButton
          type="button"
          variant="secondary"
          onClick={onCancel}
          className="px-6 py-2.5 font-bold"
        >
          Abbrechen
        </IOSButton>
        <IOSButton
          type="submit"
          variant="primary"
          disabled={submitting || !isFormValid}
          className="px-8 py-2.5 font-bold min-w-[160px]"
        >
          {submitting ? <LoadingSpinner size="sm" /> : 'Antrag stellen'}
        </IOSButton>
      </div>
    </form>
  )
}
