// src/components/forms/LeaveRequestForm.tsx
'use client'

import React, { useState, useMemo } from 'react'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'

interface LeaveRequestFormProps {
  children: any[]
  onSubmit: (data: any) => void
  onCancel: () => void
  loading?: boolean
}

export const LeaveRequestForm = ({
  children,
  onSubmit,
  onCancel,
  loading: submitting
}: LeaveRequestFormProps) => {
  const [form, setForm] = useState({
    child_id: '',
    start_date: '',
    end_date: '',
    leave_type: '' as 'sick' | 'vacation' | 'other' | '',
    reason: '',
    notes: ''
  })

  const [error, setError] = useState('')

  const minDate = useMemo(() => new Date().toISOString().split('T')[0], [])

  const isFormValid = 
    form.child_id && 
    form.start_date && 
    form.end_date && 
    form.leave_type && 
    form.reason.trim()

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { id, value } = e.target
    setForm(prev => ({ ...prev, [id]: value }))
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!isFormValid) {
      setError('Bitte füllen Sie alle erforderlichen Felder aus.')
      return
    }

    if (new Date(form.end_date) < new Date(form.start_date)) {
      setError('Das Enddatum muss nach dem Startdatum liegen.')
      return
    }

    setError('')
    onSubmit({
      ...form,
      reason: form.reason.trim(),
      notes: form.notes.trim() || undefined,
      status: 'pending'
    })
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label htmlFor="child_id" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
          Kind <span className="text-red-500">*</span>
        </label>
        <select
          id="child_id"
          value={form.child_id}
          onChange={handleChange}
          required
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
        >
          <option value="">Kind auswählen</option>
          {children.map(child => (
            <option key={child.id} value={child.id}>
              {child.first_name} {child.last_name}
            </option>
          ))}
        </select>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label htmlFor="start_date" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
            Startdatum <span className="text-red-500">*</span>
          </label>
          <input
            id="start_date"
            type="date"
            value={form.start_date}
            onChange={handleChange}
            required
            min={minDate}
            className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          />
        </div>

        <div>
          <label htmlFor="end_date" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
            Enddatum <span className="text-red-500">*</span>
          </label>
          <input
            id="end_date"
            type="date"
            value={form.end_date}
            onChange={handleChange}
            required
            min={form.start_date || minDate}
            className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          />
        </div>
      </div>

      <div>
        <label htmlFor="leave_type" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
          Art der Abwesenheit <span className="text-red-500">*</span>
        </label>
        <select
          id="leave_type"
          value={form.leave_type}
          onChange={handleChange}
          required
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
        >
          <option value="">Art auswählen</option>
          <option value="sick">Krankheit</option>
          <option value="vacation">Urlaub</option>
          <option value="other">Sonstiges</option>
        </select>
      </div>

      <div>
        <label htmlFor="reason" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
          Grund <span className="text-red-500">*</span>
        </label>
        <textarea
          id="reason"
          value={form.reason}
          onChange={handleChange}
          rows={3}
          required
          className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
          placeholder="Geben Sie den Grund für die Abwesenheit an..."
        />
      </div>

      <div>
        <label htmlFor="notes" className="block text-sm font-semibold text-slate-700 dark:text-slate-200 mb-1.5">
          Zusätzliche Anmerkungen (Optional)
        </label>
        <textarea
          id="notes"
          value={form.notes}
          onChange={handleChange}
          rows={2}
          className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
          placeholder="Weitere Informationen..."
        />
      </div>

      {error && (
        <div className="p-3 bg-red-50 text-red-700 rounded-xl text-xs font-medium border border-red-100">
          {error}
        </div>
      )}

      <div className="flex gap-3 justify-end pt-4">
        <IOSButton
          type="button"
          variant="secondary"
          onClick={onCancel}
          className="px-6 py-2.5 font-bold"
        >
          Abbrechen
        </IOSButton>
        <IOSButton
          type="submit"
          variant="primary"
          disabled={submitting || !isFormValid}
          className="px-6 py-2.5 font-bold min-w-[140px]"
        >
          {submitting ? <LoadingSpinner size="sm" /> : 'Absenden'}
        </IOSButton>
      </div>
    </form>
  )
}

// components/forms/LeaveRequestForm.vue
<template>
  <div class="p-6">
    <h3 class="text-lg font-medium text-gray-900 mb-4">Request Leave</h3>
    
    <form @submit.prevent="handleSubmit">
      <div class="mb-4">
        <label for="child_id" class="block text-sm font-medium text-gray-700 mb-2">
          Child <span class="text-red-500">*</span>
        </label>
        <select
          id="child_id"
          v-model="form.child_id"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        >
          <option value="">Select a child</option>
          <option v-for="child in children" :key="child.id" :value="child.id">
            {{ child.first_name }} {{ child.last_name }}
          </option>
        </select>
      </div>

      <div class="grid grid-cols-2 gap-4 mb-4">
        <div>
          <label for="start_date" class="block text-sm font-medium text-gray-700 mb-2">
            Start Date <span class="text-red-500">*</span>
          </label>
          <input
            id="start_date"
            v-model="form.start_date"
            type="date"
            required
            :min="minDate"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>

        <div>
          <label for="end_date" class="block text-sm font-medium text-gray-700 mb-2">
            End Date <span class="text-red-500">*</span>
          </label>
          <input
            id="end_date"
            v-model="form.end_date"
            type="date"
            required
            :min="form.start_date || minDate"
            class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
      </div>

      <div class="mb-4">
        <label for="leave_type" class="block text-sm font-medium text-gray-700 mb-2">
          Leave Type <span class="text-red-500">*</span>
        </label>
        <select
          id="leave_type"
          v-model="form.leave_type"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        >
          <option value="">Select type</option>
          <option value="sick">Sick</option>
          <option value="vacation">Vacation</option>
          <option value="other">Other</option>
        </select>
      </div>

      <div class="mb-4">
        <label for="reason" class="block text-sm font-medium text-gray-700 mb-2">
          Reason <span class="text-red-500">*</span>
        </label>
        <textarea
          id="reason"
          v-model="form.reason"
          rows="3"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="Enter reason for leave request..."
        />
      </div>

      <div class="mb-4">
        <label for="notes" class="block text-sm font-medium text-gray-700 mb-2">
          Additional Notes (Optional)
        </label>
        <textarea
          id="notes"
          v-model="form.notes"
          rows="2"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="Any additional information..."
        />
      </div>

      <div v-if="error" class="mb-4 p-3 bg-red-50 text-red-700 rounded-md text-sm">
        {{ error }}
      </div>

      <div class="flex gap-3 justify-end">
        <button
          type="button"
          @click="$emit('cancel')"
          class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          :disabled="loading || !isFormValid"
          class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ loading ? 'Submitting...' : 'Submit Request' }}
        </button>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useAuthStore } from '~/stores/auth'
import { useLeaveRequestsStore } from '~/stores/leaveRequests'

const props = defineProps<{
  children: any[]
}>()

const emit = defineEmits<{
  (e: 'submit', data: any): void
  (e: 'cancel'): void
}>()

const authStore = useAuthStore()
const leaveRequestsStore = useLeaveRequestsStore()

const form = ref({
  child_id: '',
  start_date: '',
  end_date: '',
  leave_type: '' as 'sick' | 'vacation' | 'other' | '',
  reason: '',
  notes: ''
})

const loading = ref(false)
const error = ref('')

const minDate = computed(() => {
  return new Date().toISOString().split('T')[0]
})

const isFormValid = computed(() => {
  return form.value.child_id &&
    form.value.start_date &&
    form.value.end_date &&
    form.value.leave_type &&
    form.value.reason.trim()
})

const handleSubmit = async () => {
  if (!isFormValid.value) {
    error.value = 'Please fill in all required fields'
    return
  }

  if (new Date(form.value.end_date) < new Date(form.value.start_date)) {
    error.value = 'End date must be after start date'
    return
  }

  loading.value = true
  error.value = ''

  try {
    const requestData = {
      child_id: form.value.child_id,
      parent_id: authStore.user?.id,
      start_date: form.value.start_date,
      end_date: form.value.end_date,
      leave_type: form.value.leave_type,
      reason: form.value.reason.trim(),
      notes: form.value.notes.trim() || undefined,
      status: 'pending' as const
    }

    emit('submit', requestData)
  } catch (e: any) {
    error.value = e.message || 'Failed to submit leave request'
  } finally {
    loading.value = false
  }
}
</script>
