// next-app/src/components/forms/PortfolioForm.tsx
'use client'

import React, { useState, useEffect, useMemo } from 'react'
import { IOSButton } from '@/components/ui/IOSButton'
import { LoadingSpinner } from '@/components/common/LoadingSpinner'
import { useChildrenStore } from '@/stores/children'

interface PortfolioFormProps {
  initialData?: any
  onSubmit: (data: any) => void
  onCancel: () => void
  loading?: boolean
}

export const PortfolioForm = ({
  initialData,
  onSubmit,
  onCancel,
  loading: submitting
}: PortfolioFormProps) => {
  const { children, loading: childrenLoading, fetchChildren } = useChildrenStore()
  
  const [form, setForm] = useState({
    child_id: initialData?.child_id || '',
    title: initialData?.title || '',
    portfolio_type: (initialData?.portfolio_type || 'other') as 'artwork' | 'photo' | 'achievement' | 'activity' | 'milestone' | 'other',
    description: initialData?.description || '',
    content: initialData?.content || '',
    date: initialData?.date || new Date().toISOString().split('T')[0],
    attachments: initialData?.attachments || [] as string[]
  })

  const [error, setError] = useState('')

  useEffect(() => {
    fetchChildren()
  }, [fetchChildren])

  const isFormValid = 
    form.child_id && 
    form.title && 
    form.portfolio_type && 
    form.date

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { id, value } = e.target
    setForm(prev => ({ ...prev, [id]: value }))
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!isFormValid) {
      setError('Bitte füllen Sie alle erforderlichen Felder aus.')
      return
    }

    setError('')
    onSubmit(form)
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label htmlFor="child_id" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Kind <span className="text-red-500">*</span>
        </label>
        <select
          id="child_id"
          value={form.child_id}
          onChange={handleChange}
          required
          disabled={childrenLoading}
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all disabled:opacity-50"
        >
          <option value="">{childrenLoading ? 'Lädt...' : 'Kind auswählen'}</option>
          {children.map(child => (
            <option key={child.id} value={child.id}>
              {child.first_name} {child.last_name}
            </option>
          ))}
        </select>
      </div>

      <div>
        <label htmlFor="title" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Titel <span className="text-red-500">*</span>
        </label>
        <input
          id="title"
          type="text"
          value={form.title}
          onChange={handleChange}
          required
          className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          placeholder="z.B. Kunstwerk - Frühlingsblumen"
        />
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label htmlFor="portfolio_type" className="block text-sm font-semibold text-gray-700 mb-1.5">
            Typ <span className="text-red-500">*</span>
          </label>
          <select
            id="portfolio_type"
            value={form.portfolio_type}
            onChange={handleChange}
            required
            className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          >
            <option value="artwork">Kunstwerk</option>
            <option value="photo">Foto</option>
            <option value="achievement">Leistung</option>
            <option value="activity">Aktivität</option>
            <option value="milestone">Meilenstein</option>
            <option value="other">Sonstiges</option>
          </select>
        </div>

        <div>
          <label htmlFor="date" className="block text-sm font-semibold text-gray-700 mb-1.5">
            Datum <span className="text-red-500">*</span>
          </label>
          <input
            id="date"
            type="date"
            value={form.date}
            onChange={handleChange}
            required
            className="w-full px-4 py-2.5 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all"
          />
        </div>
      </div>

      <div>
        <label htmlFor="description" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Kurze Beschreibung
        </label>
        <textarea
          id="description"
          value={form.description}
          onChange={handleChange}
          rows={2}
          className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
          placeholder="Kurze Zusammenfassung..."
        />
      </div>

      <div>
        <label htmlFor="content" className="block text-sm font-semibold text-gray-700 mb-1.5">
          Detaillierter Inhalt / Notizen
        </label>
        <textarea
          id="content"
          value={form.content}
          onChange={handleChange}
          rows={4}
          className="w-full px-4 py-3 bg-white border border-black/10 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-[#667eea] transition-all resize-none"
          placeholder="Detaillierte Informationen..."
        />
      </div>

      {error && (
        <div className="p-3 bg-red-50 text-red-700 rounded-xl text-xs font-medium border border-red-100">
          {error}
        </div>
      )}

      <div className="flex gap-3 justify-end pt-4">
        <IOSButton
          type="button"
          variant="secondary"
          onClick={onCancel}
          className="px-6 py-2.5 font-bold"
        >
          Abbrechen
        </IOSButton>
        <IOSButton
          type="submit"
          variant="primary"
          disabled={submitting || !isFormValid}
          className="px-8 py-2.5 font-bold min-w-[160px]"
        >
          {submitting ? <LoadingSpinner size="sm" /> : 'Erstellen'}
        </IOSButton>
      </div>
    </form>
  )
}

// components/forms/PortfolioForm.vue
<template>
  <form @submit.prevent="handleSubmit">
    <div class="space-y-4">
      <div>
        <label for="child_id" class="block text-sm font-medium text-gray-700 mb-2">
          Child <span class="text-red-500">*</span>
        </label>
        <select
          id="child_id"
          v-model="form.child_id"
          required
          :disabled="childrenLoading"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <option value="">{{ childrenLoading ? 'Loading children...' : 'Select a child' }}</option>
          <option v-for="child in children" :key="child.id" :value="child.id">
            {{ child.first_name }} {{ child.last_name }}
          </option>
        </select>
        <p v-if="childrenError" class="mt-1 text-sm text-red-600">
          Error loading children: {{ childrenError.message }}
        </p>
      </div>

      <div>
        <label for="title" class="block text-sm font-medium text-gray-700 mb-2">
          Title <span class="text-red-500">*</span>
        </label>
        <input
          id="title"
          v-model="form.title"
          type="text"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., Artwork - Spring Flowers"
        />
      </div>

      <div>
        <label for="portfolio_type" class="block text-sm font-medium text-gray-700 mb-2">
          Type <span class="text-red-500">*</span>
        </label>
        <select
          id="portfolio_type"
          v-model="form.portfolio_type"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        >
          <option value="">Select type</option>
          <option value="artwork">Artwork</option>
          <option value="photo">Photo</option>
          <option value="achievement">Achievement</option>
          <option value="activity">Activity</option>
          <option value="milestone">Milestone</option>
          <option value="other">Other</option>
        </select>
      </div>

      <div>
        <label for="date" class="block text-sm font-medium text-gray-700 mb-2">
          Date <span class="text-red-500">*</span>
        </label>
        <input
          id="date"
          v-model="form.date"
          type="date"
          required
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label for="description" class="block text-sm font-medium text-gray-700 mb-2">
          Description
        </label>
        <textarea
          id="description"
          v-model="form.description"
          rows="3"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          placeholder="Brief description..."
        />
      </div>

      <div>
        <label for="content" class="block text-sm font-medium text-gray-700 mb-2">
          Content
        </label>
        <textarea
          id="content"
          v-model="form.content"
          rows="4"
          class="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
          placeholder="Detailed content or notes..."
        />
      </div>

      <div v-if="error" class="p-3 bg-red-50 text-red-700 rounded-md text-sm">
        {{ error }}
      </div>

      <div class="flex gap-3 justify-end">
        <button
          type="button"
          @click="$emit('cancel')"
          class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          :disabled="loading || !isFormValid"
          class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ loading ? 'Creating...' : 'Create Portfolio Item' }}
        </button>
      </div>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useChildrenStore } from '~/stores/children'

const emit = defineEmits<{
  (e: 'submit', data: any): void
  (e: 'cancel'): void
}>()

const childrenStore = useChildrenStore()
const { children, loading: childrenLoading, error: childrenError } = storeToRefs(childrenStore)

const form = ref({
  child_id: '',
  title: '',
  portfolio_type: '' as 'artwork' | 'photo' | 'achievement' | 'activity' | 'milestone' | 'other',
  description: '',
  content: '',
  date: new Date().toISOString().split('T')[0],
  attachments: [] as string[]
})

const loading = ref(false)
const error = ref('')

const isFormValid = computed(() => {
  return form.value.child_id &&
    form.value.title &&
    form.value.portfolio_type &&
    form.value.date
})

onMounted(async () => {
  await childrenStore.fetchChildren()
})

const handleSubmit = () => {
  if (!isFormValid.value) {
    error.value = 'Please fill in all required fields'
    return
  }

  loading.value = true
  error.value = ''

  emit('submit', form.value)
}
</script>
